### PR TITLE
Favors strategy overrides for top-level dependencies

### PR DESCRIPTION
**Pull request by mrinaldi**
Fixes regression for #55.

### CODE REVIEW

**Comment by forki** [comment]
thanks. it also fixes https://github.com/fsprojects/Paket/commit/0e4557086fb4c5f3dda7761efa1037de24d459cf

**Comment by mrinaldi** [comment]
For a `paket.dependencies` like this:
```
strategy min
source http://nuget.org/api/v2

nuget Nancy.Bootstrappers.Windsor ~> 0.23
nuget Castle.Windsor
```

What do you think the version of `Castle.Windsor` should be when we update all?
`3.2.1` (favoring the strategy option) or `3.3.0` (lastest one)

I mean, when we are updating all and resolving top-level dependencies that are also transitive, should we only favor [strategy overrides](http://fsprojects.github.io/Paket/nuget-dependencies.html#Strategy-modifiers) (`!` and `@`), or should we favor the [strategy option](http://fsprojects.github.io/Paket/dependencies-file.html#Strategy-option) also?

**Comment by forki** [comment]
3.2.1 is the only version that works with Nancy.Bootstrappers.Windsor 0.23

**Comment by mrinaldi** [comment]
Sorry, may be that was a bad example.

How about this one:
```
strategy min
source http://nuget.org/api/v2

nuget Castle.Core
nuget Castle.Windsor
```

Note the `strategy min`. What do you think the version of Castle.Core should be when we update all?
`3.2.1` (favoring the strategy option) or `3.3.0` (lastest one)

**Comment by forki** [comment]
yeah that is really tricky. I guess we can take any Castle.Windsor (probably the latest) and need to find the lowest matching Castle.Core

**Comment by mrinaldi** [comment]
Alright. This PR is fine then.

**Comment by forki** [comment]
cool. https://github.com/fsprojects/Paket/commit/7f10a2fc3964786937a48924c5bc7b767d12787b

**Comment by agross** [comment]
Cool! :+1:

**Pull request merged**
