### PR TITLE
Ignore disabled upstream feeds

### PR DESCRIPTION
**Pull request by theimowski**

### CODE REVIEW

**Comment by forki** [comment]
any ideas why the mono build fails on the sample?

**Comment by forki** [comment]
I guess it was https://github.com/fsprojects/Paket/commit/6cce93377a84d285fbd741de7755c128851ec1cd#diff-86117e2b5523a68369ab3089fdcff773R79

thanks for contributing!

**Comment by theimowski** [comment]
ah didn't know Mono doesn't like these - do you know exact reason why that happens?

**Comment by forki** [comment]
Yes. Filename is case-sensitive. You named the folder "NuGet..." but wrote
"Nuget..." in test. It just didn't find the file...

**Comment by theimowski** [comment]
ok I understand know - didn't notice case sensitive file names. 
you also changed `preservenewset` to `copyalways` - is there any reason for that why mono would fail otherwise?

**Comment by forki** [comment]
The copyalways was only my first thought. But it wasn't the reason.
Everything was ok, only the file was not good on nix

**Comment by theimowski** [comment]
I see, glad I could be of help!

**Pull request merged**
