### PR TITLE
Mono boringssl: retry up to 10 times / show *which* path is too long, if _FileInfo_ fails

### PR DESCRIPTION
**Pull request by 0x53A**
This should improve the travis test results

both commits were extracted from my other PRs

### CODE REVIEW

**Comment by 0x53A** [comment]
try 1: 4/6 green
image

Failures:
image

image

**Comment by matthid** [comment]
Nice try, but it seems like mono just doesn't like paket

**Comment by 0x53A** [comment]
The nightly is a lot better. With latest / 5.2, there are assertions and crashes in malloc, etc, all over the place, but with nightly, I could only find issues with boringssl / "no performance data received".

**Comment by 0x53A** [comment]
Currently, Travis easily gets a long backlog:

image

I propose to drop 5.2, this would cut the build time by 1/3

**Comment by matthid** [comment]
Kudos for not giving up :P

**Comment by 0x53A** [comment]
It still failed with that boring-ssl bug, but I couldn't see whether my check was incorrect, or whether it really failed 10 times in a row.

That's why I added a throw with a custom message, but now it doesn't fail anymore at all :\

**Pull request merged**
