### PR TITLE
redirects option clarification

### PR DESCRIPTION
**Pull request by cloudRoutine**

### CODE REVIEW

**Comment by forki** [comment]
unless you specify that other option

**Comment by cloudRoutine** [comment]
there's an option to make it create app.config files?!?

**Comment by forki** [comment]
--createnewbindingfiles

**Comment by cloudRoutine** [comment]
is that documented anywhere? it definitely doesn't come up in the commandline help

**Comment by forki** [comment]
http://fsprojects.github.io/Paket/paket-install.html shows it

**Comment by cloudRoutine** [comment]
neat, TIL

**Comment by forki** [comment]
Thanks for fixing the docs

**Pull request merged**
