### PR TITLE
try to cache proxy

### PR DESCRIPTION
**Pull request by forki**
for a couple of users it seems to be very very slow to calc the proxy. see https://gitter.im/fsprojects/Paket discussion with @alexeyzimarev

### CODE REVIEW

**Comment by forki** [comment]
//cc @vasily-kirichenko could you please take a look?

**Comment by vasily-kirichenko** [comment]
Looks like an ordinary thread safe memoization. Maybe it is worth to extract `memoze` into some core module.

**Comment by forki** [comment]
the question is more: do you think it's enough to cache proxy per HTTP host?

**Comment by vasily-kirichenko** [comment]
No idea.

**Comment by forki** [comment]
fair enough ;-)

**Comment by forki** [comment]
I released this as 2.16.0-alpha001.
ypu can get it with `paket.bootstrapper.exe prerelease`

@alexeyzimarev, @alistair please check if it improves things

@vasily-kirichenko  could you please verify that we don't break you

thanks everbody.

**Comment by forki** [comment]
@dnauck you are also behind proxy, right?

**Comment by alexeyzimarev** [comment]
I am at home now and have no proxy. Will be able to check tomorrow if I would reach my machine at work, I will be at another office for three days.

**Comment by alistair** [comment]
So I have just updated to the latest,  cleaned cache and packages directory and run the following

https://gist.github.com/alistair/65cba5d92556e6f0457c

Time taken has dropped from 7 minutes to 1.

**Comment by dnauck** [comment]
@forki no .. not with my dev machine, cannot test

**Comment by alexeyzimarev** [comment]
I tested with 2.16.0 and it works splendidly :+1: 46 seconds instead of seven minutes.

**Comment by forki** [comment]
Awesome. Thanks for all the help here.

**Comment by vasily-kirichenko** [comment]
Tested `paket outdated` on 2.16.0. Works OK, but I'm not sure it's faster.

**Comment by forki** [comment]
It's only faster for a handful of people where the proxy detection was
super slow. Most people (like myself) will not have perf gains. But I was
worried that caching might break things.

**Pull request merged**
