### PR TITLE
Xamarin.Mac supports .Net Standard 2.0

### PR DESCRIPTION
**Pull request by sergey-tihon**
fix for #3500

### CODE REVIEW

**Comment by forki** [comment]
What about 2.1?

Sergey Tihon <notifications@github.com> schrieb am So., 14. Apr. 2019,
21:11:

**Comment by matthid** [comment]
How does that fit into the table at the end of [this document](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks)?

**Comment by sergey-tihon** [comment]
@forki  I cannot find info about 2.1 [except this](https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/):

> .NET Core 3.0 as well as upcoming versions of Xamarin, Mono, and Unity will be updated to implement .NET Standard 2.1.

I assume that it is not released yet.

@matthid at least based on [this table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), it is supported 
_NET_Standard___Microsoft_Docs


BTH the difference between `Modern` & `Full` version of `Xamarin.Mac` still not clear for me
Fullscreen_4_15_19__10_13_AM
Fullscreen_4_15_19__10_14_AM

**Comment by matthid** [comment]
Question is how do they differ in the NuGet package. Maybe they have different monikers or the moniker is versioned now?
What about people using older versions of Xamarin and a newer version of Paket (including this PR). That will lead to issues, correct? Or are all Xamarin users forced to use latest somehow?

**Comment by forki** [comment]
yeah it's weird that they only have one moniker. that's nuts

**Comment by sergey-tihon** [comment]
I have no idea, tbh, I think depends on the IDE version that you have (latest available at the install time). I just know that latest Paket generate incorrect assembly references nowadays.

Do you know Xamarin expert that can consult us ? // cc @TimLariviere

**Pull request merged**
