### PR TITLE
Add .NETCoreApp2.1 and UAP10.0.16300 tfms

### PR DESCRIPTION
**Pull request by JarnoNijboer**
Possible fix for #3081

When restoring [fake-bootstrap](https://github.com/matthid/fake-bootstrap), errors were appearing about .NETCoreApp2.1 and UAP10.0.16300 TFMs
Added these TFMs to FrameworkHandling.fs and fixed broken tests. If more changes are needed, let me know

### CODE REVIEW

**Comment by forki** [comment]
the fix looks good, but still red integration tests. let me see

**Comment by JarnoNijboer** [comment]
Yeah, I broke tests while trying to fix them, will look into it.

**Comment by forki** [comment]
can you please merge master. that may fix couple of tests

**Comment by JarnoNijboer** [comment]
Integration tests are passing on local machine, except 1:
```
1) Error : Paket.IntegrationTests.NuGetV3Specs.#2700-1 v3 works properly
System.Exception : Paket failed with
-> Unable to retrieve package versions for 'Microsoft.CSharp'
```

**Comment by forki** [comment]
thank you!

**Pull request merged**
