### PR TITLE
Redirect order integration test

### PR DESCRIPTION
**Pull request by RustyF**
A retrospective integration test to show that commit https://github.com/fsprojects/Paket/pull/2230/commits/3d0d8c560d5f36fef0a634c519b2da9d582a6adb fixes issue #2228 

P.S. This is my first ever PR

### CODE REVIEW

**Comment by RustyF** [comment]
I might have screwed my PR - I only need to merge one commit on one branch

**Comment by matthid** [comment]
@RustyF You can change the target branch via Edit... select fix_dotnetcore (your stuff will be later in master but thats ok in this case)

**Comment by RustyF** [comment]
Ah, I see - many thanks - done

**Comment by matthid** [comment]
@RustyF thanks you for the test. There seems to be some small casing problem left. Let me know if you need any help.

**Comment by matthid** [comment]
Thank you!

**Comment by forki** [comment]
hey @RustyF welcome to paket ;-)

**Comment by RustyF** [comment]
Thanks @forki 👍

**Pull request merged**
