### PR TITLE
Adds binding redirect for applicable assemblies only

### LINKED ISSUE #809: Binding redirects - create entries only for applicable binaries for a project
Extracted from #806 

/cc @isaacabraham

### PR DESCRIPTION
**Pull request by mrinaldi**
Fixes #809.

/cc @isaacabraham

### CODE REVIEW

**Comment by forki** [comment]
I think there is an issue with using things like `/binding-redirect-adds-referenced-assemblies-only/before/Project1/Project1.fsproj`

when I run paket install for the main Paket project then this will get affected.

we should rename fsproj files in the before folder to fsprojtemplate and remove the suffix when we copy the files to temp.

**Comment by isaacabraham** [comment]
In terms of behaviour, am I correct in thinking that rather than inserting BRs from all dependencies, it now checks what dependencies there are for each project one by one, and generates specific BRs for each of them?

**Comment by forki** [comment]
Just to clarify: my comment was only referring to the integration tests. We
need to protect integration test data against run of paket update from the
root of the repo.

**Comment by mrinaldi** [comment]
oops :blush:

done in 142e28d

**Comment by mrinaldi** [comment]
@isaacabraham kind of. It doesn't generate BRs for each referenced dependency, but for required referenced dependency only.

That means it'll only generate BRs for dependencies that are referenced and have a higher version than the version required for another assembly.

For example:
`AutoFixture.Xunit 3.36.9` requires `xunit.extensions ≥ 1.8.0.1549 && < 2.0.0`, but references `xunit.extensions 1.8.0.1549`.

This PR will only generate BRs when needed. That means if a project has a dependency on `AutoFixture.Xunit 3.36.9` but depends on `xunit.extensions 1.9.2`, it'll generate BR for `xunit.extensions`.

However, if the project references `AutoFixture.Xunit 3.36.9` and `xunit.extensions 1.8.0.1549`, no BR will be generated.

**Comment by isaacabraham** [comment]
@mrinaldi so that's even better than what I was thinking - basically the minimal set of BRs that are required. LGTM.

**Comment by forki** [comment]
is there something we should write into the docs?

**Comment by dnauck** [comment]
What about transient dependencies that needs BRs?

E.g. Dependency 1 has transient dependency on Newtonsoft.Json 5.x and Dependency 2 has transient dependency on Newtonsoft.Json 6.x ?

Looks like your PR (just read the text here) will not generate a BR for Newtonsoft.Json in this case but this is required.

**Comment by mrinaldi** [comment]
@dnauck actually, it does.

Using this `paket.dependencies`
```
source https://www.nuget.org/api/v2/

nuget PushoverQ.Json
nuget Newtonsoft.Json.Schema
```

And this `paket.references`
```
PushoverQ.Json
Newtonsoft.Json.Schema
```

This is the resulting app.config:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<runtime><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="7.0.0.0" />
  </dependentAssembly>
  <dependentAssembly>
    <assemblyIdentity name="Microsoft.ServiceBus" publicKeyToken="31bf3856ad364e35" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="3.0.0.0" />
  </dependentAssembly>
</assemblyBinding></runtime></configuration>
```

**Comment by mrinaldi** [comment]
Added 7b3533e to make sure that even if `--createnewbindingfiles` is specified, the `app.config` is not created if no binding redirect is required.

**Comment by mrinaldi** [comment]
@forki We can improve the docs describing the new behavior, albeit the old behavior is not described.
In my opinion, however, the current docs are ok.

**Comment by forki** [comment]
cool! thanks so much!

**Pull request merged**
