### PR TITLE
handling for dotnet 9

### PR DESCRIPTION
**Pull request by smoothdeveloper**
steps towards #4237

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
@kerams, now the branch can install this:

```
source https://api.nuget.org/v3/index.json

storage: none
nuget microsoft.aspnetcore.cryptography.internal prerelease
```

Can you think of another paket.dependencies that you would like to check?

I'll try to see if the only failing test is related to this branch.

**Comment by smoothdeveloper** [comment]
@forki, pending review, this is potentially ready for next alpha release.

**Comment by kerams** [comment]
Thank you, this is all I ever wanted for Valentine's.

**Comment by forki** [comment]
very cool! thanks a lot!

**Comment by forki** [comment]
alpha is released

**Pull request merged**
