### PR TITLE
Fixes img src attribute

### PR DESCRIPTION
**Pull request by mariusschulz**
… so that the GROSSWEBER logo shows up correctly ;-)

### CODE REVIEW

**Comment by forki** [comment]
mhm it worked for me before the change. now it doesn't anymore

**Comment by forki** [comment]
image

**Comment by mariusschulz** [comment]
Ah, I looked at the file here on GitHub. Check out the relative paths.

**Comment by mariusschulz** [comment]
Here's the link: https://github.com/fsprojects/Paket/blob/master/docs/content/testimonials.md

**Comment by forki** [comment]
mhm. yes the file structure is different.

maybe we should change that instead. but I'll revert the commit for now in order to fix the link in the online docs

**Comment by mariusschulz** [comment]
Right, that makes sense. Sorry, only noted the missing image here.

**Pull request merged**
