### PR TITLE
Revert Netstandard to see if build works

### PR DESCRIPTION
**Pull request by forki**
*don't merge*

### CODE REVIEW

**Comment by forki** [comment]
@matthid I think I reverted to something that already built. I don't really understand that error. Is that a mono issue?

**Comment by matthid** [comment]
I would say nunit bug, because appveyor fails as well. Can you try to revert that update as well.

**Comment by forki** [comment]
Now it fails for different reasons. So looks like nunit is really broken

**Comment by matthid** [comment]
yep, looks like either paket bug or not updated unit tests to me...

**Pull request merged**
