### PR TITLE
Add support for MonoAndroid11.0 and MonoAndroid12.0

### LINKED ISSUE #4112: How to use Paket with MonoAndroid TargetFrameworkVersion v12.0?
### Description

I changed the TargetFrameworkVersion to 12.0 in my project but the package still generates the wrong condition:

```
<Choose>
    <When Condition="$(TargetFrameworkIdentifier) == 'MonoAndroid' And $(TargetFrameworkVersion) == 'v10.0'">
      <PropertyGroup>
        <__paket__Xamarin_Android_Support_VersionedParcelable_targets>monoandroid90\Xamarin.Android.Support.VersionedParcelable</__paket__Xamarin_Android_Support_VersionedParcelable_targets>
      </PropertyGroup>
    </When>
  </Choose>
```

### Repro steps

1. Create blank MonoAndroid app and add any dependency.

2. Set `TargetFrameworkVersion` to `v12.0`

3. Run `dotnet paket install`

### Expected behavior

```
<Choose>
    <When Condition="$(TargetFrameworkIdentifier) == 'MonoAndroid' And $(TargetFrameworkVersion) == 'v12.0'">
      <PropertyGroup>
        <__paket__Xamarin_Android_Support_VersionedParcelable_targets>monoandroid90\Xamarin.Android.Support.VersionedParcelable</__paket__Xamarin_Android_Support_VersionedParcelable_targets>
      </PropertyGroup>
    </When>
  </Choose>
```

### Actual behavior

```
<Choose>
    <When Condition="$(TargetFrameworkIdentifier) == 'MonoAndroid' And $(TargetFrameworkVersion) == 'v10.0'">
      <PropertyGroup>
        <__paket__Xamarin_Android_Support_VersionedParcelable_targets>monoandroid90\Xamarin.Android.Support.VersionedParcelable</__paket__Xamarin_Android_Support_VersionedParcelable_targets>
      </PropertyGroup>
    </When>
  </Choose>
```

### Known workarounds

None

### PR DESCRIPTION
**Pull request by Dolfik1**
Fix #4112

### CODE REVIEW

**Comment by Dolfik1** [comment]
Hmm. What's wrong with test?

**Comment by forki** [comment]
hey thanks for the contribution.

**Comment by forki** [comment]
I'll take care of it

**Comment by forki** [comment]
released inPaket.Core.7.0.0-alpha004

**Pull request merged**
