### PR TITLE
Symbols source

### PR DESCRIPTION
**Pull request by pms1969**
changed the way I thought about the problem.... now works much better, and the ```build.cmd nuget``` command should work as expected.

### CODE REVIEW

**Comment by pms1969** [comment]
is this ok?

**Comment by forki** [comment]
I had to resolve merge conflicts since @cloudRoutine send it some refactorings in that area.
please review https://github.com/fsprojects/Paket/commit/dc7ec4738202d41f5a1e636393a564b350a2718d 

thx

**Comment by pms1969** [comment]
doh, just spotted a problem with it (linked files).  I'll fix asap (might be early tomorrow) and get you another pull request.

**Comment by forki** [comment]
Cool thx

**Comment by harrisonmeister** [comment]
Can I ask why this has been done? I now have a bunch of internal nuget packages which have their dependencies added?

**Comment by forki** [comment]
Really? I thought it was under switch and only for symbol packages

**Comment by forki** [comment]
Could please elaborate a bit on the concrete issue?

**Comment by harrisonmeister** [comment]
By symbol packages, do you mean project references? That's what I'm seeing. When I run a paket hard install, I get the Dependency twice, e.g.:

ProjectB has a project reference to ProjectA. When I reference ProjectB in some other project, say ProjectC, I see the below - which seems odd that it would appear twice. (It might be that this is right)


	<Choose>
		<When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0' Or $(TargetFrameworkVersion) == 'v4.5')">
		  <ItemGroup>
			<Reference Include="ProjectA">
			  <HintPath>..\..\..\..\packages\ProjectA\lib\net40\ProjectA.dll</HintPath>
			  <Private>True</Private>
			  <Paket>True</Paket>
			</Reference>
		  </ItemGroup>
		</When>
	  </Choose>
	  <Choose>
		<When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0' Or $(TargetFrameworkVersion) == 'v4.5')">
		  <ItemGroup>
			<Reference Include="ProjectA">
			  <HintPath>..\..\..\..\packages\ProjectB\lib\net40\ProjectA.dll</HintPath>
			  <Private>True</Private>
			  <Paket>True</Paket>
			</Reference>
			<Reference Include="ProjectB">
			  <HintPath>..\..\..\..\packages\ProjectB\lib\net40\ProjectB.dll</HintPath>
			  <Private>True</Private>
			  <Paket>True</Paket>
			</Reference>
		  </ItemGroup>
		</When>
	  </Choose>

**Comment by forki** [comment]
ProjectA.dll shouldn't be in Project B nuget package. that is clearly a bug.

I think https://github.com/fsprojects/Paket/pull/1383/files#diff-74c1bcac29cb19f058c1e6032cc1ce19R161 needs to be filtered. we should not add that stuff when a paket.template file exists for that project

**Comment by forki** [comment]
could you please retry?

**Comment by forki** [comment]
with latest that is..

**Comment by harrisonmeister** [comment]
Hi, sure will let you know the results

**Comment by harrisonmeister** [comment]
Looks like thats fixed it, many thanks!

**Comment by pms1969** [comment]
good spot.  Sorry I missed that.

**Pull request merged**
