### PR TITLE
pdb's no longer being packaged in the non symbols package

### PR DESCRIPTION
**Pull request by pms1969**

### CODE REVIEW

**Comment by forki** [comment]
Why that change?

**Comment by pms1969** [comment]
https://github.com/fsprojects/Paket/issues/1394

basically, if the pdb's are in the non-symbols package, VS won't download the symbols package for debugging.

**Comment by pms1969** [comment]
as far as I can tell, the Travis build was already borking on that test.

**Comment by forki** [comment]
So now we put the pdbs in the normal package, but not into the symbols
package?

**Comment by pms1969** [comment]
Other way around.

**Comment by forki** [comment]
But not everyone is using symbols packages. What about the other case?

**Comment by pms1969** [comment]
depends if you want strict nuget replication in that area or not.  Nuget doesn't package them in the non-symbols regardless.

Should only require a small tweak to fix for when there is no symbols requested.  Depends on what you'd like to do?

**Comment by forki** [comment]
I think we should still put the pdbs in the normal package when we don't
create a symbols package. That's what nuget does, right?

**Comment by pms1969** [comment]
No it doesn't, tho i'll confirm that.

In the case that you want to add them, you can still add it as a file dependency and it won't be removed. (I've just confirmed that that is true of that build)

**Comment by pms1969** [comment]
Confirmed. Nuget does not include pdb's regardless of whether symbols have been requested or not.

**Comment by forki** [comment]
Ok. Let's remove them then. But how about a template file property that
automatically adds them? Should be a good alternative for people so they
don't have to use explicit file references

**Comment by pms1969** [comment]
not a bad idea?  so for project files only?
property: include-pdbs
default: false
??

**Comment by forki** [comment]
yes that would be awesome

**Comment by pms1969** [comment]
do you want that as part of this pull request or another?

**Comment by forki** [comment]
please add it to this one.

**Comment by pms1969** [comment]
done

**Comment by pms1969** [comment]
travis failing on the same tests.  It has an ignore on it, so not sure why it gets run.

**Pull request merged**
