### PR TITLE
[WIP] Initial implementation of support for private github repos

### PR DESCRIPTION
**Pull request by colinbull**
This tackles #1043. 

It is in work in progress as I haven't been able to test it as yet, but thought I'd send the P.R. so I could get some initial feedback as I know @mavnn had an interest.

### CODE REVIEW

**Comment by mavnn** [comment]
Awesome :) I'll try and take it for a spin later today

**Comment by forki** [comment]
did it work?

**Comment by mavnn** [comment]
Got jumped by something else and now I'm on holiday for a week. Sorry :(

It's on the todo list for the day I get back though.

**Comment by amazingant** [comment]
:heart_eyes: @colinbull is my new hero!

Gave the code a (very) quick look and added `github amazingant/FParsecScript-privatedev .gitignore amazingant_github` to a dependencies file (private version of [amazingant/FParsecScript][1]) to test with. Looks like `Utils.getFromUrl` is being passed `None` for its auth parameter [here][2] still though, so no magic for me just yet.

[1]: https://github.com/amazingant/FParsecScript
[2]: https://github.com/colinbull/Paket/blob/master/src/Paket.Core/RemoteDownload.fs#L17

**Comment by colinbull** [comment]
Doh, didn't see that there, good spot, I'll fix this up tonight.

**Comment by colinbull** [comment]
ping @amazingant give that a go. Again, I don't have a way to test this. but fixed up the bits you pointed out.

**Comment by amazingant** [comment]
@colinbull: I'll rebuild and give it a go when I get back from lunch. I have room for another private repo on my account right now; would it help you at all if I make one and add you as a contributor or whatever so you can test against it? I'd want to delete it or make it public after this gets merged, but I'm happy to lend some space. :)

**Comment by colinbull** [comment]
@amazingant Yes, that would be an awesome help! For a start it would mean I could actually test it rather than flying blind and letting others pick up the testing.

**Comment by amazingant** [comment]
@colinbull enjoy GitHub's name-generated obtuse-spork

Anyone else want to be a contributor on it for testing?

**Comment by amazingant** [comment]
I'm not sure if this would break anything else (cc/ @forki), but fd2e9f4fc36713ffd5729909a6697ca340c2e68b works for me if I change the [rawFileUrl][1] to sprintf against `https://raw.githubusercontent.com/%s/%s/%s/%s`

[1]: https://github.com/fsprojects/Paket/blob/fd2e9f4fc36713ffd5729909a6697ca340c2e68b/src/Paket.Core/RemoteDownload.fs#L59

**Comment by forki** [comment]
@amazingant sounds good.

**Comment by forki** [comment]
@colinbull let me know when you think we can merge this.

**Comment by colinbull** [comment]
@forki I think this is good to go now.

**Comment by forki** [comment]
woot

woot!

**Pull request merged**
