### PR TITLE
travis support .net core sdk

### PR DESCRIPTION
**Pull request by enricosada**
travis support .net core (`osx`, `linux`) sdk using `dotnet` key with language `csharp`

### CODE REVIEW

**Comment by enricosada** [comment]
added https://github.com/fsharp/FAKE/pull/1281#issuecomment-245340969 , fake helper are using wrong path for `dotnet`

**Comment by enricosada** [comment]
ok @forki this fix the build and use the already installed .net core sdk in travis (faster).

Paket should build in developer machine too (in my machine works), because now is using the already installed .net core sdk (.net core sdk is a prerequisite, it's useless to install it each time) and doesnt give you an error like you had locally last time because wrong paths.

i added the workaround for dotnet path here so paket work now
I think is the right thing to do in FAKE too, i'll try to send a pr to @matthid pr

**Comment by matthid** [comment]
@enricosada

> .net core sdk is a prerequisite, it's useless to install it each time

The same argument goes for any dependency. I often use fake/paket to install dependencies just to make builds more reproducable/stable across machines. In general I prefer local over global installs (almost always)...

**Comment by forki** [comment]
i it still installing the sdk if we don't have it? I liked that idea

**Comment by enricosada** [comment]
this repo can install .net core sdk with the fake script, np for me, but the fake script is bugged atm so this workaround the issue and make build green. Also for developers who have it already installed.

about global/local install ok, but that's a ci server, if they give us a supported way to do it i think we should use that (it's their bandwidth we are using) if possible. And the build matrix support `dotnet` key too.

**Comment by forki** [comment]
Thanks buddy

**Comment by enricosada** [comment]
@forki i added some comment about .net core sdk and FAKE in https://github.com/fsharp/FAKE/pull/1281#issuecomment-245530087

i like the idea of install deps too

**Pull request merged**
