### PR TITLE
Fixed an exception when trying to load an assembly that has already been loaded from a different location.

### PR DESCRIPTION
**Pull request by vik-borisov**
Previously, all assemblies were loaded into the current domain. If different Paket groups have the same assembly, when you try to load the assembly into the current domain the error occurs.
Now each group has its own domain, which the group loads assemblies into. Current domain uses only the value of property "AssemblyName" of  an assembly.

### CODE REVIEW

**Comment by vik-borisov** [comment]
May be will be fixed https://github.com/fsprojects/Paket/issues/1783

**Comment by forki** [comment]
can you please rebase this? thanks

**Comment by forki** [comment]
alos please take a look at #1784

**Comment by matthid** [comment]
I don't think we need this any longer as we are now using Mono.Cecil for this (and therefore don't actually load any assemblies anymore). That is also the reason for the merge conflicts. A test-case might clarify this.

**Comment by forki** [comment]
So let's close this. @vik-borisov please send new pr if something is still wrong. Thanks for your work. 

(it's awesome that 3 people cared enough to fix this bug)

**Comment by matthid** [comment]
Ironically I didn't even noticed there was a bug there. It's just that you cannot load assemblies like this in dotnetcore and I preferred the '#ifdef' free solution with mono cecil ;)

**Pull request closed without merging**
