### PR TITLE
Better WPF support

### PR DESCRIPTION
**Pull request by sergey-tihon**
Attempt to add support of [new Build Action (Resource & Page) specific to WPF projects](https://msdn.microsoft.com/library/aa970494%28v=vs.100%29.aspx?f=255&MSPPError=-2147217396) 
Related issue https://github.com/fsprojects/Paket/issues/1260

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@forki It seems that it works, at least in my cases.
Should I add integration tests on something else?

**Comment by forki** [comment]
That would be great. (otherwise I will probably  break it) 

There are many many integration tests that you can copy. Just look at bit around

**Comment by sergey-tihon** [comment]
This PR is ready for merge after review

**Comment by forki** [comment]
Awesome!

cat

**Pull request merged**
