### PR TITLE
Use a hashset

### PR DESCRIPTION
**Pull request by forki**
references #2844 

brings original why sample down to 1s

### CODE REVIEW

**Comment by forki** [comment]
so from 21s down to 1s - good team work @theimowski!

**Comment by theimowski** [comment]
LGTM, pity there are no tests to be sure there's no regression.
Can we name the nested rec function `paths'` to better distinguish from outer fun?

**Comment by forki** [comment]
@theimowski my question is: are we ver going back here? In my optimization we only add to the set and never reuse old sets.

**Comment by theimowski** [comment]
Hm crap you're right. Now it might skip some chains ...
E.g. when we have a diamond:
```
A
  B
B
  C
  D
C
  E
D
  E
E
```

Then it would output just `A->B->C->E` and skip `A->B->D->E`
So it changes behavior - but aside maybe such behavior is ok?

**Comment by forki** [comment]
so revert?

**Comment by theimowski** [comment]
That's up to you - behavior changed, but I'm not sure whether it's ok or not.
By that I mean the output shown when `--details` is specified might get very long for bigger trees

**Comment by forki** [comment]
@matthid  ?

**Comment by theimowski** [comment]
Do we know how does yarn handle such cases?

**Comment by forki** [comment]
Dunno. But I'm fine with revert. 3s is still usable.

**Comment by theimowski** [comment]
Ok then how about revert and create issue to cover the code with some tests and optionally then improve perf

**Pull request merged**
