### PR TITLE
[wip/discussion] add a mechanism to auto-update the baseline files

### PR DESCRIPTION
**Pull request by 0x53A**
How do you update the baseline files if a test fails? manually? or is there already another tool i missed?

If there isn't already a better way, and you don't mind, I would go through the rest of this file and adapt all remaining tests.

### CODE REVIEW

**Comment by 0x53A** [comment]
looks like master is broken - I updated the baselines in the second commit, but you need to decide if that is actually ok or if it represents a bug.

cc @forki 

-----------------

No idea why - the last build from master was green ...

image

----------------

**Comment by forki** [comment]
I like that. can you please write a bit about this in the readme?

**Comment by 0x53A** [comment]
Sure, will do that (prob. in the evening, after work) - do you have any idea why master seems to be broken?

**Comment by matthid** [comment]
While I see the pain point there (and I was hit time and time again). This is at the same time dangerous as well. Just my regular disclaimer. we'd need to make sure the flag is never set in master and that we carefully review those changes in the tests now (I'm not sure this is done atm). maybe a big disclaimer is enough. THIS FLAG IS NOT MEANT FOR YOU TO INTRODUCE LARGE CHANGES EASILY.

**Comment by 0x53A** [comment]
For me, it was to just be able to compare it - the test outputs two gigantic strings (actual vs expected), good luck seeing the difference. With this you can override the baselines then use git to compare it.

**Comment by forki** [comment]
Yes git compare is the trick that really works.

Am 24.04.2017 10:41 schrieb "Lukas Rieger" <notifications@github.com>:

**Comment by matthid** [comment]
My proposed solution would be to improve the test output to show the diff notation as well... But yeah I'm not saying I'm against it :). Like I said I know the pain :)

**Comment by matthid** [comment]
I just discussed this yesterday with @cloudRoutine as well on Slack

**Pull request merged**
