### PR TITLE
Fix for #3494

### LINKED ISSUE #3494: paket pack with multi-targeted project only creates first framework specified
### Description

using `paket pack` on a project with multiple TargetFrameworks creates a nupkg with only the first specified framework. ie. if the declaration is `<TargetFrameworks>netstandard2.0;net472</TargetFrameworks>`, then the nupkg has just the `netstandard2.0` contents.
If they're swapped round:
`<TargetFrameworks>net472;netstandard2.0</TargetFrameworks>`, then the nupkg has just the `net472` contents.

### Repro steps

Get this repo: <https://github.com/ozwaldDunlop/paket-multitarget-bug>

1. Run `.paket\paket.exe install`
2. Build in Debug mode
3. Run `.paket\paket.exe pack . --build-config Debug`
4. Open the resulting nupkg in 7zip or [Nuget Package Explorer](https://chocolatey.org/packages/NugetPackageExplorer)

### Expected behavior

You should see `netstandard2.0` and `net472` folders in the nupkg as you do when you run `dotnet pack`:
image

### Actual behavior

You only see one lib folder: image 

### Known workarounds

Use `dotnet pack` instead of `paket pack`

### PR DESCRIPTION
**Pull request by jam40jeff**
This fixes #3494 by adding support for multiple target frameworks to the pack command.

### CODE REVIEW

**Comment by jam40jeff** [comment]
Sorry, but I don't use git very often.  I tried to clean up the pull request with a rebase, but it looks like it just made more commits.  The diff still looks correct, however.  Feel free to instruct me to cleanup if necessary.

**Comment by jam40jeff** [comment]
This fixes issue #3494.

**Comment by jam40jeff** [comment]
This should be ready for review.  It looks like only the flaky tests are failing.

**Comment by forki** [comment]
can you please merge with master?

**Comment by jam40jeff** [comment]
@forki Done.

**Comment by forki** [comment]
cool. do we need to add something to the docs?

**Comment by jam40jeff** [comment]
I don't believe so.  Nothing public-facing changed and IMO it works as one would expect now when multi-targeting.

**Pull request merged**
