### PR TITLE
[Ready] Simplify and fix memoizeAsyncEx

### LINKED ISSUE #2639: Restore Failure on Mono: System.Exception: Expected an result at this place.
I've been skimming through the travis logs and found one error that looked ... interesting:

image

https://travis-ci.org/fsprojects/Paket/jobs/266475236#L1953

It comes from this line:

https://github.com/fsprojects/Paket/blob/ca538da8de310a32e2e11c03841d5292df80670d/src/Paket.Core/Common/Utils.fs#L62-L82

Just judging from the context, it seems like this should not happen and represents either a mono async issue, or an actual bug. But I haven't analyzed it in any way.

If you don't care about this, just close the issue ;-)

### PR DESCRIPTION
**Pull request by 0x53A**
fixes #2639 

lets see what CI says

### CODE REVIEW

**Comment by matthid** [comment]
See https://github.com/fsprojects/Paket/issues/2639#issuecomment-323611783

This throws away the first result and duplicates it on the usage-side (IE duplicates the first request).

**Comment by matthid** [comment]
There is most likely a better way to do what I'm trying to achieve but I haven't found/used the correct primitives...

**Comment by matthid** [comment]
Also feel free to change the signature, maybe there is another one to achieve the same :)

**Comment by 0x53A** [comment]
I made it more explicit what happens, while trying to keep the logic the same.

**Comment by 0x53A** [comment]
In my fork, AV is green:
image

Will rebase it all into one commit ...

**Comment by forki** [comment]
thanks!

**Pull request merged**
