### PR TITLE
Fix RestrictionsChanged Detection

### PR DESCRIPTION
**Pull request by lust4life**
see details: https://github.com/fsprojects/Paket/pull/2638#discussion_r243729652

```fsharp
// the requirement's setting
{ImportTargets = None;
    FrameworkRestrictions = AutoDetectFramework;
    OmitContent = None;
    IncludeVersionInPath = None;
    LicenseDownload = None;
    ReferenceCondition = None;
    CreateBindingRedirects = None;
    EmbedInteropTypes = None;
    CopyLocal = None;
    SpecificVersion = None;
    StorageConfig = Some NoPackagesFolder;
    Excludes = [];
    Aliases = map [];
    CopyContentToOutputDirectory = None;
    GenerateLoadScripts = None;}

// the resolved package 
// Install Settings
{ImportTargets = None;
    FrameworkRestrictions = ExplicitRestriction true;                                                                                                       
    OmitContent = None;                                                                                                                                     
    IncludeVersionInPath = None;
    LicenseDownload = None;                                                                                                                                 
    ReferenceCondition = None;                                                                                                                              
    CreateBindingRedirects = None;
    EmbedInteropTypes = None;                                                                                                                               
    CopyLocal = None;
    SpecificVersion = None;                                                                                                                                 
    StorageConfig = None;
    Excludes = [];                                                                                                                                          
    Aliases = map [];
    CopyContentToOutputDirectory = None;
    GenerateLoadScripts = None;};

//    GroupSettings =
{ImportTargets = None;
      FrameworkRestrictions =
       ExplicitRestriction
         || (== net461) (== netcoreapp2.0) (== netcoreapp2.2) (== netstandard2.0);
      OmitContent = None;
      IncludeVersionInPath = None;
      LicenseDownload = None;
      ReferenceCondition = None;
      CreateBindingRedirects = None;
      EmbedInteropTypes = None;
      CopyLocal = None;
      SpecificVersion = None;
      StorageConfig = Some NoPackagesFolder;
      Excludes = [];
      Aliases = map [];
      CopyContentToOutputDirectory = None;
      GenerateLoadScripts = None;};

// Settings =
{ImportTargets = None;
      FrameworkRestrictions =
       ExplicitRestriction
         || (== net461) (== netcoreapp2.0) (== netcoreapp2.2) (== netstandard2.0);
      OmitContent = None;
      IncludeVersionInPath = None;
      LicenseDownload = None;
      ReferenceCondition = None;
      CreateBindingRedirects = None;
      EmbedInteropTypes = None;
      CopyLocal = None;
      SpecificVersion = None;
      StorageConfig = Some NoPackagesFolder;
      Excludes = [];
      Aliases = map [];
      CopyContentToOutputDirectory = None;
      GenerateLoadScripts = None;};}

```

### CODE REVIEW

**Comment by lust4life** [comment]
@matthid  the impact here is : 
when we use config like below in `packet.dependencies`

```
storage: none
framework: auto-detect
```

run `dotnet build` , it will always shows a trace warning like 
```
  paket.dependencies and paket.lock are out of sync in E:\git\test\go.
  Please run 'paket install' or 'paket update' to recompute the paket.lock file.
  Changes were detected for Main/FSharp.Core
      - RestrictionsChanged
  Starting restore process.
```

although it will only occurs the first time after we generate a restore cache in `xx/obj/` folder, but when in ci case, it will always show a warning message, if we have many packages, it will generate warning message for every packages. and using `paket install` or `paket update` here doesn't help.

e.g.
- new project
- paket.dependencies
```
source https://api.nuget.org/v3/index.json
storage: none
framework: auto-detect
nuget FSharp.Core
```
- run `dotnet build`

**Comment by lust4life** [comment]
And if this is not a [FullResotre](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/Installation/RestoreProcess.fs#L578) , it will give this warning message always. 
`paket restore --project xxx.fsproj`

**Comment by lust4life** [comment]
@matthid test added.

**Comment by matthid** [comment]
Ok but the test didn't fail before the change, correct? I feel like a unit test might be easier to realize (assert that the settings are as they should be). The other way would be to assert that paket doesn't emit any warning?

**Comment by lust4life** [comment]
the test do fail before the change. since it will generate a warning message which should not be. not very familiar with paket's source code, could you tell me how to assert paket doesn't emit any warning, seems this warning message are publish to a event through [`traceWarn`](https://github.com/fsprojects/Paket/blob/add_gif/src/Paket.Core/Common/Logging.fs#L49)

**Comment by lust4life** [comment]
@matthid  ping

**Comment by matthid** [comment]
Afaik warnings don't make integration tests fail?

**Comment by lust4life** [comment]
Are you suggesting a unit test to cover this situation ？i think the difference here is how to generate a lock file : by real service (integration test) or by fake one (unit test). 

The problem here is not about whether the warning will cause the test to fail. It will generate inappropriate warnings.

and it give tips : `paket.dependencies and paket.lock are out of sync in %s.%sPlease run 'paket install' or 'paket update' to recompute the paket.lock file.`  re-run `paket install` will not solve this problem.

**Comment by matthid** [comment]
All I'm saying is that the test is "green" before and after the change even if it emits a warnings before and none after the change. Afaik there is nothing in place to "check" if the warning is there or not. Therefore there is no benefit in the test as it is now.

Yes my suggestion would be to either change the test in a way to check if the warning was emitted and fail the test or use a unit-test instead (which I'd argue is easier because then you can "test" that the "settings object" is correct instead of testing the output)

**Comment by lust4life** [comment]
@matthid  got you, fixed.

**Comment by lust4life** [comment]
@matthid  ping, I don't mean to rush you, can you do a release for this pr ? since this warning message will cause our ci pipeline failed (too many log message, travis will kill the build job). or is there anything I can help ? 🙂

**Comment by matthid** [comment]
Not sure if the failing test is related, doesn't look like it.

**Comment by lust4life** [comment]
@matthid  @forki  thx.

**Pull request merged**
