### PR TITLE
Cleanup PublicAPI

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by matthid** [comment]
I think this conflicts with https://github.com/fsprojects/Paket/pull/2638 on some lines

**Comment by forki** [comment]
haha so I are telling me to merge it asap so that I'm clear? ;)

**Comment by forki** [comment]
ok. I will keep it open until the other one is done.

**Comment by matthid** [comment]
For example ;).
No idea, tbh ideal timeslot for cleanup is after big changes started, but tbf that is never the case.

Nono please merge if ready I can live with the consequences :P

**Pull request merged**
