### PR TITLE
Change "update package" and install to not pin unchanged versions

### PR DESCRIPTION
**Pull request by forki**
this new version does not pin unchanged depedencies in the resolver phase.
Instead we introduce "preferred versions" and try these versions first.

/cc @mrinaldi @dnauck

### CODE REVIEW

**Comment by forki** [comment]
This allows us to "update package" in much more scenarios since we allow more possible resolutions. In order to keep the lock file as stable as possible we probe the old locked versions of unrelated packages first. 

@mrinaldi I also added your new test case which didn't work before.

**Comment by forki** [comment]
@dnauck I added you since I remember you reporting issues with updating transitive dependencies. This would work now since we don't pin the direct dependencies anymore

**Comment by mrinaldi** [comment]
Very cool, indeed.

There's one downside though.

This is how long it takes to do a selective update now:
`4 minutes, 48 seconds - ready.`

Comparing to the 2.9.0 version:
`43 seconds - ready.`

and to the 2.5.0 version:
`15 seconds - ready.`

Seems that this lag is due to fetching all versions for every package of the whole graph.
Version 2.9.0 would not fetch versions when the package is pinned (I've a lot of pinned packages)
Version 2.5.0 would fetch versions but only for the packages from the updating package graph.

So you know, my `paket.dependencies` has 102 packages and 51 of them are pinned.

**Comment by forki** [comment]
Yes I knew this would happen, and I already have plans to tackle perf.

At this point I just wanted to make sure it's "correct" and that I didn't
oversee something important.

**Comment by mrinaldi** [comment]
Looks correct to me :+1:

**Comment by forki** [comment]
@mrinaldi could you please test again. just be pretty fast now.

**Comment by forki** [comment]
it's in 2.10.0-alpha

**Comment by mrinaldi** [comment]
Much better now:
`41 seconds - ready.`

**Comment by forki** [comment]
Still much slower than expected. Is there a chance I can reproduce your
sample?

**Comment by mrinaldi** [comment]
The `NuGetV2.GetVersions` seems to be causing the problem.
Parallelizing the calls apparently floods the server.

Some calls are taking 2, 3x more time to complete comparing to the exactly same call when not parallelizing.
Using only `tryGetPackageVersionsViaOData` dropped the total time to `14 seconds - ready.`

I'm using ProGet 3.6.1, BTW.

**Comment by forki** [comment]
Mhm maybe we need a smart way to filter unsupported api calls.

**Comment by forki** [comment]
I mean I already tried but didn't really find a smart way

**Comment by mrinaldi** [comment]
The problem is not exactly unsupported calls, but the `tryGetAllVersionsFromNugetODataWithFilter` which is supported but takes around 2 seconds in ProGet.

For example, `FindPackagesById()?id='Microsoft.Bcl.Build'` takes `0:00:00.252` and `Packages?$filter=Id%20eq%20'Microsoft.Bcl.Build'` takes `0:00:02.243`.

**Comment by mrinaldi** [comment]
Of course, Async.Choice chooses the first call to return, but the `Packages?$filter=Id%20eq%20'Microsoft.Bcl.Build'` call definitely takes a significant amount of resources in ProGet, slowing down all other calls.

**Comment by forki** [comment]
Any ideas are appreciated.

**Comment by mrinaldi** [comment]
I'm working on it, will send a PR when I'm done.

**Pull request merged**
