### PR TITLE
Fix NRE in #1434

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by pms1969** [comment]
that bit of code was to ensure that referenced project were included as dependencies in the package, not as dll's, if, and only if the project had it's own template that happened to be a project template.

**Comment by pms1969** [comment]
was it barfing on core.Id.Value?

**Comment by forki** [comment]
But why was that recursive? And we do add nuget dependencies at another
place, right?

**Comment by pms1969** [comment]
was recursive because project a can reference project b which can reference project c.  project c has a paket.template, and you'd need that to be included as a package dependency

**Comment by forki** [comment]
Mhm I guess that makes some sense for this setting. Yes the package id is
null.

**Comment by pms1969** [comment]
The dependencies that are added elsewhere are only direct dependencies, they don't include dependencies for projects that become packages themselves

**Comment by forki** [comment]
how about 3b3a73d then?

**Comment by pms1969** [comment]
looks good

**Comment by forki** [comment]
I don understand "~~referenced-project" - where is that handled?

**Comment by pms1969** [comment]
yeah, I was unsure that was the right thing to do with that, but I kind of hit the limits of my F#.

It's handled right at the bottom of that file.

**Comment by forki** [comment]
what do you think about  5783de4?

**Comment by forki** [comment]
ah never mind. I think I now understand what you want to do.

**Comment by forki** [comment]
Like  f46872a ?

**Pull request merged**
