### PR TITLE
install mvvmlightlibs first time with wpav8.1 framework in lock file

### PR DESCRIPTION
**Pull request by sergey-tihon**
This test work on my machine and produce lock file with `wpav8.1`
image

### CODE REVIEW

**Comment by sergey-tihon** [comment]
Seems that on travis paket create lock file with `wpav8.1` - https://travis-ci.org/fsprojects/Paket/builds/119346651#L2424
@forki You should be able to reproduce it on you machine as well

**Comment by sergey-tihon** [comment]
image

**Comment by forki** [comment]
ok I get the same error as https://travis-ci.org/fsprojects/Paket/builds/119373387

    Expected string length 18715 but was 18660. Strings differ at index 2594.
    Expected: "...argetFrameworkIdentifier) == 'WindowsPhoneApp') Or ($(Targ..."
    But was:  "...argetFrameworkIdentifier) == '.NETCore') Or ($(TargetFrame..."

but it's an error in the csproj - not in the lock file!?

**Comment by forki** [comment]
OK now I can reproduce. I needed to change it to " File.ReadAllText newLockFilePath" instead of LockFile.Load and ToString

**Comment by sergey-tihon** [comment]
I think that issue with project files is another one.

>I needed to change it to " File.ReadAllText newLockFilePath" instead of LockFile.Load and ToString
Why resource can be different?

**Comment by forki** [comment]
ok new version was released

**Pull request merged**
