### PR TITLE
Fix failing test case.

### PR DESCRIPTION
**Pull request by matthid**
Small check if this makes travis happy again.

### CODE REVIEW

**Comment by matthid** [comment]
Success. Seems like a linux-bug slipped through somehow. Lets wait if I broke Appveyor ;)

**Comment by forki** [comment]
Thanks. Awesome

**Comment by matthid** [comment]
Did you release the wrong version? I thought this problem was only in v3...

**Comment by forki** [comment]
Yeah seems like it. But apart from zero-diff version and wrong release notes nothing bad happened.

**Pull request merged**
