### PR TITLE
Prevent paket holding locks on assemblies during binding redirects

### PR DESCRIPTION
**Pull request by haraldsteinlechner**
solves issue https://github.com/fsprojects/Paket/issues/1477

### CODE REVIEW

**Comment by forki** [comment]
@haraldsteinlechner @isaacabraham is this good to go?

**Comment by forki** [comment]
What do we need from the assembly? We have a assembly meta data reader here in paket that doesn't load the assembly at all.

**Comment by haraldsteinlechner** [comment]
imo my commit would be good to go. 
The only problem i could imagine is performance.
I'd recommend to merge the commit now, but leave the issue open and look for another option instead of loading the assembly.

**Comment by isaacabraham** [comment]
@forki it was to get assembly version and the signed key (if it exists). We never had the metadata reader at the time of the BR code so if that can also get these attributes maybe it would be better to replace this PR with one that uses that instead?

In the interim this code looks like it should be fine (although I haven't tested it myself) - it's just an alternative way of loading data on the assembly. The fact that it has to load the entire assembly into memory first could have some implications in terms of memory though?

**Comment by forki** [comment]
mhm merging this broke couple of releated integration tests. not sure why the build was green.

**Comment by haraldsteinlechner** [comment]
hmmm. crazy. also for my build all worked fine. checking again

**Comment by forki** [comment]
It's 4 integration tests. And if I revert your commit they are working
again.

**Comment by haraldsteinlechner** [comment]
my initial commit was green because it only ran on travis i suppose

**Comment by haraldsteinlechner** [comment]
ok. i failed in finding a good, fast and robust solution to this problem.
1) Loading assemblies in the default AppDomain always locks the file.
2) We could use a fresh appdomain for loading and unloading those assemblies. However, using appdomains to do this is not straightforward (especially since passing data around requires serialization etc)
3) We could use mono.ceceil for loading assembly metadata, but i suppose this is problematic as well (additional dependency)-

I don't know why there is a difference between mono and .net but one thing i know for sure: assembly binding semantcis is subtle and danger zone.

So, fixing our windows build (and appveyor CI), is not that simple. Revert and look for another solution not involving assembly loading (which is also SLOOW)?

**Comment by isaacabraham** [comment]
Also AppDomains are dead in CoreCLR world.

**Comment by forki** [comment]
Ok I will try to use the meta data reader that came from the F# compiler
itself. We already use it for pack.

**Comment by isaacabraham** [comment]
Sounds good. If we can rationalise this stuff to use a single mechanism that's a win.

**Comment by forki** [comment]
Ok tried a different workaround in c57e735 - can please test with latest?

**Comment by haraldsteinlechner** [comment]
i also found a different workaround: https://github.com/haraldsteinlechner/Paket/commit/777a4157023352b8ff37c18cfbd87bbd1305c675

the main problem was the caching of loaded libs

**Comment by forki** [comment]
cool please send as PR

**Comment by haraldsteinlechner** [comment]
i updated my fix https://github.com/haraldsteinlechner/Paket/commit/ce21a161030f3c8dc84654973d5ebfeab483e90f 

However, i did not send a pull request yet since i think your version is more robust when considering same assemblies with different versions etc. (my version builds on computing a key for assembly paths, yours uses more .net assembling binding resoution magic)

**Comment by haraldsteinlechner** [comment]
i finally went with my solution, since i had some weired test errors (laziness in seq). i hope we can close down this boring thing.... (see my new PR, waiting for CI)

**Pull request merged**
