### PR TITLE
use .net core sdk rtm (2.0.3)

### PR DESCRIPTION
**Pull request by enricosada**
Use .net core sdk rtm (2.0.3), instead of preview version (2.1.x)

This add a workaround, because SourceLink are included as `PackageReference`

as a note, will speedup things a bit in ci and in dev, because `2.0.3` is already installed in appveyor/travis

### CODE REVIEW

**Comment by forki** [comment]
Please take a look at #2855

**Comment by enricosada** [comment]
@forki seens that. but my issue was not just disable sourcelink (already done in the other PR), but to fix it with sdk 2.0.3

Ihmo this PR is ok.

The build fails (ref [appveyor log#L4769](https://ci.appveyor.com/project/matthid/paket-a815y/build/0.0.1.637#L4769) ) because of a test, but is unrelated ihmo

```
-> PathTooLongException: Path too long: C:\projects\paket-a815y\integrationtests\scenarios\i002294-pin-netstandard-1-6\temp\packages\runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl\runtime.opensuse.42.1-x64.runtime.native.system.security.cryptography.openssl.4.3.2.nupkg
-> PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
```

**Comment by enricosada** [comment]
green, done for me

**Comment by matthid** [comment]
Thanks for taking care of the test. We have renamed tests in the past so that is indeed what we would have done (issue number is usually enough info anyway).

Regarding the "integrationtests" folder I think we wouldn't even mind changing the structure to get rid of the directory completely. It is just work and headache nobody has gone into (as we have several hard-coded places in the test-suite).
So feel free to do it in a separate PR ;)

**Comment by forki** [comment]
Awesome!!!!!

**Pull request merged**
