### PR TITLE
bugfix/issue #3763 partially extracted nugets

### PR DESCRIPTION
**Pull request by viktor-svub**
fixing partial nuget extraction #3763 by extending fixes for borked and leaky zips to catch more cases

### CODE REVIEW

**Comment by forki** [comment]
This is released in v6 alpha channel. Can you please test it out and then I'll push it to v5 as well. Thanks for your help!

**Comment by viktor-svub** [comment]
Verified 6.0.0-alpha009 with previously failing dependencies -- the expected yellow warning "Trying to extract files individually" shows up, and the packages are fully extracted and work correctly in dotnet restore/build/run. Thank you!

**Comment by viktor-svub** [comment]
It seems version `5.241.3` has some new merge/build issue -- `paket install` ends with:
```
Paket failed with
-> Resource stream 'Paket.Restore.targets' could not be found in the Paket.Core assembly
```
It happens on all install attempts, regardless of `.paket\Paket.Restore.targets` presence, and the file indeed does not re/appear with this version when not present. 

It does _not_ happen when 6.0.0-alpha009 is used for install, regardless if fresh or using 5.241.3 bootstrapper with version in paket.dependencies to use the alpha.

**Comment by forki** [comment]
Damn. Unlisted that one.

Can you please try .4? If that also broken then I need to unlisted and
check that tomorrow.


Viktor Svub <notifications@github.com> schrieb am So., 22. Dez. 2019, 13:02:

**Comment by forki** [comment]
Ok never mind. It's still broken. Seems I need to dig deeper tomorrow.

**Comment by forki** [comment]
ok released 5.241.5 and that one seems to work. I had to install VS 2019 because it used a wrong compiler version. ffs

**Comment by viktor-svub** [comment]
thank you! 5.241.5 works perfectly :)

**Pull request merged**
