### PR TITLE
build extension with separate fsharp core version

### PR DESCRIPTION
**Pull request by smoothdeveloper**
This makes the extension work out of box in VS.

Also added some paths to scan paket.exe after suggestions in #3950

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
@forki this is green, for review.

**Comment by forki** [comment]
awesome. thanks
next step would be to use fsharp.core 5 everywhere

**Comment by smoothdeveloper** [comment]
somehow the release is still compiled against fsharp.core 4.7.0.0, not sure how it is happening.

image

**Comment by forki** [comment]
Could you please try to update FSharp.Core everywhere?

Gauthier Segay <notifications@github.com> schrieb am Fr., 4. Dez. 2020,
19:38:

**Pull request merged**
