### PR TITLE
Fix issue 3381 - generate load script

### PR DESCRIPTION
**Pull request by andre-correia**
https://github.com/fsprojects/Paket/issues/3381

### CODE REVIEW

**Comment by forki** [comment]
what's the status?

**Comment by andre-correia** [comment]
The integration test scenario that I've created is passing now but there are a few other tests that are now failing. I am checking why.

**Comment by andre-correia** [comment]
@forki I noticed that some of the tests have the attribute `Flaky` so I guess those are normal to fail under certain conditions like a different MSBuild version for example, right?

**Comment by andre-correia** [comment]
@forki I've checked all the tests and none of them seems to be due to my changes. Can you please confirm?

**Comment by matthid** [comment]
@andre-correia Please feel free to fix them if you know how ;)

**Comment by matthid** [comment]
But yeah all PRs are red but AppVeyor is green in master?

**Comment by enricosada** [comment]
I checked, so

## travis

the same travis tests were already red on master ( https://travis-ci.org/fsprojects/Paket/jobs/435977159 )

## appveyor

appeveyor tests fails is unrelated i think ( ref https://ci.appveyor.com/project/paket/paket/builds/19485318/job/hs86ojf27cyw1a6n/tests )

image

I'll try rerun the same, maybe is flacky and will go green

**Comment by andre-correia** [comment]
Thanks guys!

**Pull request merged**
