### PR TITLE
Reproduce stackoverflow from #1432

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
Ok the fix in 98faf34 is really worrying me.

So this suggest we do something strange and confuse Set.remove. I looked at the implementation and it's using CompareTo and no Equals.

During the debugging of the integration test I saw a set with 3 elements where we wanted to remove one element (which was also the first in the set). CompareTo was only called twice and not with the first element of the list (at least the debugger didn't step in there).

/cc @dsyme @mexx

**Comment by forki** [comment]
Ok d6e4503 seems to be the correct fix. Some how we had a case where we made a > b and b > a
This confused Set.remove since it is relying on proper CompareTo.

**Comment by mexx** [comment]
@forki `Set` requires the contained type to be ordered, as far as I can see from a quick look on the implementation. Is the underlying object type ordered?

**Comment by forki** [comment]
@mexx yes I fucked up the order as written above.

**Comment by forki** [comment]
And was so close: https://github.com/fsprojects/Paket/issues/1392#issuecomment-171967067

**Pull request merged**
