### PR TITLE
implement alternative fallback download of paket when github is failing

### PR DESCRIPTION
**Pull request by Stift**
With the ongoing outage/difficult connectivity of github we need a solution to run our builds. The current situation is that the most builds only contain the paket.bootstrapper.exe. When this fails downloading from github, like it happened the last days from time to time the build stops.
Therefore I introduced a fallback that downloads the nuget.exe and make a `nuget install paket` to extract the paket.exe and copy it to the desired target location.

### CODE REVIEW

**Comment by forki** [comment]
Wow. that sounds like a good idea

**Comment by forki** [comment]
I assume this will also fix the issue with broken builds on Travis when we hit the github API limit

**Comment by forki** [comment]
Thanks for helping to do this:

truck

**Comment by Stift** [comment]
No problem. It saves my life as well.
When we switch to .NET 4.5 in the future we can directly download and unzip it without using nuget.exe.

**Comment by forki** [comment]
Oh. If you are interested you can try to do this. I plan to merge #732 soon, so upgrading the bootstrapper would be ok.

**Comment by Stift** [comment]
Ok. I make it a separate branch.

**Comment by Stift** [comment]
Have it ready. To what branch should the pr go? I saw that you have the `zip` branch for that.

**Comment by forki** [comment]
please send it to master

**Pull request merged**
