### PR TITLE
Fix localization tests

### PR DESCRIPTION
**Pull request by JohanLarsson**

### CODE REVIEW

**Comment by forki** [comment]
still getting "Could not find 'paket.dependencies'. To use Paket with this solution, please run 'paket init' first."

**Comment by JohanLarsson** [comment]
Ok, adding it, not sure it was ever there.

**Comment by forki** [comment]
now it complains about missing lock files. keep pushing things ;-)

**Comment by JohanLarsson** [comment]
No fun for the planet when I waste cycles like this. Adding lock files.

**Comment by JohanLarsson** [comment]
Green now.

**Comment by forki** [comment]
thanks!

**Pull request merged**
