### PR TITLE
Fixed v3 api dependency resolution.

### PR DESCRIPTION
**Pull request by xavierzwirtz**
Fixes most of #1212

### CODE REVIEW

**Comment by xavierzwirtz** [comment]
Latest changes fix all of #1212

**Comment by forki** [comment]
I'm getting an error:

    Paket version 2.24.7.0
    found: C:\Users\Steffen\AppData\Local\NCrunch\3308\5\integrationtests\scenarios\i001211-top-level-v3\temp\paket.dependencies
    Parsing C:\Users\Steffen\AppData\Local\NCrunch\3308\5\integrationtests\scenarios\i001211-top-level-v3\temp\paket.dependencies
    Resolving packages for group Main:
      0 packages in resolution. 13 requirements left
      Trying to resolve NLog 3.2.1 (from C:\Users\Steffen\AppData\Local\NCrunch\3308\5\integrationtests\scenarios\i001211-top-level-v3\temp\paket.dependencies)
     - NLog is pinned to 3.2.1
      1 packages in resolution. 12 requirements left
      Trying to resolve NLog.FSharp 3.2.1 (from C:\Users\Steffen\AppData\Local\NCrunch\3308\5\integrationtests\scenarios\i001211-top-level-v3\temp\paket.dependencies)
     - NLog.FSharp is pinned to 3.2.1
      2 packages in resolution. 11 requirements left
      Trying to resolve FsLexYacc >= 6.1.0 (from C:\Users\Steffen\AppData\Local\NCrunch\3308\5\integrationtests\scenarios\i001211-top-level-v3\temp\paket.dependencies)
      - fetching versions for FsLexYacc
     - FsLexYacc 6.1.0
    Source 'http://api.nuget.org/v3/index.json' exception: System.Exception: Error file for FsLexYacc exists at C:\Users\Steffen\AppData\Local\NuGet\Cache\FsLexYacc.6.1.0.s1689900308.json.failed
       bei Paket.NuGetV3.GetPackageDetails@229-10.Invoke(Exception _arg3) in D:\code\paket\src\Paket.Core\NuGetV3.fs:Zeile 245.
       bei Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
    System.Exception : Paket failed with:
    	Couldn't get package details for package FsLexYacc 6.1.0 on http://api.nuget.org/v3/index.json.
    StackTrace:
         bei Paket.NuGetV2.GetPackageDetails@607-14.Invoke(String message) in D:\code\paket\src\Paket.Core\NuGetV2.fs:Zeile 607.
       bei Paket.NuGetV2.GetPackageDetails(String root, Boolean force, FSharpList`1 sources, PackageName packageName, SemVerInfo version) in D:\code\paket\src\Paket.Core\NuGetV2.fs:Zeile 607.
       bei Paket.UpdateProcess.lockFile@174-6.Invoke(FSharpList`1 sources, PackageName packageName, SemVerInfo version) in D:\code\paket\src\Paket.Core\UpdateProcess.fs:Zeile 174.
       bei Paket.PackageResolver.getExploredPackage$cont@232[a](UpdateMode updateMode, a sources, FSharpList`1 globalFrameworkRestrictions, FSharpFunc`2 getPackageDetailsF, IDictionary`2 rootSettings, Dictionary`2 exploredPackages, SemVerInfo version, PackageRequirement dependency, Unit unitVar) in D:\code\paket\src\Paket.Core\PackageResolver.fs:Zeile 241.
       bei Paket.PackageResolver.getExploredPackage@220[a](UpdateMode updateMode, a sources, FSharpList`1 globalFrameworkRestrictions, FSharpFunc`2 getPackageDetailsF, IDictionary`2 rootSettings, Dictionary`2 exploredPackages, PackageRequirement dependency, SemVerInfo version) in D:\code\paket\src\Paket.Core\PackageResolver.fs:Zeile 232.
       bei Paket.PackageResolver.tryToImprove@404[a](UpdateMode updateMode, FSharpOption`1 strategy, a sources, GroupName groupName, FSharpList`1 globalFrameworkRestrictions, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, FSharpRef`1 lastConflictReported, FSharpOption`1 packageFilter, IDictionary`2 rootSettings, Dictionary`2 exploredPackages, Dictionary`2 conflictHistory, HashSet`1 knownConflicts, FSharpSet`1 openRequirements, FSharpMap`2 filteredVersions, FSharpMap`2 currentResolution, FSharpSet`1 closedRequirements, PackageRequirement currentRequirement, Resolution conflictStatus, FSharpRef`1 compatibleVersions, FSharpRef`1 globalOverride, Boolean useUnlisted) in D:\code\paket\src\Paket.Core\PackageResolver.fs:Zeile 428.
       bei Paket.PackageResolver.step@262[a](UpdateMode updateMode, FSharpOption`1 strategy, a sources, GroupName groupName, FSharpList`1 globalFrameworkRestrictions, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, FSharpRef`1 lastConflictReported, FSharpOption`1 packageFilter, IDictionary`2 rootSettings, Dictionary`2 exploredPackages, Dictionary`2 conflictHistory, HashSet`1 knownConflicts, FSharpMap`2 filteredVersions, FSharpMap`2 currentResolution, FSharpSet`1 closedRequirements, FSharpSet`1 openRequirements) in D:\code\paket\src\Paket.Core\PackageResolver.fs:Zeile 447.
       bei Paket.PackageResolver.tryToImprove@404[a](UpdateMode updateMode, FSharpOption`1 strategy, a sources, GroupName groupName, FSharpList`1 globalFrameworkRestrictions, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, FSharpRef`1 lastConflictReported, FSharpOption`1 packageFilter, IDictionary`2 rootSettings, Dictionary`2 exploredPackages, Dictionary`2 conflictHistory, HashSet`1 knownConflicts, FSharpSet`1 openRequirements, FSharpMap`2 filteredVersions, FSharpMap`2 currentResolution, FSharpSet`1 closedRequirements, PackageRequirement currentRequirement, Resolution conflictStatus, FSharpRef`1 compatibleVersions, FSharpRef`1 globalOverride, Boolean useUnlisted) in D:\code\paket\src\Paket.Core\PackageResolver.fs:Zeile 436.
       bei Paket.PackageResolver.step@262[a](UpdateMode updateMode, FSharpOption`1 strategy, a sources, GroupName groupName, FSharpList`1 globalFrameworkRestrictions, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, FSharpRef`1 lastConflictReported, FSharpOption`1 packageFilter, IDictionary`2 rootSettings, Dictionary`2 exploredPackages, Dictionary`2 conflictHistory, HashSet`1 knownConflicts, FSharpMap`2 filteredVersions, FSharpMap`2 currentResolution, FSharpSet`1 closedRequirements, FSharpSet`1 openRequirements) in D:\code\paket\src\Paket.Core\PackageResolver.fs:Zeile 447.
       bei Paket.PackageResolver.tryToImprove@404[a](UpdateMode updateMode, FSharpOption`1 strategy, a sources, GroupName groupName, FSharpList`1 globalFrameworkRestrictions, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, FSharpRef`1 lastConflictReported, FSharpOption`1 packageFilter, IDictionary`2 rootSettings, Dictionary`2 exploredPackages, Dictionary`2 conflictHistory, HashSet`1 knownConflicts, FSharpSet`1 openRequirements, FSharpMap`2 filteredVersions, FSharpMap`2 currentResolution, FSharpSet`1 closedRequirements, PackageRequirement currentRequirement, Resolution conflictStatus, FSharpRef`1 compatibleVersions, FSharpRef`1 globalOverride, Boolean useUnlisted) in D:\code\paket\src\Paket.Core\PackageResolver.fs:Zeile 436.
       bei Paket.PackageResolver.step@262[a](UpdateMode updateMode, FSharpOption`1 strategy, a sources, GroupName groupName, FSharpList`1 globalFrameworkRestrictions, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, FSharpRef`1 lastConflictReported, FSharpOption`1 packageFilter, IDictionary`2 rootSettings, Dictionary`2 exploredPackages, Dictionary`2 conflictHistory, HashSet`1 knownConflicts, FSharpMap`2 filteredVersions, FSharpMap`2 currentResolution, FSharpSet`1 closedRequirements, FSharpSet`1 openRequirements) in D:\code\paket\src\Paket.Core\PackageResolver.fs:Zeile 447.
       bei Paket.PackageResolver.Resolve[a](GroupName groupName, a sources, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, FSharpOption`1 strategy, FSharpList`1 globalFrameworkRestrictions, FSharpSet`1 rootDependencies, UpdateMode updateMode) in D:\code\paket\src\Paket.Core\PackageResolver.fs:Zeile 218.
       bei <StartupCode$Paket-Core>.$DependenciesFile.resolveGroup@473-1.Invoke(GroupName groupName, b _arg1) in D:\code\paket\src\Paket.Core\DependenciesFile.fs:Zeile 495.
       bei Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
       bei Microsoft.FSharp.Collections.FSharpMap`2.Map[b](FSharpFunc`2 f)
       bei Paket.UpdateProcess.selectiveUpdate(Boolean force, FSharpFunc`2 getSha1, FSharpFunc`2 getSortedVersionsF, FSharpFunc`2 getPackageDetailsF, LockFile lockFile, DependenciesFile dependenciesFile, UpdateMode updateMode, SemVerUpdateMode semVerUpdateMode) in D:\code\paket\src\Paket.Core\UpdateProcess.fs:Zeile 138.
       bei Paket.UpdateProcess.SelectiveUpdate(DependenciesFile dependenciesFile, UpdateMode updateMode, SemVerUpdateMode semVerUpdateMode, Boolean force) in D:\code\paket\src\Paket.Core\UpdateProcess.fs:Zeile 169.
       bei Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions options) in D:\code\paket\src\Paket.Core\UpdateProcess.fs:Zeile 184.
       bei <StartupCode$Paket-Core>.$PublicAPI.Update@184.Invoke(Unit unitVar0) in D:\code\paket\src\Paket.Core\PublicAPI.fs:Zeile 184.
       bei Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action) in D:\code\paket\src\Paket.Core\Utils.fs:Zeile 367.
       bei Paket.Program.handler@342-15.Invoke(ParseResults`1 results) in D:\code\paket\src\Paket\Program.fs:Zeile 342.
       bei Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args) in D:\code\paket\src\Paket\Program.fs:Zeile 55.
       bei Paket.Program.processCommand@61-1.Invoke(Command command, String[] args) in D:\code\paket\src\Paket\Program.fs:Zeile 61.
       bei Paket.Program.main() in D:\code\paket\src\Paket\Program.fs:Zeile 329.
       bei Microsoft.FSharp.Core.Operators.FailWith[T](String message)
       bei Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in D:\code\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:Zeile 33.
       bei Paket.IntegrationTests.TestHelpers.update(String scenario) in D:\code\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:Zeile 37.
       bei Paket.IntegrationTests.NuGetV3Specs.#1211 update with V3 API should work exactly like V2 API() in D:\code\Paket\integrationtests\Paket.IntegrationTests\NuGetV3Specs.fs:Zeile 16.

**Comment by forki** [comment]
I updated my other PR

**Comment by xavierzwirtz** [comment]
It looks like because of the way the error file is written, it will always overwrite the error file with an error that says
```
Source 'http://api.nuget.org/v3/index.json' exception: System.Exception: Error file for FsLexYacc exists at C:\Users\Steffen\AppData\Local\NuGet\Cache\FsLexYacc.6.1.0.s1689900308.json.failed
   bei Paket.NuGetV3.GetPackageDetails@229-10.Invoke(Exception _arg3) in D:\code\paket\src\Paket.Core\NuGetV3.fs:Zeile 245.
   bei Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
```

It will even do this in the NuGet `v2` api. I think the logic should be changed to add a automatic bypass of the cache in that case, with a message logged to the console.

**Comment by forki** [comment]
can you try to implement that? would help me a lot.

**Comment by xavierzwirtz** [comment]
Can do.

**Pull request merged**
