### PR TITLE
filter .targets / .props earlier

### PR DESCRIPTION
**Pull request by 0x53A**
This works around https://github.com/fsprojects/Paket/issues/2283, see my last two comments there

### CODE REVIEW

**Comment by forki** [comment]
it's marked WIP?

**Comment by 0x53A** [comment]
yeah, because i didn't run the tests locally, and wanted to get a second opinion whether that is actually the correct way. If you say it looks good, then let's merge it. =)

cc @matthid

**Comment by forki** [comment]
It's called getTartgetFiles but also retrieves props?

**Comment by 0x53A** [comment]
The naming is, in general, a bit inconsistent. In the Model there is a single list of files, which is only split later on between .targets and .props. A better name would be something like ImportFiles or BuildFiles, but that is for a later day to refactor.

**Comment by forki** [comment]
thanks! Looking forward to that  PR then ;-)

**Comment by matthid** [comment]
I will look over it on the evening. But if forki wants to release I'm fine with that. It's unlikely worse than what we have (I mean now that we are slowly understanding what we do) ;)

**Comment by 0x53A** [comment]
The next weekend is supposed to be rainy ...

**Comment by matthid** [comment]
Yep that PR is fine :)

**Pull request merged**
