### PR TITLE
align with spec requirements, meaning no leading zeroes on semVers

### PR DESCRIPTION
**Pull request by baronfel**
per the spec:

>A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and **MUST NOT** contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

Emphasis mine

### CODE REVIEW

**Comment by baronfel** [comment]
Actually found this when I was integrating this module into FAKE, thanks to the tests over there.

**Comment by cdrnet** [comment]
Note that `0` starts with `0` as well, and `0.1.0` is a perfectly valid version number.

**Comment by forki** [comment]
We also need to support 0 itself since it is used in “=> 0" all over the
place

Am 08.05.2017 8:28 vorm. schrieb "Christoph Ruegg" <notifications@github.com

**Comment by forki** [comment]
ping

**Comment by baronfel** [comment]
Sorry this has taken so long, I'm in vacation without a computer but can
take a look on Saturday.

**Comment by baronfel** [comment]
ok this is looking fixed up now.  I'm super curious what it would take to move us over to [SemVer.net](https://github.com/xyncro/semver.net) instead of a home grown parse, and it looks like we mostly have a 
1) semi-convention around the 'name' of the prerelease segment being the first alpha segment,
1) various tostring functions that normalize for nuget (which may not be necessary anymore if the 3.4+ documentation is correct in that they strip leading zeroes, and trailing 4th segment zeroes)

**Comment by forki** [comment]
@baronfel the issue is always to support old released nupkg that don't conform to semver

**Comment by forki** [comment]
we recently made paket more conform to semver. So hope it's better now.

**Pull request closed without merging**
