### PR TITLE
#2716 Duplicates appear in generated scripts.

### LINKED ISSUE #2716: Duplicates appear in generated scripts.
### Description

Duplicate `#r` lines appear in generated script files. Is this necessary? Can it cause problems?

### Repro steps

Use the Entity Framework nuget package as a test case.

### Expected behavior

I would expect to see the following in the generated script file:

```
#r "System.ComponentModel.DataAnnotations" 
#r "../../../packages/EntityFramework/lib/net45/EntityFramework.dll" 
#r "../../../packages/EntityFramework/lib/net45/EntityFramework.SqlServer.dll" 
```
### Actual behavior

Paket generates a file as follows:

```
#r "System.ComponentModel.DataAnnotations" 
#r "System.ComponentModel.DataAnnotations" 
#r "../../../packages/EntityFramework/lib/net45/EntityFramework.dll" 
#r "../../../packages/EntityFramework/lib/net45/EntityFramework.SqlServer.dll" 
```
### Known workarounds

Create your own references file.

### PR DESCRIPTION
**Pull request by t-krag**
Resolves #2716

### CODE REVIEW

**Comment by forki** [comment]
Can you please take a look at appveyor? Thanks

**Comment by lexarchik** [comment]
This tests fail fixed in #2768

**Comment by forki** [comment]
Ok thanks!

Am 15.09.2017 10:23 vorm. schrieb "lexarchik" <notifications@github.com>:

**Comment by t-krag** [comment]
Do you want a new PR for this? I'm not totally on top of how things works with appveyor automation. If so, you can just close this one and I'll make a new.

**Pull request merged**
