### PR TITLE
Fixed NugetV2 querying #2472

### PR DESCRIPTION
**Pull request by bhugot**
Should Fix for #2472

### CODE REVIEW

**Comment by matthid** [comment]
Oh really? So this url was wrong all this time? Or are there some NuGet servers behaving differently?

**Comment by matthid** [comment]
/cc @forki might know something out of his memories?

I need some time to look at all of this and go through the specs :/. And my todo list is always full.

**Comment by forki** [comment]
against which feed is that?

**Comment by bhugot** [comment]
The url was working on nuget.org v2 and v3 but was not on nexus or artifactory. With () it s seems to be working on all

**Comment by forki** [comment]
@maartenba do you know something about this? and would it work with myget?

**Comment by bhugot** [comment]
@forki just tried on a myget repo and it's working too

https://dotnet.myget.org/F/dotnet-corert/api/v2/Packages?$filter=(tolower(Id)%20eq%20%27system.xml.xdocument%27)%20and%20(Version%20eq%20%274.3%27)

https://dotnet.myget.org/F/dotnet-corert/api/v2/Packages()?$filter=(tolower(Id)%20eq%20%27system.xml.xdocument%27)%20and%20(Version%20eq%20%274.3%27)

**Comment by matthid** [comment]
anyone knows which one is correct according to the spec?

**Comment by matthid** [comment]
Maybe there even is a difference between them?

**Comment by bhugot** [comment]
There is no diff if you look at the data I think it's just an implementation of odata

In code we already use

```fsharp
let url = sprintf "%s/Packages(Id='%O',Version='%O')" nugetURL packageName version
```
And i think some odata implementation accept a call without () but it's the same than with .

**Comment by Reelix** [comment]
Based off the error log, it's trying to pull:

http://myserver.com/nuget/private/Packages?$filter=(tolower(Id)%20eq%20%27company.packageName%27)%20and%20(NormalizedVersion%20eq%20%271.1.423.393%27)

**Comment by bhugot** [comment]
try with ()

**Comment by maartenba** [comment]
OData specific imo, ping the respective support alias for the servers that are throwing :-)

**Comment by forki** [comment]
thanks. I released it in 5.5 alpha channel. Let's see how it goes.

**Comment by forki** [comment]
I knew this one would bite us. https://github.com/fsprojects/Paket/issues/2504 sigh

**Pull request merged**
