### PR TITLE
WIP: Initial Integration tests

### PR DESCRIPTION
**Pull request by forki**
I'm starting to build integration tests

### CODE REVIEW

**Comment by mrinaldi** [comment]
excited

**Comment by forki** [comment]
It's not pretty, but it's a start

**Comment by forki** [comment]
seems i001166-resolve-nancy-fast doesn't run after latest resolver changes.
seems to run fine before

**Comment by forki** [comment]
@mrinaldi could you please take a look at i001166-resolve-nancy-fast - it seems to resolve with paket 2.18 but not with your changes

**Comment by forki** [comment]
I think I found it.

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/commit/8f7109205e272b586855b5c035b97118622b8907 seems to fix it.

**Comment by mrinaldi** [comment]
Cool. The tests are showing their worth already.

**Pull request merged**
