### PR TITLE
Fake references missing for IntegrationTests

### PR DESCRIPTION
**Pull request by dcorriveau-omniscient**
Not sure if I'm doing something wrong but I didn't have FAKE references and so I couldn't compile the project.

### CODE REVIEW

**Comment by forki** [comment]
What do you mean with "fake references"?

**Comment by forki** [comment]
Ah I understand. But please take the existing fake from the build group. No changes in dependencies or lock file needed. Only in the paket.references

**Comment by dcorriveau-omniscient** [comment]
FakeLib doesn't work for the IntegrationTests project (exclamation mark next to the reference and I can't compile).
Edit: Alright, I'll try the paket.references only

**Comment by dcorriveau-omniscient** [comment]
Alright, it should work with the Build group now.

**Comment by forki** [comment]
Lgtm. Thx

**Pull request merged**
