### PR TITLE
Allow Pack to pin only project references (Pull Request)

### PR DESCRIPTION
**Pull request by jam40jeff**
See #1648.

### CODE REVIEW

**Comment by tsibelman** [comment]
Hi @jam40jeff It will be very helfull for as if you could finish this feature.

**Comment by jam40jeff** [comment]
I have completed this feature and am using it in my own custom build of Paket.  However, I was unable to get the pull request approved.  Adding another voice of support to this issue can't hurt though.  I still believe it is a very valuable option and would like to see it included in Paket so I don't have to keep synchronizing my custom build with each release.

**Comment by tsibelman** [comment]
Why this pull request was not aproved ? I do not see anything here, did you got some feedback by some other chanell ?

**Comment by jam40jeff** [comment]
The discussion on #1648 is the reasoning for the pull request not being approved.  I implemented the simple switch which allows you to use exact versioning for project reference dependencies rather than minimum versioning.  The rest of that discussion was about how to make it so other schemes could be used, but I still think that would just complicate things without adding much benefit.

The two options (exact with this switch, minimum without it) are the only two I have needed.  I use minimum when I am guaranteeing backwards compatibility between projects within a solution and exact when I am not.

**Comment by tsibelman** [comment]
I read the disscusion but fail to see anyone objecting to this change, @forki can you tell us if you see somee problem with this ?

**Comment by forki** [comment]
can you please rebase this. Then I will review. Thx

**Comment by forki** [comment]
thanks!

**Comment by tsibelman** [comment]
Thank you guys, you made my day.

**Pull request merged**
