### PR TITLE
Fix fast restore

### PR DESCRIPTION
**Pull request by matthid**
This has regressed countless times:
- (recently) https://github.com/fsprojects/Paket/pull/3598
- https://github.com/fsprojects/Paket/pull/3013
- https://github.com/fsprojects/Paket/pull/3200
- https://github.com/fsprojects/Paket/pull/3201
- https://github.com/fsprojects/Paket/pull/3206

The last regression was due to the change of the caching file to only contain hashes. This is tricky to fix in msbuild, but there is https://docs.microsoft.com/en-us/visualstudio/msbuild/getfilehash-task?view=vs-2019 which seems to produce the exact same hash we already generate in C# (when using SHA256 in hex format).
I guess this also replaces https://github.com/fsprojects/Paket/pull/2870, lets see if this actually works for everyone, if not we are doomed ;)

Therefore we:
- [x] Add (failing) integration test for #2684.
- [x] Fix the issue at hand

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
Seems to be working for me! 

Only issue I seemed to have is having an older FAKE version causes `paket.restore.cached` to be in a old format and give this new Targets file errors.  Might need to recommend people update their FAKE version if they hit this error

```
.paket/Paket.Restore.targets(101,13): error MSB4184: The expression ""System.String[]".GetValue(1)" cannot be evaluated. Index was outside the bounds of the array.
```

**Comment by matthid** [comment]
I think we should fix that, if we cannot read the cache file we should probably call restore and consider it outdated

**Comment by matthid** [comment]
Seems the testsuite agrees ;)

**Comment by forki** [comment]
is this ready?

**Comment by matthid** [comment]
Should be ready if it turns green. I addressed the failing tests and the issue @TheAngryByrd pointed out (including a test for this scenario as none existed)

Notice that this also fixes https://github.com/fsharp/FAKE/issues/2348 which apparently is a feature now in the SAFE-Stack. Instead of adding an integration test into FAKE, I think it should be enough that we now have one here, time will tell.

**Comment by matthid** [comment]
I accidentally pushed into `origin` and then deleted the branch, therefore we now have 4 instead of 2 CI builds and two are red because they can't find the branch :)

**Comment by forki** [comment]
@matthid you always find novel ways to confuse me ;-)

**Comment by matthid** [comment]
That's why I added a comment ;).
`push origin` is just to much muscle memory ;)

**Comment by forki** [comment]
You could point origin to your fork and name the common fork upstream

Matthias Dittrich <notifications@github.com> schrieb am Di., 2. Juli 2019,
19:47:

**Comment by baronfel** [comment]
That's what I do, too terrified I'll flub things up by happenstance

**Comment by matthid** [comment]
Had to fix another test anyway, so back to normal ;)

**Pull request merged**
