### PR TITLE
Local file - npkg in path version

### PR DESCRIPTION
**Pull request by theimowski**
TODO:
- [x] docs

References #1803

### CODE REVIEW

**Comment by theimowski** [comment]
I think it's ready for merge

**Comment by gertjvr** [comment]
Is #1838 trying to achieve the same thing?

**Comment by gertjvr** [comment]
Eager to try this out, thanks again for implementing this

**Comment by theimowski** [comment]
Lol haven't seen #1838 before and yeah i guess it serves the same purpose

**Comment by theimowski** [comment]
@forki weren't there any merge conflicts? I saw you merged #1838 before this one

**Comment by forki** [comment]
I merged with --sours to get @creib into history but applied your PR

**Comment by theimowski** [comment]
:+1:

**Pull request merged**
