### PR TITLE
Make sure we don't forget empty results

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
for nuget and myget we should break earlier if we get Emptyesult. we don't need to check all fallbacks here

**Comment by matthid** [comment]
Ideally we trust empty results when we got real results from a particular url before...

**Comment by forki** [comment]
Yes. That is next step. We should definitely trust myget and nuget

Am 15.08.2017 13:52 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by matthid** [comment]
We should do https://github.com/fsprojects/Paket/pull/2582 for GetDetails as well instead of adding special cases again :/

**Comment by forki** [comment]
Yes definitely.

Am 15.08.2017 13:54 schrieb "Matthias Dittrich" <notifications@github.com>:

**Pull request merged**
