### PR TITLE
[WIP] .net core paket

### PR DESCRIPTION
**Pull request by enricosada**
have a `paket` targeting .net core app 2.0

ref https://github.com/fsprojects/Paket/issues/2875

target just `netstandard2.0` for `Paket.Core` (is ok @matthid ?), instead
of `netstandard1.6`

- add tests of .net standard paket.core
- fix build script

TODO:

- [x] unit tests
- [ ] remove temporary packagerefence
    - [ ] fix fscheck deps
- [x] sourcelink
- [x] integration tests (with paket published as .net core fdd)
- [ ] cleanup (squash related, etc)
- [x] ~fix the nuspec (is not right, there is a fallback group)~
    - [x] no, really, fix it. same bug with dependencies on netstandard1.6

### CODE REVIEW

**Comment by matthid** [comment]
> target just netstandard2.0 for Paket.Core (is ok @matthid ?), instead

Yes FAKE is already on netcoreapp2.0 so upgrading Paket is OK for me. Thanks for taking care of this.

**Comment by enricosada** [comment]
nice, now time to rebase

**Comment by enricosada** [comment]
the nuspec is wrong

```xml
    <dependencies>
      <group>
        <dependency id="Chessie" version="0.6.0"></dependency>
        <dependency id="FSharp.Compiler.Tools" version="0.0"></dependency>
        <dependency id="FSharp.Core" version="0.0"></dependency>
        <dependency id="Mono.Cecil" version="0.10.0-beta6"></dependency>
        <dependency id="Newtonsoft.Json" version="0.0"></dependency>
      </group>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Mono.Cecil" version="0.10.0-beta6" exclude="Build,Analyzers"></dependency>
        <dependency id="Chessie" version="0.6.0" exclude="Build,Analyzers"></dependency>
        <dependency id="System.Security.Cryptography.ProtectedData" version="4.4.0" exclude="Build,Analyzers"></dependency>
        <dependency id="Newtonsoft.Json" version="10.0.3" exclude="Build,Analyzers"></dependency>
      </group>
    </dependencies>
```

the first one is the fallbackgroup, and is wrong. should be a `.NETFramework` identitifer
that's logged somewhere as bug @forki @matthid ?

**Comment by matthid** [comment]
Yes here: https://github.com/fsprojects/Paket/issues/2792

**Comment by enricosada** [comment]
Ty @matthid , added my 👍 so is going to be resolved faster 😄 

joking aside, it;s just an issue if a `netstandard1.6` ( or `netstandard2.1` ) reference `Paket.Core`, so atm is really minor

**Comment by enricosada** [comment]
only @forki appveyor seems to be fast enough, sigh.

**Comment by enricosada** [comment]
@forki @matthid  what should i do about CI?

now the build will take a bit longer (that's because we run "integration tests" for both .net and .net core version).

I'll split the build in two matrix job. 
   - A: everything like now, minus .net core integration tests
   - B: full netcore, will run .net core integration tests
pretty much like now as time used, twice as much worker used each commit

but maybe leaving just @forki fast worker enabled, matth/cloudroutine disabled. no code changes and 1h build, can be a way too

About travis, IF OK, i'll open a PR to disable failing test and open an issue about know failure. And cleanup the matrix, to add mono 4.8, 5.2, 5.4 (osx/unix). travis job are pretty much free, because always run in parallel, osx a bit more queued ro tun , but matrix is nice like https://travis-ci.org/fsharp/FsAutoComplete

**Comment by matthid** [comment]
Maybe only testing netcore and getting travis green again is another option...

**Comment by enricosada** [comment]
@matthid @forki i prepared a repo ( https://github.com/enricosada/paket-netcore-testing
 ) with the current WIP of this PR, if you have time for some feedback

this add both .net core, and pratically something really similar to repo level tool, because is tons easier to implement. i'll split that for the other PR.

bootstrapping is a bit tricky, but the idea is that boostrapper is:

- or .net cli global tools (dotnetcli v2.2 or v2.3), so .net core ready, zero files
- or current mono/.net exe boostrapper (no changes for users, commit usual boostrapper)
- or a native binary (no deps, bigger download?)
- or push boostrapper in native package managers (brew etc). this can be done using paket itself as boostrapper so paket is a repo level tool. like a machine wide paket (but repo will the specified version of paket)

**Comment by enricosada** [comment]
meanwhile fixed on linux/mac (thx to @TheAngryByrd 👍 ).
now should work ok.

**Comment by matthid** [comment]
I think the only thing we need to verify here is that `paket push` works (there is no automatic test for this as of today)

**Comment by enricosada** [comment]
Closing.

- .net core already merged
- new fully .net core install flow is wip in https://github.com/fsprojects/Paket/pull/3183

**Pull request closed without merging**
