### PR TITLE
Don't try and push other peoples nupkg files

### PR DESCRIPTION
**Pull request by mavnn**

### CODE REVIEW

**Comment by mavnn** [comment]
Just realised that this build.fsx relies on the version that hasn't been published yet. Might be worth repointing at the bin directory instead

**Comment by forki** [comment]
I'm already trying to solve the hen and egg problem ;-)

**Comment by forki** [comment]
ok it now pushed only paket.core. It seems to miss paket.nupkg

**Comment by mavnn** [comment]
That's very odd. Did it create paket.nupkg?

**Comment by forki** [comment]
nope.

**Comment by forki** [comment]
wait a minute. could still be related to hen and egg

**Comment by mavnn** [comment]
No, we've changed template file detection. It now only looks for templates from projects.

**Comment by mavnn** [comment]
I've commented on the commit that changed it, I misunderstood the new logic originally.

**Comment by forki** [comment]
ok it's "fixed", but I need to cleanup my mess

**Pull request merged**
