### PR TITLE
Adding support for SpecificVersion attribute on assembly references

### PR DESCRIPTION
**Pull request by batzen**
This PR adds support for `SpecificVersion` on assembly references.
This was requested in #2040.

- [X] Implement feature
- [X] Fix unit and integration tests (partially done, see below)
- [X] Add new tests to verify feature

I'm currently having a hard time trying to find out which integration tests i broke with my change as they often ~~fail because either the path is too long (exceeds 260 characters for file or 248 for directory)  (solved by moving to c:\paket) or they~~ fail with 

>  Expected: "...argetFrameworkVersion) == 'v4.6.1' Or $(TargetFrameworkVer..."
  But was:  "...argetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersi..."

The tests failing with this error are:
- #1427 install content
- #1427 install content once from dependencies file
- #1427 install content once from dependencies file removes paket tag
- #1427 install content once from dependencies file stays stable
- #1427 install content once from dependencies file stays stable 2 installs
- #1427 install content once from references file
- #1427 won't install content when content:none

The following tests timeout:
- #1174 Should find Ninject error

I don't think those fails are caused by my changes, but i can't be sure...

Please tell me if i did anything wrong as this is the first time i am in contact with F#.

### CODE REVIEW

**Comment by matthid** [comment]
can you rebase/merge? Currently master is green so it might solve the spurious issues you encountered (there was a problem with the integration test suite which was solved)...

**Comment by matthid** [comment]
Nevermind you were faster :)

**Comment by forki** [comment]
Is this flag enabled by default?

**Comment by batzen** [comment]
The default is `True` which is the same as omitting it in assembly references.

**Comment by forki** [comment]
We should not emit it then in default case to reduce impact in csproj

**Comment by batzen** [comment]
I thought that i should add it to csproj as private is also added by default.
If you don't want it to be added i will remove it if it's not specified or equals true.

**Comment by matthid** [comment]
@forki If we get this into paket 5 I guess it's OKisch, because it will already rewrite a lot because of new restriction system, netcore and xamarin support...

**Comment by forki** [comment]
Okish yes, but still lets keep it small if possible.

Am 11.06.2017 4:13 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by batzen** [comment]
So which way should i go?
Omit it if it's not specified (`None`) or also omit it if it's specified with the default value of `True`?

**Comment by forki** [comment]
Omit only if not explicitly specified. That's what we always do.

Am 11.06.2017 4:18 nachm. schrieb "Bastian Schmidt" <
notifications@github.com>:

**Comment by batzen** [comment]
Ok.
Will make the changes accordingly and revert most changes to tests.

**Comment by batzen** [comment]
Should be as expected now + tests are present now too.

**Comment by forki** [comment]
💋

**Comment by forki** [comment]
Urgs I forgot to ask for docs and already released it in rc006. Can you please send a PR to the docs as well?

I think it needs to go to https://github.com/fsprojects/Paket/blob/master/docs/content/nuget-dependencies.md#copy_local-settings and https://github.com/fsprojects/Paket/blob/master/docs/content/references-files.md#copy_local-settings

**Comment by batzen** [comment]
Of course. Didn't know about that. Will get it done till friday.

**Pull request merged**
