### PR TITLE
show stack trace in verbose mode (closes #2480)

### LINKED ISSUE #2480: Too verbose output if writing in cache fails
### Description

When a user updates a package and some program blocks the the access to a file an error message is thrown in the output:
````
Source 'https://mynugetserver/api/odata' exception: System.IO.IOException: The process cannot access the file 'C:\Users\user\AppData\Local\Nuget\Cache\Snappy.NET.1.1.1.8.s314620838_v5.1.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at Paket.NuGetCache.get@175-3.Invoke(ODataSearchResult _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@825-1.Invoke(a a)
Something failed in GetPackageDetails, trying again with force: Couldn't get package details for package Snappy.NET 1.1.1.8 on https://mynugetserver/api/odata.

````

### Repro steps

Cannot come up with a genuine repro.

### Expected behavior

only show the call stack when in verbose mode, but not in normal mode.

### Actual behavior

Too verbose output.

### Known workarounds

Not a blocking issue.

### PR DESCRIPTION
**Pull request by Stift**
minimize the output in normal mode when getPackageDetails have a problem.
See #2480 for more info.

### CODE REVIEW

**Comment by matthid** [comment]
Oh I was too slow: https://github.com/fsprojects/Paket/issues/2480#issuecomment-312815393
Please only handle the one particular instance of the error.

**Comment by matthid** [comment]
The reasoning is that I want to move away from all the general "with e ->" clauses thoughout the code base. but that is a painful process (so I kind of provoke people to open issues by printing stacktraces on errors, this was imho better than if I forgot something and introduced breaking changes)

**Comment by Stift** [comment]
I'll understand. 
Updated it and limiting to IOException. Unfortunately a bunch of inherited classes are also now catched the same way (PathTooLong, etc.). Is this okay?

**Comment by matthid** [comment]
@Stift in a perfect world i'd like to only catch the access denied error, but I can see the difficulties here. So I'm fine with it. Maybe we can add a code comment to clarify why it was added (to make it easier for future contributors to handle the sub-types differently). A link to your issue is probably just fine.

**Comment by Stift** [comment]
I know, that perfect world I also dream of. I just wanted to prevent filtering on message strings and the exception does not give more details.

**Comment by matthid** [comment]
Yes I agree, filtering of the string is error prone. Thanks for looking into this.

**Comment by forki** [comment]
thanks!

**Pull request merged**
