### PR TITLE
extended semver2 support in paket.template files

### PR DESCRIPTION
**Pull request by viktor-svub**
Attempt at supporting half-open dependency constraints with minimum from current or locked version, but open to semver-declared compatibility. 

Example of intended usage would be `My.Package ~> LOCKED:Minor >= LOCKEDVERSION`. 

- Numeric syntax is "number of segments used", negative counts non-zero segments from end. 
- Unit-testing is done by extending existing scenarios via TestCase, further may be added. 
- Combining with group-binding syntax is expected and supported, like: 

>`LOCKED-NetCore:Patch` -or- `LOCKED:Patch-NetCore`
>`LOCKED-NetCore:[3]` -or- `LOCKED:[3]-NetCore`
>`LOCKED-NetCore:[-1]` -or- `LOCKED:[-1]-NetCore`

As side effect, `paket.template` dependencies can now support inline and full-line comments.
Locked-version dependencies without group bind are assumed to be "Main" and print warnings when resolved from different group.

### CODE REVIEW

**Comment by forki** [comment]
do we need to update docs?

**Comment by viktor-svub** [comment]
I can add docs change, if there are no expected changes in the proposed syntax

**Comment by forki** [comment]
Yes please

Viktor Svub <notifications@github.com> schrieb am Do., 24. Mai 2018, 18:19:

**Comment by viktor-svub** [comment]
Docs updated, feel free to do any fixups - English not being my first language results in some creative contraptions at times :)

**Pull request merged**
