### PR TITLE
Boostrapper download without nuget exe and switch bootstrapper to .net 4.5

### PR DESCRIPTION
**Pull request by Stift**
The previous approach for the nuget fallback for the bootstrapper used the nuget.exe to accomplish it tasks.
I changed the fallback behaviour for the bootstrapper with the following new features
- change project version to .Net 4.5 (to unzip via Framework)
- do not use nuget.exe anymore
- download package directly via nuget API
- use evaluated parameters for prerelease or specified version

### CODE REVIEW

**Comment by forki** [comment]
very cool.
could you please add a --prefer-nuget switch, which changes the order?
I'm sure @vasily-kirichenko would like it, since sometime github download is slow.

**Comment by Stift** [comment]
Very nice idea. Will do that.

**Comment by Stift** [comment]
Ok. I introduced now the parameter `--prefer-nuget` which prefers nuget over github. 
Default behaviour: github (fallback: nuget)
`--prefer-nuget` behaviour: nuget (fallback: github)

I hope this pleases all the needs.
igbe3a8tavn0q

**Comment by Stift** [comment]
Just found a bug in version parsing from nuget. Will provide a fix in a minute

**Comment by Stift** [comment]
There was an issue with the SemVer stuff. Should be fixed by now

**Comment by forki** [comment]
cool thanks. I just have to wait a bit until we have the other .NET 4.5 stuff ready.

**Comment by Stift** [comment]
Ok. I'll wait until then with other improvements, I'll have in my pipeline.

**Comment by forki** [comment]
Thanks. It's now part of 0.39 alpha.

**Comment by Stift** [comment]
Very nice. You are welcome.

**Pull request merged**
