### PR TITLE
WIP Fix (maybe) for #2156

### PR DESCRIPTION
**Pull request by smoothdeveloper**
exclude framework assemblies when generating scripts for netcore/netstandard

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
This is not ready

**Comment by smoothdeveloper** [comment]
Before:

`main.group.csx`

```
#r "System.Xml.Linq" 
#r "System.Xml" 
#r "mscorlib" 
#r "System.Core" 
#r "System" 
#r "System.Runtime.Serialization" 
#r "System.ComponentModel.Composition" 
#r "Microsoft.CSharp" 
#r "../../packages/Microsoft.CSharp/lib/netstandard1.3/Microsoft.CSharp.dll" 
#r "../../packages/Newtonsoft.Json/lib/netstandard1.0/Newtonsoft.Json.dll" 
#r "../../packages/System.Dynamic.Runtime/lib/netstandard1.3/System.Dynamic.Runtime.dll" 
#r "../../packages/System.IO.FileSystem.Primitives/lib/netstandard1.3/System.IO.FileSystem.Primitives.dll" 
#r "../../packages/System.Linq/lib/netstandard1.6/System.Linq.dll" 
#r "../../packages/System.Linq.Expressions/lib/netstandard1.6/System.Linq.Expressions.dll" 
#r "../../packages/System.ObjectModel/lib/netstandard1.3/System.ObjectModel.dll" 
#r "../../packages/System.Reflection.Emit/lib/netstandard1.3/System.Reflection.Emit.dll" 
#r "../../packages/System.Reflection.Emit.ILGeneration/lib/netstandard1.3/System.Reflection.Emit.ILGeneration.dll" 
#r "../../packages/System.Reflection.Emit.Lightweight/lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll" 
#r "../../packages/System.Reflection.TypeExtensions/lib/netstandard1.5/System.Reflection.TypeExtensions.dll" 
#r "../../packages/System.Runtime.Handles/ref/netstandard1.3/System.Runtime.Handles.dll" 
#r "../../packages/System.Runtime.Serialization.Primitives/lib/netstandard1.3/System.Runtime.Serialization.Primitives.dll" 
#r "../../packages/System.Text.RegularExpressions/lib/netstandard1.6/System.Text.RegularExpressions.dll" 
#r "../../packages/System.Threading/lib/netstandard1.3/System.Threading.dll" 
#r "../../packages/System.Threading.Tasks.Extensions/lib/netstandard1.0/System.Threading.Tasks.Extensions.dll" 
#r "../../packages/System.Xml.ReaderWriter/lib/netstandard1.3/System.Xml.ReaderWriter.dll" 
#r "../../packages/System.Xml.XDocument/lib/netstandard1.3/System.Xml.XDocument.dll" 
#r "../../packages/System.IO.FileSystem/ref/netstandard1.3/System.IO.FileSystem.dll" 
```
after:
```
#r "../../packages/Microsoft.CSharp/lib/netstandard1.3/Microsoft.CSharp.dll" 
#r "../../packages/Newtonsoft.Json/lib/netstandard1.0/Newtonsoft.Json.dll" 
#r "../../packages/System.Dynamic.Runtime/lib/netstandard1.3/System.Dynamic.Runtime.dll" 
#r "../../packages/System.IO.FileSystem.Primitives/lib/netstandard1.3/System.IO.FileSystem.Primitives.dll" 
#r "../../packages/System.Linq/lib/netstandard1.6/System.Linq.dll" 
#r "../../packages/System.Linq.Expressions/lib/netstandard1.6/System.Linq.Expressions.dll" 
#r "../../packages/System.ObjectModel/lib/netstandard1.3/System.ObjectModel.dll" 
#r "../../packages/System.Reflection.Emit/lib/netstandard1.3/System.Reflection.Emit.dll" 
#r "../../packages/System.Reflection.Emit.ILGeneration/lib/netstandard1.3/System.Reflection.Emit.ILGeneration.dll" 
#r "../../packages/System.Reflection.Emit.Lightweight/lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll" 
#r "../../packages/System.Reflection.TypeExtensions/lib/netstandard1.5/System.Reflection.TypeExtensions.dll" 
#r "../../packages/System.Runtime.Handles/ref/netstandard1.3/System.Runtime.Handles.dll" 
#r "../../packages/System.Runtime.Serialization.Primitives/lib/netstandard1.3/System.Runtime.Serialization.Primitives.dll" 
#r "../../packages/System.Text.RegularExpressions/lib/netstandard1.6/System.Text.RegularExpressions.dll" 
#r "../../packages/System.Threading/lib/netstandard1.3/System.Threading.dll" 
#r "../../packages/System.Threading.Tasks.Extensions/lib/netstandard1.0/System.Threading.Tasks.Extensions.dll" 
#r "../../packages/System.Xml.ReaderWriter/lib/netstandard1.3/System.Xml.ReaderWriter.dll" 
#r "../../packages/System.Xml.XDocument/lib/netstandard1.3/System.Xml.XDocument.dll" 
#r "../../packages/System.IO.FileSystem/ref/netstandard1.3/System.IO.FileSystem.dll" 
```

**Comment by forki** [comment]
Ready?

**Comment by smoothdeveloper** [comment]
@forki if the result is what is expected (or at least an improvement, we can look further) yes.

**Comment by filipw** [comment]
Did it miss `System.IO`? seems like that package should be there as well

**Comment by filipw** [comment]
or `System.Runtime.Extensions`?

**Comment by filipw** [comment]
it seems it's skipping dlls from `ref` if no corresponding dll in `lib` was found.
I believe this shouldn't be like that because for scripting you want to have reference assemblies when you can since you will be passing them to the compiler https://docs.microsoft.com/en-us/nuget/create-packages/project-json-and-uwp#directory-structure

**Comment by smoothdeveloper** [comment]
I'll look where they are supposed to happen, but before or after this PR they aren't there apparently although I see them stated as dependency in `Newtonsoft.Json.nuspec`.

**Comment by smoothdeveloper** [comment]
@forki by chance do you know which place in `InstallModel` might have the missing stuff?

**Comment by forki** [comment]
ref and lib's need to be referenced differently. The netcore fsi will get a #r-ref command to support this. I assume C# will need to do the same.

What are you missing in the model?

**Comment by smoothdeveloper** [comment]
@forki I'm not sure I'm missing anything, or rather I'm missing everything as I'm confused about the whole issue.

@filipw's comments imply we should handle those ref (currently they are not surfaced in script generation, which uses InstallModel) as `#r` references.

**Comment by forki** [comment]
AFAIK `ref` files are needed at design time, not at runtime.

**Comment by matthid** [comment]
Scripting is Compile & Runtime at the same time :)

**Pull request merged**
