### PR TITLE
Bugs/3074 bad request

### PR DESCRIPTION
**Pull request by haf**
My editor also trimmed trailing whitespace. I hope that's fine, or I'll separate it.

### CODE REVIEW

**Comment by matthid** [comment]
Yes trimming whitespace is usually fine. However, can you mark the actual change. I reviewed it briefly and cannot find the actual change oO. Maybe I'm blind.

**Comment by haf** [comment]
https://github.com/fsprojects/Paket/pull/3078/files#diff-c472e5dab436e319906fd5150ed22a62R516

**Comment by matthid** [comment]
So the problem was that the message was not good enough?

**Comment by haf** [comment]
@matthid No it was not; it was just a way to see what GCloud was responding.

The real issue is still open. The repro is simple; make a single http dep to that URI. I haven't gone further myself.

**Comment by haf** [comment]
However, you can replace that with https://github.com/fsprojects/Paket/issues/3079 - it's a similar issue.

**Pull request merged**
