### PR TITLE
Fix #3410 - UnauthorizedAccessException writing to MyProject.paket.references.cached

### LINKED ISSUE #3410: Paket failed with UnauthorizedAccessException writing to MyProject.paket.references.cached
### Description

When running `.paket\paket.exe restore`, sometimes it fails with an error.

### Repro steps

Uncertain how to get this to 100% repro. It seems to be fairly uncommon to get into this state, but once it's in it, it stays this way until manual intervention repairs or works around the issue.

FWIW, I've only seen this happen on developer workstations, not on headless build servers.

### Expected behavior

`paket.exe restore` restores packages without error

### Actual behavior

Error message, as below:

```
C:\CW\CWShared\ErrorReporting\Shared>.paket\paket.exe restore -v
Checking Paket version (version 5.186.0 requested)...
Paket.exe 5.186.0 is up to date.
Paket version 5.186.0
found: C:\CW\CWShared\ErrorReporting\Shared\paket.dependencies
 - C:\CW\CWShared\ErrorReporting\Shared\.paket\Paket.Restore.targets already up-to-date
Parsing C:\CW\CWShared\ErrorReporting\Shared\paket.dependencies
 - C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.NuGet.Config already up-to-date
 - C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.net46.paket.resolved created
 - C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.netstandard2.0.paket.resolved created
 - C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.paket.props already up-to-date
Failed to save cached file C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.paket.references.cached. Retry. Message: Access to the path 'C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.paket.references.cached' is denied.
Failed to save cached file C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.paket.references.cached. Retry. Message: Access to the path 'C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.paket.references.cached' is denied.
Failed to save cached file C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.paket.references.cached. Retry. Message: Access to the path 'C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.paket.references.cached' is denied.
Failed to save cached file C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.paket.references.cached. Retry. Message: Access to the path 'C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.paket.references.cached' is denied.
Failed to save cached file C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.paket.references.cached. Retry. Message: Access to the path 'C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.paket.references.cached' is denied.
Performance:
 - Runtime: 1 second
Paket failed with
-> UnauthorizedAccessException: Access to the path 'C:\CW\CWShared\ErrorReporting\Shared\src\WTG.ErrorReporting\obj\WTG.ErrorReporting.csproj.paket.references.cached' is denied.
   StackTrace:
        at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
        at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
        at Paket.RestoreProcess.loop@478-18(ReferencesFile referencesFile, FileInfo paketCachedReferencesFileName, Int32 trials)
        at Paket.RestoreProcess.loop@478-18(ReferencesFile referencesFile, FileInfo paketCachedReferencesFileName, Int32 trials)
        at Paket.RestoreProcess.loop@478-18(ReferencesFile referencesFile, FileInfo paketCachedReferencesFileName, Int32 trials)
        at Paket.RestoreProcess.loop@478-18(ReferencesFile referencesFile, FileInfo paketCachedReferencesFileName, Int32 trials)
        at Paket.RestoreProcess.loop@478-18(ReferencesFile referencesFile, FileInfo paketCachedReferencesFileName, Int32 trials)
        at Paket.RestoreProcess.loop@478-18(ReferencesFile referencesFile, FileInfo paketCachedReferencesFileName, Int32 trials)
        at Paket.RestoreProcess.createProjectReferencesFiles(LockFile lockFile, ProjectFile projectFile, ReferencesFile referencesFile, Lazy`1 resolved, FSharpMap`2 groups, FSharpOption`1 targetFrameworks)
        at Paket.RestoreProcess.RestoreNewSdkProject@531.Invoke(Unit unitVar0)
        at Paket.Utils.RunInLockedAccessMode[a](String lockedFolder, FSharpFunc`2 action)
        at Paket.RestoreProcess.Restore$cont@591(FSharpOption`1 targetFrameworks, FSharpList`1 referencesFileNames, FSharpOption`1 projectFile, Boolean ignoreChecks, FSharpOption`1 group, Boolean force, Boolean failOnChecks, String dependenciesFileName, FileInfo lockFileName, String root, Boolean isFullRestore, Lazy`1 lockFile, Lazy`1 localFile, Boolean hasLocalFile, Unit unitVar)
        at Paket.RestoreProcess.Restore(String dependenciesFileName, FSharpOption`1 projectFile, Boolean force, FSharpOption`1 group, FSharpList`1 referencesFileNames, Boolean ignoreChecks, Boolean failOnChecks, FSharpOption`1 targetFrameworks)
        at Paket.Program.handleCommand@825-14.Invoke(ParseResults`1 results)
        at Paket.Program.processWithValidationEx$cont@42[a](Boolean silent, FSharpFunc`2 commandF, a result, Unit unitVar)
        at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
        at Paket.Program.handleCommand(Boolean silent, Command command)
        at Paket.Program.main()
```

The cause is likely to be that the file is marked read-only at the filesystem level:

image

### Known workarounds

- Surgical: Manually clear the read-only flag and re-run Paket.
- Simple: Delete all `obj` folders and re-run Paket.

### PR DESCRIPTION
**Pull request by yaakov-h**
Root cause as discussed in #3410 - a source control system that marks `paket.references` as read-only.

I mostly made the integration test by copying it from the one above. It fails without the changes from the second commit, and passes with them. 😃 

I made two changes:

1. Before deleting `obj\foo.csproj.paket.references.cached` we clear the read-only flag, so that Paket can upgrade from a broken version without issue.
2. After copying `obj\foo.csproj.paket.references.cached` we clear the read-only flag, so that this doesn't re-occur, and so none of the intermediary `obj` files are read-only.

### CODE REVIEW

**Comment by forki** [comment]
Can you please take a look at the CI errors? Thx

**Comment by yaakov-h** [comment]
Hmmm. I can't reproduce the Windows failure, nor the Linux failure on Mono 4.6.

I'll try grab latest Mono (5.x) and see if I can figure anything out.

**Comment by yaakov-h** [comment]
The core issue seems to be a bug in Mono where `File.GetAttributes(...)`/`FileSystemInfo.Attributes` returns `-1`, so `FileSystemInfo.set_IsReadOnly` attempts to set the attributes to `-1 | ReadOnly` which is an invalid combination, and throws.

I haven't managed to cleanly reproduce, and it seems odd to be messing with read-only on Linux, since read-only is actually a Windows thing. On Linux and macOS, Mono and .NET Core emulate the read-only bit by adjusting the file write bits.

As such, I've locked the file-read-only behavior to Windows only, which is probably the only place where this sort of bug would be legitimately encountered anyway.

**Comment by forki** [comment]
It's still red on the appveyor.

**Comment by forki** [comment]
2) Error : Paket.IntegrationTests.RestoreSpec.#3410 Paket restore fails when obj files are readonly
System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\projects\paket\integrationtests\scenarios\i003410-readonly-obj\temp\dotnet\obj\dotnet.csproj.paket.references.cached'.

**Comment by yaakov-h** [comment]
Yeah, looking into it now.

Do you have any idea why _another_ test is also failing with a readonly file error?

I'm not familiar with the internal test infrastructure or if there are dependencies between tests / dirty state / etc.

**Comment by forki** [comment]
the other one may be unrelated

**Comment by yaakov-h** [comment]
`integrationtests/scenarios/*/before/**/obj` is in `.gitignore`, so one of my test input files was never present. 😭 

🤞 it'll be good now

**Comment by yaakov-h** [comment]
@forki any idea what's with integration test `i003012`? I haven't touched it, and my new test isn't leaving anything behind...

**Comment by forki** [comment]
It says:

> UnauthorizedAccessException: Access to the path 'C:\projects\paket\integrationtests\scenarios\i003012\temp\dotnet\obj\dotnet.csproj.paket.references.cached' is denied.

**Comment by yaakov-h** [comment]
I can see that, but I cannot for the life of me figure out _why_.

Are tests run in parallel, perhaps?

**Comment by yaakov-h** [comment]
I can't even reproduce it locally anymore. 😢

**Comment by qiuhaotc** [comment]
Same problem and that project is also .net core project😫

**Comment by yaakov-h** [comment]
@forki fixed appveyor 😄

**Comment by forki** [comment]
thanks!!!

**Pull request merged**
