### PR TITLE
thread through existing omitcontent setting into ExcludeAssets=contentFiles in the SDK

### PR DESCRIPTION
**Pull request by baronfel**
This should allow for closing #4039 by letting users specify `content: none` on a group, dependency, or reference-level.

We follow the existing patterns for the copy_local setting, and we alter the generated PackageReference nodes in both places they are generated:

* paket.props file
* Paket.Restore.targets

In addition, there is a usability tweak for new users: when we create the fsharp.core dependency in the converted paket.dependencies file we automatically add `content: none` to it, because FSharp.Core > 5.0 comes with the xml doc in the contentFiles folders, so users start getting FSharp.Core.xml listed as a content file in their apps.

### CODE REVIEW

**Comment by baronfel** [comment]
@forki since I'm changing the format of the generated props files, do I need to update the version info on [this line](https://github.com/baronfel/Paket/blob/support-omitcontent-in-sdk/src/Paket.Core/Installation/RestoreProcess.fs#L348) and the associated restore.targets version?

**Comment by baronfel** [comment]
The failing test is the same one from the other PRs: the v3 validation check...

**Comment by baronfel** [comment]
Should be unblocked by #4042

**Comment by forki** [comment]
thanks!

**Pull request merged**
