### PR TITLE
Allow comments in the references file.

### LINKED ISSUE #2371: Allow comments in paket.references
### Description

Its frustrating experience if you add a comment and a long running update then fails because of

```
Paket failed with:
        Unable to parse C:\PROJ\FSharp.Formatting\src\FSharp.Formatting.Common\paket.references
```

### PR DESCRIPTION
**Pull request by fsoikin**
Fixes #2371.

### CODE REVIEW

**Comment by forki** [comment]
Cool!

**Comment by fsoikin** [comment]
@forki note that this may become a breaking change under some very specific circumstances: before this, the `removeComment` function allowed comments to start anywhere, but now comments have to start either at the beginning of the line or after a space.

Also, I have realized that a comment can start after a space, but not after a tab. Do you think it would be a good idea to update it to allow tabs as well? Or perhaps anything that is `Char.IsWhitespace`?

**Comment by forki** [comment]
Char.iswhitespace sounds good

**Comment by fsoikin** [comment]
Got it. #2479

**Pull request merged**
