### PR TITLE
[WIP] Why oh why?

### PR DESCRIPTION
**Pull request by theimowski**
#1959

TODO:
- [ ] recognize github dependencies
- [X] show dependencies up to the top level
- [ ] option for displaying version and depending packages version constraints
- [x] show the shortest path by default, give option to show all paths
- [x] mark all direct dependencies in path
- [ ] reword "dependency path" -> "dependency chain", make the output more user-friendly
- [ ] what should be displayed when asking for a direct dependency, and what if it is not a top-level dependency?
- [ ] handle circular dependencies ?

Feedback welcome!

image

### CODE REVIEW

**Comment by cdrnet** [comment]
This will become very useful, thanks! Could it also provide some info on why a particular version is used, if applicable?

**Comment by Stift** [comment]
When a package dependency is shown, do we show all dependencies up the dependency tree up to the top-level, only top level or only to the next level?
Could also be a command switch like `--full`

**Comment by forki** [comment]
@theimowski please keep posting screenshots if you change something. This is awesome

**Comment by theimowski** [comment]
will do, I'll also let know whenever I get to the point where it could be merged - possibly with not yet all features implemented

**Comment by isaacabraham** [comment]
Would it be worth making package id optional - so that it shows why all packages are in the lock file for a given group (although this might be a bit verbose)?

**Comment by theimowski** [comment]
@Stift I think it makes sense to show all deps up to the top level by default.
What I'm wondering is whether it makes sense to print all paths from the top level package, or just choose a shortest one? (see below e.g. Microsoft.Bcl.Build) 

image

**Comment by forki** [comment]
Maybe show the shortest and say "and x more paths"?

**Comment by tommes** [comment]
Maybe (as a 2nd step) we couln't just ask for package id's, but also for artefacts - i.e. why is the dll/js/whatever in my output. In case I've overlooked that just ignore the comment.

**Comment by forki** [comment]
That would be brilliant

Am 14.10.2016 09:27 schrieb "Thomas Koch" <notifications@github.com>:

**Comment by forki** [comment]
@tommes but it's probably hard to decide without reimplementing MSBuild logic

**Comment by Stift** [comment]
I think by package Id would be sufficient for the most use case. 
If there are more than one path then, I'd like to have an option like -full or -all, if possible.
If a tree notation would be too complex I would recommend sth like ´Package1 >> Package2 >> Package3´
@theimowski Would it make sense to merge the trees, so that the output is more compact?

**Comment by forki** [comment]
If we merge the trees then we will get the lock file back

Am 14.10.2016 17:05 schrieb "Christian Fiebrig" <notifications@github.com>:

**Comment by theimowski** [comment]
Can NuGets have cyclic dependencies? And if so does it resolve to paket.lock?

**Comment by theimowski** [comment]
How about this? I've grouped the paths by the top level dependency and if from a specific top level dep there are >1 paths, we show shortest by default.
This way we won't ignore multiple top-level deps

image

**Comment by forki** [comment]
I released it in alpha. please create new PRs to keep it going ;-)

**Comment by theimowski** [comment]
Alright! Can one continue work on  the same branch and reopen PR in github or do i have to create new PRs?

**Comment by forki** [comment]
You can try to reopen. Not sure if this works.

Am 22.10.2016 17:51 schrieb "Tomasz Heimowski" <notifications@github.com>:

**Pull request merged**
