### PR TITLE
Generate default description when packing

### PR DESCRIPTION
**Pull request by inosik**
@forki you didn't revert the actual change yesterday, only the commit related to the error message. I brought the change back again.

I'm not entirely sure about the generated description, though.

/cc @richard-green

### CODE REVIEW

**Comment by inosik** [comment]
The warning gets printed even if a description exists, Have to change something.

**Comment by forki** [comment]
:kiss: thanks for helping here and staying wit us ;-)

**Comment by inosik** [comment]
I'm still not sure what @richard-green does with those invalid packages :smile:

**Comment by forki** [comment]
probably using them internally with paket as client!?

**Comment by inosik** [comment]
Should I undo the change to `RELEASE_NOTES.md`?

**Comment by forki** [comment]
No all is well

**Comment by richard-green** [comment]
Hi - yes most of our packages are for internal use, we have many of them too, so I'll get round to bulk-updating them with some generic description ;-)

**Pull request merged**
