### PR TITLE
Fixes combine restrictions

### PR DESCRIPTION
**Pull request by mrinaldi**
This PR correctly combines AtLeast with Between and Exactly with Between restrictions.

### CODE REVIEW

**Comment by forki** [comment]
Is this compatible with https://github.com/fsprojects/Paket/pull/1130? 

/cc @vbfox could you try to include this in your pr?

**Comment by mrinaldi** [comment]
#1130 doesn't fix what this PR does.
However, it'd have to be rebased there.

Do you want me to rebase on top of #1130?

**Comment by forki** [comment]
Actually I think I will merge yours (since it seems ready) and just hope that @vbfox finds a way to merge stuff ;-)

**Comment by mrinaldi** [comment]
Alright. The merge should be easy, but let me know if my help is needed.

**Comment by vbfox** [comment]
I don't think the merge will be too hard.

**Pull request merged**
