### PR TITLE
WIP: Try to activate V3 API

### PR DESCRIPTION
**Pull request by forki**
- [x] - create integration test
- [x] - reactivate API
- [ ] - fix integration test

/cc @xavierzwirtz

### CODE REVIEW

**Comment by forki** [comment]
@xavierzwirtz do you see the issue?

**Comment by xavierzwirtz** [comment]
I have most of the issue resolved, working on some minor differences between the lock file generated against a V2 api and a lock file generated against a V3 api.

**Comment by xavierzwirtz** [comment]
I have submitted a pr (#1216) that fixes most of this issue.

I updated your regression test to compare the paket.lock when run against the `v2` api and the `v3` api. [There is only one difference now,](https://www.diffchecker.com/i0lfaxjv), and I believe the bug is actually in the `v2` api. 

From what I can tell `FSharp.Data` depends on `Zlib.Portable (1.11.0)`, but when using the `v2` api it doesnt register a dependency for `Zlib.Portable (1.11.0)`.

**Comment by forki** [comment]
so you found a bug in our v2 implementation?

**Comment by xavierzwirtz** [comment]
I think so, I'd like you to take a look at it.

**Comment by forki** [comment]
image

looks like v2 is correct. ZLib.Portable is only used for portable projects.

**Comment by xavierzwirtz** [comment]
I was not calling the right method to parse framework dependencies. Fixed that. Also added caching in.

The integration test is passing now.

**Comment by forki** [comment]
Awesome. 
Will look into this tomorrow. Thanks buddy

**Comment by xavierzwirtz** [comment]
No problem, glad this was caught quickly.

**Comment by xavierzwirtz** [comment]
Submited pr #1222 

I rewrote the `v2` and `v3` getDetails to use a single cache function.

Also changed the behavior of the cache. When an error occurs it doesnt write an error file, it simply falls back to the api. Logs to the console with `traceWarnfn`.

**Comment by forki** [comment]
the error file was a idea that future runs of paket don't have to retry the same API call

**Comment by xavierzwirtz** [comment]
Requires the user to call paket with force to blow them out though, doesn't it? Feels rather irritating from a user perspective, but I can understand if that's out of scope for this pr.

**Comment by forki** [comment]
yes, but the idea was: if all calls failed (e.g. because of error files) we
will also throw error files away and retry.
So usaully nobody should call with -f

2015-11-13 18:17 GMT+01:00 Xavier Zwirtz <notifications@github.com>:

**Comment by xavierzwirtz** [comment]
Ah, okay. I think I missed that in the v3 implementation of caching.

**Comment by xavierzwirtz** [comment]
I tested the old implementation of the v2 api's caching, if an error file exists you have to run paket with -f.

**Comment by forki** [comment]
maybe things got broken. ;-)

2015-11-13 18:25 GMT+01:00 Xavier Zwirtz <notifications@github.com>:

**Comment by xavierzwirtz** [comment]
I think so. Would you like me to try to re-implement the behavior you describe?

**Comment by forki** [comment]
if you think it's useful.
I don't really know if it's still needed, since we also change to
Async.Parallel and Async.Choice combo

2015-11-13 18:27 GMT+01:00 Xavier Zwirtz <notifications@github.com>:

**Comment by xavierzwirtz** [comment]
I think the way it works right now, without error files, is simpler and not any slower. Your probably right, the async work makes it not needed.

**Comment by forki** [comment]
Ok. Then please drop the error files. I never really liked them anyways.
Actually I'm happy to get rid of these.

**Comment by xavierzwirtz** [comment]
Heh, awesome. Thats done in the current state of the pr.
On 11/13/2015 11:35:10 AM, Steffen Forkmann <notifications@github.com> wrote:
Ok. Then please drop the error files. I never really liked them anyways.
Actually I'm happy to get rid of these.

**Pull request merged**
