### PR TITLE
Allow non-standard API endpoint for push

### PR DESCRIPTION
**Pull request by mavnn**
See #651

### CODE REVIEW

**Comment by Vidarls** [comment]
Are you also updating the FAKE helper?

**Comment by mavnn** [comment]
I've lost track - where is it?

**Comment by Vidarls** [comment]
https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/PaketHelper.fs

**Comment by forki** [comment]
I can fix it. Or are you already working on it?

**Comment by mavnn** [comment]
All yours :)

**Comment by forki** [comment]
done

**Pull request merged**
