### PR TITLE
Fix Unlisted not getting set properly when using V3 api.

### LINKED ISSUE #1242: paket outdated goes off on a useless search when using the v3 api
dependencies:

```
redirects: on

source https://api.nuget.org/v3/index.json
source https://www.nuget.org/api/v2/

nuget FSharp.Control.Reactive
nuget FSharp.Data framework: >= net40
nuget FsLexYacc framework: >= net40
nuget FsUnit framework: >= net45
nuget Newtonsoft.Json framework: >= net40
nuget NLog.FSharp 3.2.1 framework: >= net40
nuget NLog 3.2.1 framework: >= net40
nuget SnmpSharpNet
nuget NUnit.Runners
nuget FAKE ~> 4
nuget FSharp.Formatting.CommandTool
nuget FSharp.Core ~> 4 framework: >= net40
nuget ILRepack
```

Output:
```
Paket version 2.27.2.0
Resolving packages for group Main:
 - FAKE 4.9.3
 - FSharp.Core 4.0.0.1
 - NLog is pinned to 3.2.1
 - NLog.FSharp is pinned to 3.2.1
 - FSharp.Control.Reactive 3.2.0
 - FSharp.Formatting.CommandTool 2.12.0
 - ILRepack 2.0.8
 - NUnit.Runners 3.0.0
 - SnmpSharpNet 0.9.4
 - SnmpSharpNet 0.9.3
 - SnmpSharpNet 0.9.2
 - FSharp.Data 2.2.5
 - FsLexYacc 6.1.0
 - FsLexYacc 6.0.4
 - FsLexYacc 6.0.3
 - FsLexYacc 6.0.2
 - FsLexYacc 6.0.1
 - FsLexYacc 6.0.0
 - Newtonsoft.Json 7.0.1
 - Newtonsoft.Json 6.0.8
 - Newtonsoft.Json 6.0.7
 - Newtonsoft.Json 6.0.6
 - Newtonsoft.Json 6.0.5
 - Newtonsoft.Json 6.0.4
 - Newtonsoft.Json 6.0.3
 - Newtonsoft.Json 6.0.2
 - Newtonsoft.Json 6.0.1
 - Newtonsoft.Json 5.0.8
 - Newtonsoft.Json 5.0.7
 - Newtonsoft.Json 5.0.6
 - Newtonsoft.Json 5.0.5
 - Newtonsoft.Json 5.0.4
 - Newtonsoft.Json 5.0.3
 - Newtonsoft.Json 5.0.2
 - Newtonsoft.Json 5.0.1
 - Newtonsoft.Json 4.5.11
 - Newtonsoft.Json 4.5.10
 - Newtonsoft.Json 4.5.9
 - Newtonsoft.Json 4.5.8
 - Newtonsoft.Json 4.5.7
 - Newtonsoft.Json 4.5.6
 - Newtonsoft.Json 4.5.5
 - Newtonsoft.Json 4.5.4
 - Newtonsoft.Json 4.5.3
 - Newtonsoft.Json 4.5.2
 - Newtonsoft.Json 4.5.1
 - Newtonsoft.Json 4.0.8
 - Newtonsoft.Json 4.0.7
 - Newtonsoft.Json 4.0.6
 - Newtonsoft.Json 4.0.5
 - Newtonsoft.Json 4.0.4
 - Newtonsoft.Json 4.0.3
 - Newtonsoft.Json 4.0.2
 - Newtonsoft.Json 4.0.1
 - Newtonsoft.Json 3.5.8
 - FsUnit 1.4.0
 - NUnit.Console 3.0.0
 - NUnit 2.6.4
 - FsLexYacc.Runtime 6.1.0
 - Rx-Core 2.2.5
 - Rx-Interfaces 2.2.5
 - Rx-Linq 2.2.5
Outdated packages found:
  Group: Main
    * FAKE 4.7.2 -> 4.9.3
    * FsUnit 1.3.1 -> 1.4.0
    * NUnit.Runners 2.6.4 -> 3.0.0
```

If I remove the v3 source

```
Paket version 2.27.2.0
Resolving packages for group Main:
 - FAKE 4.9.3
 - FSharp.Core 4.0.0.1
 - NLog is pinned to 3.2.1
 - NLog.FSharp is pinned to 3.2.1
 - FSharp.Control.Reactive 3.2.0
 - FSharp.Formatting.CommandTool 2.12.0
 - ILRepack 2.0.8
 - NUnit.Runners 3.0.0
 - SnmpSharpNet 0.9.4
 - FSharp.Data 2.2.5
 - FsLexYacc 6.1.0
 - Newtonsoft.Json 7.0.1
 - FsUnit 1.4.0
 - NUnit.Console 3.0.0
 - NUnit 2.6.4
 - FsLexYacc.Runtime 6.1.0
 - Rx-Core 2.2.5
 - Rx-Interfaces 2.2.5
 - Rx-Linq 2.2.5
Outdated packages found:
  Group: Main
    * FAKE 4.7.2 -> 4.9.3
    * FsUnit 1.3.1.0 -> 1.4.0
    * NUnit.Runners 2.6.4 -> 3.0.0
11 seconds - ready.
```

### PR DESCRIPTION
**Pull request by xavierzwirtz**
Fixes #1242

### CODE REVIEW

**Comment by forki** [comment]
:hugs:

**Comment by forki** [comment]
looks like it's doing the opposite!?

**Comment by forki** [comment]
but's an easy fix

**Comment by xavierzwirtz** [comment]
Oh dammit. I'm afk now, can't fix it for a couple hours.

**Comment by xavierzwirtz** [comment]
It passed the integration test though, which seems very odd.

**Comment by forki** [comment]
No problem. I've already done it. Thanks for the help.

**Comment by forki** [comment]
regarding integration tests: if all versions are unlisted then paket tries a second run with out the flag ;-)

**Pull request merged**
