### PR TITLE
don't use hyphen in environment variables. Most shells do not like th…

### PR DESCRIPTION
**Pull request by matthid**
…at. (it's a windows only thing basically)

### CODE REVIEW

**Comment by matthid** [comment]
https://github.com/fish-shell/fish-shell/issues/1206

**Comment by forki** [comment]
so I need to change my release script?

**Comment by matthid** [comment]
That's why I added it as PR ;) Now you can decide. Or we read both don't really care so much either way...

**Comment by forki** [comment]
Read both, then I don't have to do anything

Am 25.05.2017 5:26 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Pull request merged**
