### PR TITLE
#2599 : Package detail request fallback when no package detail in main feed.

### PR DESCRIPTION
**Pull request by jcchalte**
NuGetV2 :
- Corrected an edge case where the Nuget Feed does not expose the package detail in the root feed but let the user access details directly through the detail URL.
Should correct #2599

### CODE REVIEW

**Comment by forki** [comment]
(don't worry if the Travis goes red. We currently experience a bit of mono trouble.)

**Comment by jcchalte** [comment]
Well, I have looked at the codebase for another  "Packages(Id=" and you are right, this case is already used but only on URL that appears to be tfs or vsts related (eg. if `urlSimilarToTfsOrVsts` function returns true).

So we could either change this test to include more cases such as the devexpress case (but I can't see any way to do this just from the URL without adding one more hard-coded test, and nothing in the feed seems really relevant at first sight) or maybe remove the TfsOrTst branch and let those queries bubble up to the 5 ou 6th fallback function ? But it will slow down those queries....

**Comment by forki** [comment]
I will think about it and discuss it with @matthid. I think we will release
your pr as hotfix and then try to merge @matthid's perf improvements.

Sorry @matthid - this will need another rebase then. :P

But I assume we can then remove that other code path completely. Because
perf comes back with @matthid's tricks

Am 11.08.2017 09:05 schrieb "Jean-Christophe Chalté" <
notifications@github.com>:

**Comment by matthid** [comment]
Can you all please retry with  5.86.0-alpha002. Otherwise we might break you on next release.

**Pull request merged**
