### PR TITLE
Fix repeated conflict detection and introduce optional resolver timeout

### PR DESCRIPTION
**Pull request by viktor-svub**
- repeated conflict detection used `HashSet` as set item -- as it was not comparable, it was always adding new records -- it was replaced by F# `Set` which implements comparable as expected
- added support for `PAKET_RESOLVER_TIMEOUT` environment variable, allowing to terminate the resolver in finite time -- for cases when we hit "loop of doom" on automated build agents
- switched to UTC time handling to avoid DST glitches (plus, UtcNow is faster)

### CODE REVIEW

**Comment by forki** [comment]
oups ;-)

**Comment by matthid** [comment]
Good, maybe that explains our changing Lockfile as well.

**Comment by forki** [comment]
ok there are two integration tests failing. I think it's because the output changed

**Comment by viktor-svub** [comment]
I may be mistaken but it looks to me like the failure is unrelated -- i.e. the `#1177 should resolve with pessimistic strategy correctly` failed with: 
```
-> Could not find versions for package Castle.Windsor on http://www.nuget.org/api/v2.
-> Source 'http://www.nuget.org/api/v2' yielded no results
	-  Request 'http://www.nuget.org/api/v2/FindPackagesById()?semVerLevel=2.0.0&id='Castle.Windsor'' finished with error
	-> Could not retrieve data from 'http://www.nuget.org/api/v2/FindPackagesById()?semVerLevel=2.0.0&id='Castle.Windsor''
	-> HttpRequestException: An error occurred while sending the request
	-> WebException: Error: TrustFailure (One or more errors occurred.)
	-> AuthenticationException: A call to SSPI failed, see inner exception.
	-> MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
	     at /build/mono-5.4.1.7/external/boringssl/ssl/handshake_client.c:1132
```
And `#55 should resolve with pessimistic strategy correctly` is similar, just with different package. 
Isn't this something changed recently on `master`?

**Comment by forki** [comment]
master is green AFAIK

**Comment by viktor-svub** [comment]
Also locally (Windows only) the `build RunIntegrationTestsNetCore SkipDocs=1` with `PAKET_RESOLVER_WORKERS=24` and `PAKET_TESTSUITE_FLAKYTESTS=false` passed all tests. 

Right, I have no Mono install, and `master` is green, but I cannot see how these changes affected certificate validation against `nuget.org` -- maybe this PR is not re/based correctly?

**Comment by forki** [comment]
ok let me try to rebase it in new PR

**Comment by forki** [comment]
let's see https://github.com/fsprojects/Paket/pull/3085

**Comment by forki** [comment]
the other one is green

**Comment by forki** [comment]
Thx. It's released

**Pull request closed without merging**
