### PR TITLE
[WIP] Generate include script for each group

### PR DESCRIPTION
**Pull request by smoothdeveloper**
This includes #1786 (I did that to separate code review if we want to merge in two steps)

This PR add generation of a script per group, like @Krzysztof-Cieslak asked for:

`paket-files/include-scripts/net45/include.main.group.fsx`

the include script contains all the framework and file assemblies resolved in a single pass.

- [x] generate a script per group
- [ ] write few tests
- [ ] do not include mscorlib and FSharp.Core for .fsx files (factorize the existing code)

### CODE REVIEW

**Comment by matthid** [comment]
Oh nice, this fixes https://github.com/fsprojects/Paket/issues/1680 as well. Actually I could use this right now in my FAKE stuff, so perfect timing :)

**Comment by matthid** [comment]
Why generate "one big" script instead of loading the ones we already have?

**Comment by smoothdeveloper** [comment]
@matthid few reasons:

* I suspect the compiler / tooling to handle this better (https://github.com/Microsoft/visualfsharp/issues/1311) which is basically what prompted me to go this route (and help investigate the issue)
* it should be faster, it won't parse dozen of files and need less deduplication to be executed
* it is also more convenient to have a single list of all of those references when user wants to make a workaround in his own include script in case this one doesn't work out of the box (most likely due to tooling bug)
* more user friendly when I "go to definition" on the script and can see all of it's beauty without browsing a web of small files

since the file is generated also and code to implement that is rather small, I don't think we should bother taking another route.

What do you think?

Thanks for feedback!

**Comment by matthid** [comment]
Yeah I don't have a strong opinion on this, just curiosity. I think generating one file is fine.

One thing I noticed (if I even saw that correctly) is that you currently don't use the ordered package list. This might lead to errors for dependencies across packages.

**Comment by smoothdeveloper** [comment]
@matthid is it not on this line: https://github.com/fsprojects/Paket/pull/1787/files#diff-87b562c7f3686bb8259c47e6ba1b6ba8R250 ?

**Comment by matthid** [comment]
Ah I didn't noticed that you are running the function over the complete list of assemblies for the group. Yeah this should work.

**Comment by isaacabraham** [comment]
You also don't want to load the same assemblies in twice, so a single script without duplicates might be preferable.

**Comment by forki** [comment]
is tis ready to merge?

**Comment by smoothdeveloper** [comment]
@forki the feature is working but it doesn't have specific integration/unit tests yet, and there are probably bugs that we have yet to find from usage.

I'm ok having it merged (useful feature) and to work on adding test in separate PR.

**Comment by forki** [comment]
Looks like one of the related integration tests is broken

**Comment by forki** [comment]
can you please take a look at master. I have 3 broken tests now

**Comment by smoothdeveloper** [comment]
@forki, I'm on it I'll have a fix shortly.

**Pull request merged**
