### PR TITLE
Added MonoAndroid9.0 + compatibility between .NET Standard 2.0 and MonoAndroid8.0/XamariniOS

### PR DESCRIPTION
**Pull request by TimLariviere**
.NET Standard 2.0 is compatible with MonoAndroid >= 8.0 and Xamarin.iOS >= 10.14, but this was missing in Paket.
Also Android Pie has been released last month, so I added a new moniker `MonoAndroid9.0`.

Let me know if I'm missing anything.

### CODE REVIEW

**Comment by TimLariviere** [comment]
Also the new moniker doesn't seem to work.
`Could not parse framework 'monoandroid9.0'. Try to update or install again or report a paket bug.`
Any idea what I'm doing wrong?

**Comment by forki** [comment]
something is weird with the CI server

**Comment by TimLariviere** [comment]
Ok, found why Paket was not able to parse monoandroid9.0.

**Comment by forki** [comment]
thanks!

**Pull request merged**
