### PR TITLE
#1019 always redirect to the Redirect.Version

### PR DESCRIPTION
**Pull request by reidev275**

### CODE REVIEW

**Comment by forki** [comment]
cool. only a couple of test errors now ;-)

**Comment by isaacabraham** [comment]
@reidev275 OK, just a few unit tests to fix as well.

**Comment by isaacabraham** [comment]
Damn @forki did you write a cross-country mind-reader in F# last night in your spare time or something?

**Comment by Krzysztof-Cieslak** [comment]
Microsoft Telepathy (™)

**Comment by reidev275** [comment]
Sorry, very new to the whole FSharp project scaffold with the build scripts.  Thanks for being understanding as always !

**Comment by forki** [comment]
awesome. thx

awesome

**Comment by isaacabraham** [comment]
@reidev275 excellent - that's exactly why "up-for-grabs" like this are good - you get to learn more about the project scaffold and the infrastructure behind the CI process, which is usually pretty consistent across most of fsprojects :-)

**Comment by reidev275** [comment]
yeah, love the idea of the up for grabs issues.  That's exactly why I was
excited to jump in on this one.

**Pull request merged**
