### PR TITLE
Switched to using Chessie Nuget package.

### LINKED ISSUE #1253: Use Chessie package from Nuget
I am referencing Paket.Core in a project, as well as using Chessie. The way Paket includes a full copy of Chessie is causing lots of pain and suffering translating between the Paket Chessie and the regular Chessie assembly. Would it be possible to switch Paket.Core to reference the Chessie Nuget package?

### PR DESCRIPTION
**Pull request by xavierzwirtz**
Resolves #1253

### CODE REVIEW

**Comment by forki** [comment]
could you please also add it to the ILRepack phase:

https://github.com/fsprojects/Paket/blob/master/build.fsx#L193
https://github.com/fsprojects/Paket/blob/master/build.fsx#L204

**Comment by xavierzwirtz** [comment]
Did that.

**Comment by xavierzwirtz** [comment]
Thanks!

**Comment by forki** [comment]
it's relased as alpha. please confirm that it works, then I will release.
Btw: the impact on the dll is 2KB. So it went from 3935 KB to 3937KB. I think that's OK ;-)

**Comment by xavierzwirtz** [comment]
Tested `2.30.0-alpha002`. Everything looks good. Compiles and all my tests pass.

**Pull request merged**
