### PR TITLE
Dog fooding "pack" and "push"

### LINKED ISSUE #619: Dogfood pack command
We now have the pack command available in the latest alpha version (see #613 and [docs](http://fsprojects.github.io/Paket/template-files.html)).
We should start by dogfooding it.

/cc @mavnn

### PR DESCRIPTION
**Pull request by mavnn**
Closes #619 

Bit ugly until we get a fake helper.

I'm also wondering if we want to expand the number of fields we'll infer from projects beyond what NuGet allows. Later, I think...

### CODE REVIEW

**Comment by mavnn** [comment]
This uses both a "type project" (for Paket.Core) and a "type file" (the ilmerged paket.exe) template, so if you can publish using this I would say we have a decent sanity check of the core functionality.

**Comment by forki** [comment]
happy dogfooding
i-have-no-idea-what-im-doing-dog

**Comment by forki** [comment]
image

;-)

It's trying to push packages from the `packages` folder. We need to make sure to only push our own pckages. Ideas?

**Comment by mavnn** [comment]
Hmm. Yes, looks like we need to take a root directory parameter like for do for the packing. I was just scanning from dependency file down.

Give me a bit, I might get grabbed for lunch in the middle.

**Pull request merged**
