### PR TITLE
generate nuspecs in IntermediateOutputPath

### LINKED ISSUE #2865: Paket.restore.targets creates nuspec in wrong folder
I just upgrade a solution to the new csproj format, but have a problem with packaging with `dotnet pack`
 afterwards. As I understand `paket.Restore.targets` override the packaging process by generating nuspec files which are modified afterward by `paket fix-nuspecs`. The problem is that these nuspec files are duplicated in `obj` and `obj/$(Configuration)`, and only last one is correct. There is one project which does not have a `paket.references` file and it is correctly generated.

As I work-a-round I tried deleting the entire section in the  `paket.Restore.targets` and now everything works as expected. Dependencies are also correct.

### PR DESCRIPTION
**Pull request by johlrich**
this is so they go in obj/Configuration/ instead of obj/

closes #2865

### CODE REVIEW

**Comment by forki** [comment]
Pinging @matthid because I'm on vacation

**Comment by forki** [comment]
@johlrich  can you please take a look at the broken test in appveyor
(travis is expected to be red)

**Comment by johlrich** [comment]
Looks like I didn't test with the IntermediateOutputPath variable enough. That one includes the configuration and the target framework in the path. I switched back to `$(BaseIntermediateOutputPath)$(Configuration)/` and will keep an eye on the appveyor result.

**Comment by forki** [comment]
Mhm still red?

**Comment by forki** [comment]
Maybe the test is no good?

**Comment by johlrich** [comment]
Hmmmmm the test passes locally after switching. The test also fails here without the changes complaining about no description, and when looking at the in the scenario temp folder I see the same situation as the issue: an extra blank nuspec at obj root. Not sure why it's passing now.

Strange that I'm getting the opposite results as appveyor. Not really sure of a good way to troubleshoot atm. @forki any ideas? 

My only thought was to somehow capture the scenario temp folder from the appveyor build to take a closer look in both scenarios, but not sure how to do that tbh.

**Comment by forki** [comment]
Maybe different dotnet cli versions?

Am 29.10.2017 15:35 schrieb "Jonathan Ohlrich" <notifications@github.com>:

**Comment by johlrich** [comment]
@forki I think that's it. I isolated that one test and then ran it with `DOTNET_EXE_PATH` set to both the preview one that the build downloads (2.1.0-preview1-007002) and the one I have installed (2.0.2). The preview one fails, the install one passes.

Going to change to 2.0.2 so appveyor gets kicked off again with it to prove that out there. If that works then we'll have to see how you want to handle that. 🤞

**Comment by johlrich** [comment]
More weirdness, the full build is currently churning through the integration tests on my machine with 2.0.2 but appveyor can't seem to get past restoring Paket.Core.preview3.

**Comment by forki** [comment]
Yes changing the dotnet cli version is not the solution here

Am 29.10.2017 20:10 schrieb "Jonathan Ohlrich" <notifications@github.com>:

**Comment by johlrich** [comment]
Ok, it is now checking for existence in the new location and if it couldn't find it, falling back to the old location. Build finally green and worked with both cli versions here.

Not super familiar with MSBuild so let me know if there was a simpler way to do that since Exists doesn't seem to do wildcards

**Pull request merged**
