### PR TITLE
taskTimeout was increased to 180,000 ms

### PR DESCRIPTION
**Pull request by vik-borisov**
Restoring the package was unsuccessful with a low-speed network connection

### CODE REVIEW

**Comment by matthid** [comment]
Not sure if this is the correct approach here... 30s is already quite a lot of time for a request to finish. Even with a slow connection.
Maybe this is related to our now request preloading... Maybe we start just too many requests in parallel for the same server?

**Comment by forki** [comment]
@vik-borisov is this against nuget.org?

**Comment by vik-borisov** [comment]
no, it is myget

**Comment by forki** [comment]
and it was restore that failed - the download. right?

**Comment by matthid** [comment]
To be honest this change is completely unrelated to restore. And even if it would help - I still think it's the wrong way :)

**Comment by forki** [comment]
that's why I asked. I have no problem with increasing an already arbitray timeout. but wonder if the reported issue is actually restore

**Comment by vik-borisov** [comment]
Yes, the restore will fail. But then I increased the environment variable PAKET_RESOLVER_TASK_TIMEOUT to 180,000, then the problem was solved

**Comment by vik-borisov** [comment]
If i use package local cache or i use version 4, i have no problem

**Comment by matthid** [comment]
But restore/download is actually repeated 3 times, was that reported by paket?
That the environment variable helped probably was just an accident?

**Comment by vik-borisov** [comment]
Environment variable - is workaround, but it work for me and my colleagues

**Comment by matthid** [comment]
Can you show the failing output?

**Comment by vik-borisov** [comment]
Well, I'll try to reproduce this error

**Comment by vik-borisov** [comment]
`
Paket failed with:
-> There was a version conflict during package resolution.
     Resolved packages:
      - StimulReport.Base 2015.1.0.0
     Conflict detected:
      - Dependencies file requested package StimulReport.Web: 2015.1
      - Available versions:
        - (2016.2.0.0, [https://myget.org])
        - (2016.1.0.1, [https://myget.org])
        - (2016.1.0.0, [https://myget.org])
        - (2015.1.0.0, [https://myget.org])

     Please try to relax some conditions or resolve the conflict manually (see http://fsprojects.github.io/Paket/nuget-d
ependencies.html#Use-exactly-this-version-constraint).
   StackTrace:
        в Paket.PackageResolver.ResolutionModule.getModelOrFail(Resolution res)
        в Paket.UpdateProcess.groups@129-6.Invoke(GroupName groupName, DependenciesGroup dependenciesGroup)
        в Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
        в Microsoft.FSharp.Collections.FSharpMap`2.Map[b](FSharpFunc`2 f)
        в Paket.UpdateProcess.selectiveUpdate[a](Boolean force, FSharpFunc`2 getSha1, FSharpFunc`2 getVersionsF, FSharpF
unc`2 getPackageDetailsF, FSharpFunc`2 getRuntimeGraphFromPackage, LockFile lockFile, DependenciesFile dependenciesFile,
 UpdateMode updateMode, SemVerUpdateMode semVerUpdateMode)
        в Paket.UpdateProcess.SelectiveUpdate(DependenciesFile dependenciesFile, FSharpOption`1 alternativeProjectRoot,
UpdateMode updateMode, SemVerUpdateMode semVerUpdateMode, Boolean force)
        в Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions opti
ons)
        в <StartupCode$Paket-Core>.$PublicAPI.Update@238.Invoke(Unit unitVar0)
        в Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
        в Paket.Program.main@471-15.Invoke(ParseResults`1 results)
        в Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseRes
ults`1 result)
        в Paket.Program.main$cont@453(ParseResults`1 results, Boolean silent, Boolean fromBootstrapper, Unit unitVar)
        в Paket.Program.main()
-> Unable to retrieve package details for 'StimulReport.Web'-2015.1.0.0
   StackTrace:
        в Paket.PackageResolver.getPackageDetailsBlock@869.Invoke(FSharpList`1 sources, GroupName groupName, PackageName
 packageName, SemVerInfo semVer)
        в Paket.PackageResolver.explorePackageConfig(FSharpFunc`2 getPackageDetailsBlock, PackageConfig pkgConfig)
-> TimeoutException: Waited 30 seconds for a request to finish.
         Check the following sources, they might be rate limiting and stopped responding:
          - https://myget.org
          - https://myget.org
          - https://myget.org
          - https://myget.org
`

**Comment by vik-borisov** [comment]
This error is reproduced for version 5.1.7. For version 5.2.1 works fine

**Comment by matthid** [comment]
But this means you are doing `paket install` or `paket update` and not `paket restore`...

**Comment by vik-borisov** [comment]
yes, now i was used `paket update`.

**Pull request merged**
