### PR TITLE
Cleans binding redirects

### LINKED ISSUE #1218: Binding redirects not being updated on paket install
I'm having some problems isolating the exact scenarios causing this, but the issue appears to have appeared somewhere between 2.20 and 2.23.

I'll carry on having a look :)

### PR DESCRIPTION
**Pull request by mrinaldi**
This PR closes #1218.

It removes all binding redirects when the `--hard` flag is used.

It also marks all binding redirects with a `<!--Paket-->` comment.
This was the best way I've found to mark the paket's redirects.
Since it does that, it also removes all binding redirects marked with the comment, regardless the `--hard` is used.

Take this `app.config` for example:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<runtime><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="Ploeh.AutoFixture" publicKeyToken="b24654c590009d4f" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="3.36.9.0" />
  </dependentAssembly>
  <dependentAssembly>
    <assemblyIdentity name="Castle.Core" publicKeyToken="407dd0808d44fbdc" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="3.0.0.0" />
  </dependentAssembly>
  <dependentAssembly>
    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="7.0.0.0" />
  </dependentAssembly>
  <dependentAssembly>
	<!-- Paket -->
    <assemblyIdentity name="xunit.extensions" publicKeyToken="8d05b1bb7a6fdb6c" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="1.9.2.1705" />
  </dependentAssembly>
</assemblyBinding></runtime></configuration>
```

*This project only needs `Castle.Core` and `Newtonsoft.Json` binding redirect*

Running `paket install`, this is the result:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<runtime><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="Ploeh.AutoFixture" publicKeyToken="b24654c590009d4f" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="3.36.9.0" />
  </dependentAssembly>
  <dependentAssembly>
    <!--Paket-->
    <assemblyIdentity name="Castle.Core" publicKeyToken="407dd0808d44fbdc" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="3.3.0.0" />
  </dependentAssembly>
  <dependentAssembly>
    <!--Paket-->
    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="7.0.0.0" />
  </dependentAssembly>
</assemblyBinding></runtime></configuration>
```

Note that `Ploeh.AutoFixture` redirect was not removed because it was not marked.
`xunit.extensions` redirect was marked though, hence it was removed.

On the other hand, running `paket install --hard` this is the resulting file:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<runtime><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <!--Paket-->
    <assemblyIdentity name="Castle.Core" publicKeyToken="407dd0808d44fbdc" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="3.3.0.0" />
  </dependentAssembly>
  <dependentAssembly>
    <!--Paket-->
    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="7.0.0.0" />
  </dependentAssembly>
</assemblyBinding></runtime></configuration>
```

Note that regardless the redirect was marked, it was removed, leaving only the required redirects.

### CODE REVIEW

**Comment by baronfel** [comment]
What's the rationale for using `<!--Paket-->` instead of `<Paket>True</Paket>` like in the .csproj?

```
<Reference Include="FSharpx.Collections">
    <HintPath>..\packages\FSharpx.Collections\lib\portable-net4+sl4+wp71+win8\FSharpx.Collections.dll</HintPath>
    <Private>True</Private>
    <Paket>True</Paket>
</Reference>
```

**Comment by isaacabraham** [comment]
Was just going to ask the same question - surely better to use an attribute or element?

Also - whilst you're at this, can you see if it's possible to properly format the BR area of XML as well? If it's more than 60 seconds work, leave it and I'll raise an issue for it.

**Comment by mrinaldi** [comment]
I checked the `urn:schemas-microsoft-com:asm.v1` schema and for some reason I thought a `<Paket>True</Paket>` was not allowed. I never tested it though. <-- that's me being stupid

I just tested it and it does work. I'm gonna change it and update the PR.

@isaacabraham I'd rather do it in another PR

**Comment by isaacabraham** [comment]
That's cool. Cheers.

**Comment by mrinaldi** [comment]
I've updated the PR to create `<Paket>` nodes instead.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<runtime><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <Paket>True</Paket>
    <assemblyIdentity name="Castle.Core" publicKeyToken="407dd0808d44fbdc" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="3.3.0.0" />
  </dependentAssembly>
  <dependentAssembly>
    <Paket>True</Paket>
    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="7.0.0.0" />
  </dependentAssembly>
</assemblyBinding></runtime></configuration>
```

**Comment by forki** [comment]
Awesome. Thanks

**Comment by mavnn** [comment]
@mrinaldi thanks for that! Saved me a lot of work :D

**Comment by mrinaldi** [comment]
awesome

**Comment by forki** [comment]
:heart:

**Pull request merged**
