### PR TITLE
remove unused code

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by matthid** [comment]
Yes the unused code was a oversight temporarily used for debugging, nice catch.

Did you profile/measure the switch to hashset? I'm asking because the list is always quite small, so the hashset might not even be optimal. At least this code did not yield any alarm bells in the profiler at the time...

**Comment by matthid** [comment]
```
1) Failed : Paket.LockFile.ParserSpecs.should parse lock file many frameworks
  Expected: "NUGET
  remote: https://www.nuget.org/api/v2
    CommonServiceLocator (1.3) - restriction: || (== sl5) (>= net40) (>= portable-net45+monoandroid+xamarinios+win8+wp8+wpa81)
    MvvmLightLibs (5.2)
      CommonServiceLocator (>= 1.0) - restriction: || (== net35) (== sl4)
      CommonServiceLocator (>= 1.3) - restriction: || (== sl5) (>= net40) (>= portable-net45+monoandroid+xamarinios+win8+wp8+wpa81)"
Actual: "NUGET
  remote: https://www.nuget.org/api/v2
    CommonServiceLocator (1.3) - restriction: || (== sl5) (>= net40) (>= portable-net45+win8+wp8+wpa81)
    MvvmLightLibs (5.2)
      CommonServiceLocator (>= 1.0) - restriction: || (== net35) (== sl4)
      CommonServiceLocator (>= 1.3) - restriction: || (== sl5) (>= net40) (>= portable-net45+win8+wp8+wpa81)"
  Expected string length 406 but was 360. Strings differ at index 135.
  Expected: "...(>= net40) (>= portable-net45+monoandroid+xamarinios+win8+..."
  But was:  "...(>= net40) (>= portable-net45+win8+wp8+wpa81)\r\n    MvvmLig..."
```

This is actually correct as you can see in http://nugettoolsdev.azurewebsites.net/4.0.0/parse-framework?framework=portable-net45%2Bmonoandroid%2Bxamarinios%2Bwin8%2Bwp8%2Bwpa81

Not exactly sure how that PR fixes the portable detection.


Same for 
```
3) Failed : Paket.LockFile.ParserSpecs.should parse portable lockfile
  Expected: ">= portable-net40+win8+wp8+sl5"
Actual: ">= portable-net40+sl5+win8+wp8"
  String lengths are both 30. Strings differ at index 18.
  Expected: ">= portable-net40+win8+wp8+sl5"
  But was:  ">= portable-net40+sl5+win8+wp8"
  -----------------------------^
at FsUnit.Extensions.shouldEqual[a](a expected, a actual) in C:\projects\paket\paket-files\test\forki\FsUnit\FsUnit.fs:line 10
```

I'm not exactly sure about

```

2) Failed : Paket.LockFile.ParserSpecs.should parse new restrictions || (&& (< net45) (>= portable-net45+win8+wp8+wpa81)) (&& (< portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81) (>= portable-net45+win8+wp8+wpa81))
...
  Expected string length 1344 but was 1023. Strings differ at index 308.
  Expected: "...t.Bcl (1.1.10) - restriction: || (&& (< net45) (>= portabl..."
  But was:  "...t.Bcl (1.1.10) - restriction: && (< net45) (>= portable-ne..."
  --------------------------------------------^
at FsUnit.Extensions.shouldEqual[a](a expected, a actual) in C:\projects\paket\paket-files\test\forki\FsUnit\FsUnit.fs:line 10

```

But maybe paket now detects that one of the platforms is a proper subset of the other... On the other hand it might be a incorrect detection of `portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81` to one of the default profiles. As NuGet cannot assign a default portable profile (http://nugettoolsdev.azurewebsites.net/4.0.0/parse-framework?framework=portable-net45%2Bmonoandroid%2Bmonotouch%2Bxamarinios%2Bxamarinmac%2Bwin8%2Bwp8%2Bwpa81) We should not do it as well.

**Comment by matthid** [comment]
Let me know if that makes any sense at all :)

**Comment by forki** [comment]
I think the hash set is a failed experiment ;-)

Am 12.08.2017 12:28 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by matthid** [comment]
Ah now I see.

This is really weird, maybe a nuget bug. 
"portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81" -> No detection

But if the non pcl stuff is removed:

"portable-net45+win8+wp8+wpa81" -> Profile 259

I think we would need to ask a NuGet expert about this. 
If we want to mirror NuGet it will be tough without understanding the underlying logic...

**Comment by matthid** [comment]
Ok latest NuGet detects 259 as well: http://nugettoolsdev.azurewebsites.net/4.3.0-preview4/parse-framework?framework=portable-net45%2Bmonoandroid%2Bmonotouch%2Bxamarinios%2Bxamarinmac%2Bwin8%2Bwp8%2Bwpa81

So this is probably fine.

**Comment by forki** [comment]
So what should we do now?

Am 12.08.2017 12:38 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

Ok latest NuGet detects 259 as well: http://nugettoolsdev.
azurewebsites.net/4.3.0-preview4/parse-framework?framework=portable-net45%
2Bmonoandroid%2Bmonotouch%2Bxamarinios%2Bxamarinmac%2Bwin8%2Bwp8%2Bwpa81

So this is probably fine.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/pull/2609#issuecomment-321973195>, or mute
the thread

**Comment by matthid** [comment]
What you mean? Updating the tests?

**Comment by matthid** [comment]
Maybe remove the last commit

**Comment by forki** [comment]
If you think the changes make sense

Am 12.08.2017 12:40 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by matthid** [comment]
Yes strictly speaking they are probably a bugfix for some non-existing pcl users ;)

**Comment by forki** [comment]
Ok. Reverted sets

**Pull request merged**
