### PR TITLE
Add support for custom internet proxy credentials with env vars

### PR DESCRIPTION
**Pull request by dedale**
At work our internet proxy uses custom credentials (different from Active Directory standard credentials). E.g AD login is like sforkman150915 but proxy login is steffen.forkmann.

By default, Paket and bootstrapper set default credentials in IWebProxy. They fail with 407 if I want to use them. I've seen other strange behaviors like partial nuget conversion. I cannot use FsReveal for the same reasons (407!)

At work some of our tools use the following env vars: http_proxy, https_proxy and no_proxy (bypass list).

So I added support for these variables in Paket and bootstrapper.

I did it twice (once in C# for bootstrapper and once in F# for Paket Utils). I could not come with a pretty solution to factor this.

I tried to add as many tests as I could (did not test all the possibilities though)

Please review this commit. I'm not very fluent in F# yet.
I am wondering if env var are case sensitive in mono environment.

See also: https://msdn.microsoft.com/fr-fr/library/Hh272656.aspx

Next step: try to convince my team to ditch nuget...

### CODE REVIEW

**Comment by forki** [comment]
@kot_2010 could you please take a look if this would still work for you? Thx

**Comment by forki** [comment]
Seems the tests fail on TravisCI / mono ;-)

**Comment by forki** [comment]
and could you please rebase the PR? thx

**Comment by vasily-kirichenko** [comment]
Sorry, I'm on a vocation till 23/09.

**Comment by dedale** [comment]
I will rebase the PR.
I need to setup some linux distro in VirtualBox to fix the mono failures (I dont think I can reproduce on Windows)

**Comment by dedale** [comment]
I'm trying tro reproduce travis/mono failures.
I have installed the following ubuntu packages: `fsharp 4.0.0.3-0xamarin1`, `mono-complete 4.0.4.1-0xamarin1`.
Unfortunately, building paket fails with very strange errors:

image

**Comment by dedale** [comment]
Well problem disappeared after a couple of reinstallations and playing with alpha and beta mono channels. Not understood... No I can reproduce my bugs on mono.

**Comment by dedale** [comment]
Env vars ARE case sensitive under mono environment. Should be fixed now (too late to wait for CI builds)... :zzz:

**Comment by dedale** [comment]
:v: wow this was fast!

**Comment by forki** [comment]
danger

thanks. Let's see how this works in practice ;-)

**Comment by forki** [comment]
I guess we could need some docs for this.

**Comment by dedale** [comment]
Sure! I guess you're talking about http://fsprojects.github.io/.
Where do you think the docs can be added?
In the **FAQ**? e.g. *How to use Paket behind an internet proxy?*
In the **Documentation** section? (adding a topic *Internet Proxy support*)

**Comment by forki** [comment]
A faq entry would be a good start. Please also tell something about the
default behavior.

**Comment by dedale** [comment]
OK will do :-)

**Pull request merged**
