### PR TITLE
Fixes in Convert-from-nuget after ROP

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by theimowski** [comment]
looks good, I forgot we had the ``FindReferencesFile`` function

**Comment by forki** [comment]
also it seems https://github.com/fsprojects/Paket/pull/520/files#diff-8ae98470383c2c7af865300976ee41feR263 got lost.

**Comment by theimowski** [comment]
yeah, I assumed the default source should be in the APPDATA nuget.config; but that assumption may not always be correct

**Pull request merged**
