### PR TITLE
Automatic framework detection - references #1440

### PR DESCRIPTION
**Pull request by forki**
#### Automatic framework detection

If you use only one target framework in your whole repository, then paket can detect this for you and limit the installation to that specific target framework. You can control this in the [`paket.dependencies` file](dependencies-file.html):

    framework: auto-detect
    source https://nuget.org/api/v2

    nuget Example >= 2.0 // only the target framework that is used in projects

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
From Slack:
> probably it would be nice if it worked also if multiple frameworks are used in solution, giving conditionals for only those frameworks which are defined in any project

**Comment by forki** [comment]
@Krzysztof-Cieslak so we would install the union of all the target frameworks?

**Comment by Krzysztof-Cieslak** [comment]
Yes, so let's say we have in solution one project with 3.5 and second one with 4.0 - for all projects we define conditional references for both 3.5 and 4.0.

**Comment by forki** [comment]
sounds good

**Comment by forki** [comment]
If we don't find a project then we would not restrict the resolution, right?

**Comment by Krzysztof-Cieslak** [comment]
Yes, that sounds reasonable

**Pull request merged**
