### PR TITLE
Too many targets

### PR DESCRIPTION
**Pull request by 0x53A**

### CODE REVIEW

**Comment by 0x53A** [comment]
Can someone please tell me why my commit fails with 

``  InstallProcess.fs(167, 65): [FS0072] Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
  NuGetV2.fs(642, 22): [FS0001] This expression was expected to have type    'PackageName'    but here has type    ''a * 'b'``

but the following code works in fsi:

```F#

open System

[<System.Diagnostics.DebuggerDisplay("{ToString()}")>]
[<CustomEquality;CustomComparison>]
type PackageName =
| PackageName of string * string

    member this.GetCompareString() =
        match this with
        | PackageName(_,id) -> id

    override this.ToString() = 
        match this with
        | PackageName(name,_) -> name

    override this.Equals(that) = 
        match that with
        | :? PackageName as that -> this.GetCompareString() = that.GetCompareString()
        | _ -> false

    override this.GetHashCode() = hash (this.GetCompareString())

    interface System.IComparable with
       member this.CompareTo that = 
          match that with 
          | :? PackageName as that -> StringComparer.Ordinal.Compare(this.GetCompareString(), that.GetCompareString())
          | _ -> invalidArg "that" "cannot compare value of different types"

let GetTargetsFiles(targetFolder, (pkg : PackageName)) =
    let (PackageName(packageName, packageId)) = pkg
    0;;

```

## __?__ ``¯\_(ツ)_/¯``

**Comment by matthid** [comment]
Maybe we should do this in installmodel?

**Comment by 0x53A** [comment]
Feel free, I'm going to sleep. =)

**Comment by matthid** [comment]
;)

**Comment by 0x53A** [comment]
I made some changes in a file nugetv2.fs. Anything I additionally need to change for v3? @matthid

**Comment by matthid** [comment]
@0x53A  No I don't think so. The names are a bit confusing there... Could probably need some refactoring

**Pull request merged**
