### PR TITLE
generate-include-script should not #r FSharp.Core.dll

### LINKED ISSUE #1942: generate-include-script should not #r FSharp.Core.dll
### Description

If you depend on a package that depends on `FSharp.Core` package, the `generate-include-script` command should not generate `#r "...FSharp.Core.dll"

### Repro steps

Run `paket install` and `paket generate-include-scripts framework net45` for a `paket.depenencies` file containing:

```
source https://nuget.org/api/v2
nuget Suave
```

Then you should be able to run:

```
#load @"paket-files\include-scripts\net45\include.main.group.fsx"
```

### Expected behavior

Evaluating the `#load` command in FSI works.

### Actual behavior

You get an error:

> error FS1222: When mscorlib.dll or FSharp.Core.dll is explicitly referenced the --noframework option must also be passed

### Known workarounds

You can start your `fsi.exe with `--noframework` option, but I think we don't want to make people do this.

### PR DESCRIPTION
**Pull request by smoothdeveloper**
Add test case and fix implementation

Fixes #1942

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
@forki this PR failed to pass integration due to timeout on appveyor, do you have a way to run it again?

**Comment by forki** [comment]
I think easiest way is to push a new commit (which clean up or zero diff)

**Comment by forki** [comment]
thanks!

**Pull request merged**
