### PR TITLE
add FixNuspecs to public api

### PR DESCRIPTION
**Pull request by cloudRoutine**
- Add FixNuspecs as a method on `Dependencies`
- Change argu DU to accept a list and mark args as mandatory to simply implementation

### CODE REVIEW

**Comment by forki** [comment]
Breaking change?

**Comment by cloudRoutine** [comment]
the name is different

**Comment by forki** [comment]
Yes but was it already released? If so then can we create a function with old name that redirects to keep it stable?

**Comment by cloudRoutine** [comment]
I think you're the only one who's used it in
```
   <Exec Command='$(PaketCommand) fix-nuspec file "@(_NuspecFiles)" references-file "$(PaketReferencesFilePath)" ' />
```

**Comment by forki** [comment]
So this makes it everyone on core

**Comment by cloudRoutine** [comment]
don't the targets files get updated when paket gets updated?

**Comment by forki** [comment]
Nope. Only on install

**Comment by cloudRoutine** [comment]
maybe we should change that, I'll add the obsolete arg regardless

**Comment by forki** [comment]
Yes but even then people need to update the bootstrapper first.

**Comment by cloudRoutine** [comment]
checked to make sure, backwards compatibility still works

**Pull request merged**
