### PR TITLE
collect multiple install errors before failing

### PR DESCRIPTION
**Pull request by cloudRoutine**
Needing to run install several times in a row to get one successive error is a tedious chore, instead let's collect them and return them all at once.

### CODE REVIEW

**Comment by cloudRoutine** [comment]
@forki the last commit takes care of the bug I found yesterday.

**Comment by forki** [comment]
Cool thanks. Can you please send another pull request that adds this to the release notes? Thx

BTW next week I want to go rc or even release paket 4

**Comment by cloudRoutine** [comment]
@forki like this #2181 ?

**Comment by forki** [comment]
I meant an actual text entry with the feature description ;-)

Am 10.03.2017 01:49 schrieb "Jared Hester" <notifications@github.com>:

**Pull request merged**
