### PR TITLE
[Ready] Fix/refactor/improve framework restriction system, add performance metrics and pre-load requests

### PR DESCRIPTION
**Pull request by matthid**
start fixing #2317 because #2333 shows that its relevant.

Changes:
 - Remove all magic version strings
 - Restrictions can now be as complex as wanted - the simplifier almost always makes them look as "simple" as before
 - Changed Syntax in Lockfile from "Framework: " to "Restriction: " in order to be backwards compatible and allow new syntax (see below).
 - Restrictions now work nicely in combination with Portable profiles
 - Removed a various amount of hacks
 - Remove support for `V4_Client` -> if complains come up we need to find a general solution as `-client` and `-full` exists for all framework versions
 - Adds a performance overview.

TODO:
 - [x] Fix tests (part of https://github.com/fsprojects/Paket/pull/2356)
 - [x] Performance
 - [x] Lots of Json Exceptions seem to happen in the background...
 - [x] Write parser for the new syntax
 - [x] Is Syntax OK?

Example:
```
NUGET
  remote: https://www.nuget.org/api/v2
    CommonServiceLocator (1.3) - restriction: || (== sl5) (>= net40) (>= portable-net45+monoandroid+xamarinios+win8+wp8+wpa81)
    MvvmLightLibs (5.2)
      CommonServiceLocator (>= 1.0) - restriction: || (== net35) (== sl4)
      CommonServiceLocator (>= 1.3) - restriction: || (== sl5) (>= net40) (>= portable-net45+monoandroid+xamarinios+win8+wp8+wpa81)
```

The general syntax is 
 - `OP (operand1) (operand2) ...` for `||`, `NOT` and `&&` and
 - `OP tfm` for `==`, `>=` and `<`. 
 - `operandN` itself can be a operator again, for example `|| (&& (>= net3) (< net4)) (== sl4)`

Future Work:
 - Don't punish custom portables as hard (sometimes they need to be prefered. see http://nugettoolsdev.azurewebsites.net/4.0.0/get-nearest-framework?project=xamarinios10&package=portable-net45%2Bwin8%0D%0Aportable-net45%2Bmonoandroid10%2Bmonotouch10%2Bxamarinios10%2BXamarin.Mac20%0D%0Aportable-net40%2Bsl4%2Bwin8%2Bwp71%2Bwpa81%0D%0Aportable-net45%2Bwin8%0D%0Anet45%0D%0Anet40%0D%0Amonotouch%0D%0Awin8%0D%0Awpa81%0D%0Amonoandroid)
   I'm not doing that as part of this PR
   -> I'd suggest rewriting that "penalty" part from scratch

### CODE REVIEW

**Comment by forki** [comment]
You should be able to release this yourself with the release script that I
gave you for fake.

Am 13.05.2017 5:55 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by matthid** [comment]
I don't think I can finish this in the next days, it will be quite invasive in the code base (and remove so many hacks that it might hurt). These changes just show the direction it's going.... For now, I just demonstrate how the low-level code is currently broken (and quite a lot of code sits on top of this)

**Comment by matthid** [comment]
I think this is ready for review. Note that integration-tests probably need to be adapted, but I need some days break from this. If one of you wants to finish this let me know (like I said I think its just fixing the tests). Unittest-suite is green already. See my edited first post for more info.
/cc @cloudRoutine @forki

**Comment by forki** [comment]
files changed: 80 +2,601 −1,895 
ouch

**Comment by matthid** [comment]
I can try to merge and release tomorrow.

**Pull request merged**
