### PR TITLE
Update .NET & FSharp.Core Version

### PR DESCRIPTION
**Pull request by 1eyewonder**
Wanted to try to take a whack at this one which was mentioned in the Discord channel. I went ahead and updated the net core version up to 8 as well as updated FSharp.Core. I'm hoping this takes a bite of the elephant so I can go ahead and attempt at getting #4250 back on track

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
# Paket Lock Diff Report

This report was generated via [Paket Lock Diff](https://paket-lock-diff.azurewebsites.net/?olderLockFileUrl=https%3A%2F%2Fraw.githubusercontent.com%2Ffsprojects%2FPaket%2Fmaster%2Fpaket.lock&newerLockFileUrl=https%3A%2F%2Fraw.githubusercontent.com%2Ffsprojects%2FPaket%2F8703f608c7c59aebb73ad04be2386fd980faae2e%2Fpaket.lock)

## Additions - (0)

## Removals - (20)

* FSharpDepManagerExtension - (1)
  * [FSharp.Core - 5.0.0](https://www.fuget.org/packages/FSharp.Core/5.0.0/)

* Main - (19)
  * [Microsoft.Build.Framework - 16.7.0](https://www.fuget.org/packages/Microsoft.Build.Framework/16.7.0/)
  * [Microsoft.Build.Tasks.Core - 16.7.0](https://www.fuget.org/packages/Microsoft.Build.Tasks.Core/16.7.0/)
  * [Microsoft.Build.Utilities.Core - 16.7.0](https://www.fuget.org/packages/Microsoft.Build.Utilities.Core/16.7.0/)
  * [Microsoft.NETCore.App - 2.2.8](https://www.fuget.org/packages/Microsoft.NETCore.App/2.2.8/)
  * [Microsoft.NETCore.DotNetAppHost - 3.1.8](https://www.fuget.org/packages/Microsoft.NETCore.DotNetAppHost/3.1.8/)
  * [Microsoft.NETCore.DotNetHostPolicy - 3.1.8](https://www.fuget.org/packages/Microsoft.NETCore.DotNetHostPolicy/3.1.8/)
  * [Microsoft.NETCore.DotNetHostResolver - 3.1.8](https://www.fuget.org/packages/Microsoft.NETCore.DotNetHostResolver/3.1.8/)
  * [Microsoft.VisualStudio.Setup.Configuration.Interop - 1.16.30](https://www.fuget.org/packages/Microsoft.VisualStudio.Setup.Configuration.Interop/1.16.30/)
  * [runtime.native.System.Net.Security - 4.3.1](https://www.fuget.org/packages/runtime.native.System.Net.Security/4.3.1/)
  * [System.CodeDom - 4.7.0](https://www.fuget.org/packages/System.CodeDom/4.7.0/)
  * [System.Linq.Queryable - 4.3.0](https://www.fuget.org/packages/System.Linq.Queryable/4.3.0/)
  * [System.Net.Requests - 4.3.0](https://www.fuget.org/packages/System.Net.Requests/4.3.0/)
  * [System.Net.Security - 4.3.2](https://www.fuget.org/packages/System.Net.Security/4.3.2/)
  * [System.Net.WebHeaderCollection - 4.3.0](https://www.fuget.org/packages/System.Net.WebHeaderCollection/4.3.0/)
  * [System.Resources.Extensions - 4.7.1](https://www.fuget.org/packages/System.Resources.Extensions/4.7.1/)
  * [System.Runtime.Loader - 4.3.0](https://www.fuget.org/packages/System.Runtime.Loader/4.3.0/)
  * [System.Text.Encoding.CodePages - 4.7.1](https://www.fuget.org/packages/System.Text.Encoding.CodePages/4.7.1/)
  * [System.Threading.Tasks.Dataflow - 4.11.1](https://www.fuget.org/packages/System.Threading.Tasks.Dataflow/4.11.1/)
  * [System.Threading.Tasks.Parallel - 4.3.0](https://www.fuget.org/packages/System.Threading.Tasks.Parallel/4.3.0/)

## Version Upgrades - (7)

* Main - (7)
  * Major - (6)
    * [FSharp.Compiler.Service - 38.0.2 -> 43.8.400](https://www.fuget.org/packages/FSharp.Compiler.Service/43.8.400/lib/unknown/diff/38.0.2/)
    * [FSharp.Core - 6.0.3 -> 8.0.400](https://www.fuget.org/packages/FSharp.Core/8.0.400/lib/unknown/diff/6.0.3/)
    * [System.Collections.Immutable - 1.7.1 -> 8.0.0](https://www.fuget.org/packages/System.Collections.Immutable/8.0.0/lib/unknown/diff/1.7.1/)
    * [System.Diagnostics.DiagnosticSource - 5.0.1 -> 8.0.1](https://www.fuget.org/packages/System.Diagnostics.DiagnosticSource/8.0.1/lib/unknown/diff/5.0.1/)
    * [System.Reflection.Metadata - 1.8.1 -> 8.0.0](https://www.fuget.org/packages/System.Reflection.Metadata/8.0.0/lib/unknown/diff/1.8.1/)
    * [System.Runtime.CompilerServices.Unsafe - 5.0.0 -> 6.0.0](https://www.fuget.org/packages/System.Runtime.CompilerServices.Unsafe/6.0.0/lib/unknown/diff/5.0.0/)
  * Patch - (1)
    * [System.Memory - 4.5.4 -> 4.5.5](https://www.fuget.org/packages/System.Memory/4.5.5/lib/unknown/diff/4.5.4/)

## Version Downgrades - (0)

**Comment by 1eyewonder** [comment]
@forki I have a question on the ci/cd pipeline. I was looking through recent PRs which were merged and it looks like the tests were cancelled. I however have running tests with some failures. Should I treat this as I need to do more updates to get the tests passing or is this a separate issue related to the tests? I just want to make sure I'm not introducing any errors with these changes 😄

**Comment by Numpsy** [comment]
Looks to me like some of the those tests are already failing in cases where the pipeline doesn't hang/timeout - https://ci.appveyor.com/project/paket/paket/builds/50550293 (#4273 )

**Comment by Numpsy** [comment]
Anyway, it looks to me like the ```fcs can type check``` test is hanging with an error of the sort described in https://github.com/fsprojects/Paket/issues/4102 and this PR and the Chessie one both unstick it somehow (updated or removed dependencies I guess)

Removing some old deps in https://github.com/fsprojects/Paket/pull/4273 also unstuck it, though the test then failed in .NET Core (actually, I'm not sure what the direct Microsoft.Win32.Registry dependency is for - I don't immediately see any Registry access in the project)

**Comment by PatrickSchiefer** [comment]
Any chance to get this in a release soon? We have a problem with long path, which is solved when we switch to .net 8.0

**Comment by forki** [comment]
Thanks!

**Pull request merged**
