### PR TITLE
fix help for init command

### LINKED ISSUE #653: Paket init broken
```
PS C:\PAS\temp> .\Paket\tools\paket.exe init --help
Paket version 0.30.14.0
Paket failed with:
        UnionArgParser: template type inaccessible or not F# DU.
Parameter name: IArgParserTemplate
```
I'm not sure why - the code looks very similar to all the other commands. /cc @theimowski

### PR DESCRIPTION
**Pull request by theimowski**
fixes #653

### CODE REVIEW

**Comment by forki** [comment]
hehe. 20min from reported issue to fix. /cc @mavnn

**Comment by forki** [comment]
are there similar issues on other commands?

**Comment by theimowski** [comment]
What's the world record? ;)
Should not- init was special as it has no args practically

**Comment by mavnn** [comment]
20mins is pretty good :)

**Comment by mavnn** [comment]
![http://cinemak.tripod.com/speeeeeedy.gif][http://cinemak.tripod.com/speeeeeedy.gif] <- you forgot the gif though, so I'm not sure it counts.

**Pull request merged**
