### PR TITLE
Update to faster sets and maps in FSharp.Core 5.0

### PR DESCRIPTION
**Pull request by forki**
The Paket package resolution process relies heavily on sets. 

With FSharp.Core 5.0 we now have some performance improvements for sets and maps - so let's use them.

### CODE REVIEW

**Comment by forki** [comment]
Adding  nuget Nuget.Packaging 5.6 works.

group Build
   source https://api.nuget.org/v3/index.json
   nuget Fake.DotNet.Cli
   nuget Fake.IO.FileSystem
   nuget Fake.Core.Target
   nuget Nuget.Packaging 5.6

**Comment by forki** [comment]
@smoothdeveloper  I need your help here. I tried to upgrade all the things to netstandard2.1 but now a test complains:

  X fcs can type check  [3s 195ms]
  Error Message:
     Expected is <System.Object[0]>, actual is <FSharp.Compiler.SourceCodeServices.FSharpErrorInfo[6]>
  Values differ at index [0]
  Extra:    < <test.fsx (2,7)-(2,36) parse error Package manager key 'paket' was not registered in [C:\projects\paket\integrationtests\Paket.IntegrationTests\bin\Release\net461; C:\projects\paket\integrationtests\Paket.IntegrationTests\bin\Release\net461\], [C:\projects\paket\integrationtests\Paket.IntegrationTests\..\..\src\FSharp.DependencyManager.Paket\bin\Release\netstandard2.1]. Currently registered: >, <test.fsx (2,7)-(2,36) parse error Package manager key 'paket' was not registered in [C:\projects\paket\integrationtests\Paket.IntegrationTests\bin\Release\net461; C:\projects\paket\integrationtests\Paket.IntegrationTests\bin\Release\net461\], [C:\projects\paket\integrationtests\Paket.IntegrationTests\..\..\src\FSharp.DependencyManager.Paket\bin\Release\netstandard2.1]. Currently registered: >, <test.fsx (2,7)-(2,36) parse warning '' is not a valid assembly name>... >
  Stack Trace:
     at Paket.IntegrationTests.FsiExtension.fcs can type check () in C:\projects\paket\integrationtests\Paket.IntegrationTests\FsiExtension.fs:line 46


Do you know what's going wrong here?

**Comment by smoothdeveloper** [comment]
@forki can you try if adjusting this hardcoded "netstandard2.0" thing works:

https://github.com/fsprojects/Paket/blob/fc90013d093211018b8ab8ba09943f563847b37f/integrationtests/Paket.IntegrationTests/FsiExtension.fs#L16

**Comment by forki** [comment]
I already changed that to nestandard2.1

**Comment by smoothdeveloper** [comment]
Oh! the output folder for the project has changed for the release script, it is now under `bin` not `src`.

**Comment by forki** [comment]
any chance you could send a PR against my branch? I'm lost. also why is it working on travis?

**Comment by smoothdeveloper** [comment]
Checking the CI on #3922

**Comment by lcg-gauthier-segay** [comment]
The current paket FSI extension .dll in releases fails in VS, I assume because the version of fsharp.core used for compilation doesn't match the one that runs in VS.

For it to work out of the box in VS, it needs to reference the same FSharp.Core version as the nuget extension does.

#### potential fixes in this repository
* change target net461 in `Paket.IntegrationTests` project, maybe upgrading it to `net48` will allow it to load the netstandard2.0 assembly of the extension
* change how the extension is built so it uses specific version of FSharp.Core (in case this PR is still blocking, consider a separate build step).

#### Work around VS & FSharp.DependencyManager.Paket extension

For the extension to load in VS: compiling it from this repository with `dotnet build` using latest dotnet sdk instead of the one currently locked in the repository.

**Comment by forki** [comment]
@lcg-gauthier-segay @smoothdeveloper I think the problem with this pr is that I wanted to much in one step. Maybe you can try to just update the FSharp.Core in another PR and we keep this one for the next step when we want to go netstandard2.1

**Pull request closed without merging**
