### PR TITLE
Always try and extract Paket.Restore.targets even if up to date

### PR DESCRIPTION
**Pull request by BlythMeister**
Also add a log line to state that Paket.Restore.targets was saved

This means that even if your restore is up to date, it will get the latest Paket.Restore.targets to use

### CODE REVIEW

**Comment by BlythMeister** [comment]
@forki are these build failures mine, or pre-existing.  It is quite confusing 😕

**Comment by BlythMeister** [comment]
This is ready for review please.

**Comment by forki** [comment]
can you please merge with master?

**Comment by BlythMeister** [comment]
@forki done :)

**Comment by forki** [comment]
why is this needed?

**Comment by BlythMeister** [comment]
If paket is already up to date, it will not get you the latest restore targets.

This means when targets are updated, they only get downloaded (released) when paket has a need to download a dependency.

**Pull request merged**
