### PR TITLE
Add condition to AfterBuild target to unbreak nCrunch

### PR DESCRIPTION
**Pull request by thinkbeforecoding**
NCrunch doesn't run well with the target that is generated with some projects.
Adding a condition to the target disable it when running under ncrunch, avoiding to break compilation.

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
@thinkbeforecoding could you add a failing (without the change) integration test as well?

Thanks!

**Comment by forki** [comment]
there is actually already a broken test. so @thinkbeforecoding can you please try to fix that one?

**Comment by thinkbeforecoding** [comment]
I'm discovering the IntegrationTests so I'll try to see where it breaks

**Comment by forki** [comment]
I'm already on it

**Comment by thinkbeforecoding** [comment]
I think it's in a test where the condition has been added and the test verify equality with exising project. The project should then be updated.

**Pull request merged**
