### PR TITLE
Unify packaging strategy for Paket.Core

### PR DESCRIPTION
**Pull request by baronfel**
This MR 

* packs Paket.Core using the .net SDK integration instead of paket.template files
* removes custom assemblyinfo generation in favor of the automatic msbuild generation
* uses embedded Icons in the packages (as is the new hotness)
* enables sourcelink on every published artifact from this repo in the new way

I'll drop a before/after comparison of the current published nuget packages in a bit, but initial explorations via [the online nuget browser](https://nuget.info) have been very heartening!

### CODE REVIEW

**Comment by forki** [comment]
any ideas why build is red?

**Comment by baronfel** [comment]
@forki no idea really, it just seems to be the paket FSI integration. Will take a look.

**Comment by baronfel** [comment]
<details>
<summary>Paket.Core (before)</summary>

metadata and file layout

dependencies

> note that Nuget.Packaging is off in this release?

assembly attributes
</details>

<details>
<summary>Paket.Core (after)</summary>

metadata and file layout
> note the addition of the logo to the package, and the embedded PDBs now

dependencies

assembly attributes

</details>

I've included the built packages at this commit if you want to check them out:
[packages-for-this-commit.zip](https://github.com/fsprojects/Paket/files/7106592/packages-for-this-commit.zip)

**Comment by baronfel** [comment]
Closing the loop on that filling test and presenting detailed diffs of the two versions for all packed Nugets after this change. Hard finding time ATM, sorry :(

**Pull request merged**
