### PR TITLE
Use latest preview and fix appveyor build

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
/cc @enricosada 

    C:\Users\appveyor\.nuget\packages\fsharp.net.sdk\1.0.0-alpha-000001\build\netstandard1.0\FSharp.NET.Core.Sdk.targets(141,9): error MSB3073: The command "dotnet exec --depsfile C:\Users\appveyor\.nuget\packages\.tools\dotnet-compile-fsc\1.0.0-preview2-020000\netcoreapp1.0\dotnet-compile-fsc.deps.json --additionalprobingpath C:\Users\appveyor\.nuget\packages C:\Users\appveyor\.nuget\packages\dotnet-compile-fsc\1.0.0-preview2-020000\lib\netcoreapp1.0\dotnet-compile-fsc.dll @C:\projects\paket\src\Paket.Core\obj\Release\netstandard1.6\dotnet-compile.rsp" exited with code -2147450751. [C:\projects\paket\src\Paket.Core\Paket.Core.preview3.fsproj]

any ideas why that is failing?

**Comment by enricosada** [comment]
@forki you are using [preview4](https://ci.appveyor.com/project/SteffenForkmann/paket/build/0.0.1.7154#L159). 
try to use `preview3` instead, and pin to `1.0.0-preview3-004056`

**Comment by forki** [comment]
doesn't seem to work

**Comment by enricosada** [comment]
ok so, let me see 😄 
let's compare with [preview3 templates](https://github.com/dotnet/netcorecli-fsc/tree/master/examples/preview3/lib):

```
C:\projects\paket\dotnetcore\sdk\1.0.0-preview3-004056\NuGet.targets(70,5): warning : Dependency specified was Microsoft.NET.Sdk (>= 1.0.0-alpha-20161029-1) but ended up with Microsoft.NET.Sdk 1.0.0-alpha-20161104-2. [C:\projects\paket\src\Paket.Core\Paket.Core.preview3.fsproj]
```

- use `Microsoft.NET.Sdk` version `1.0.0-alpha-20161104-2`
- for `FSharp.NET.Sdk` use `1.0.0-alpha-*`  (or if you want to pin `1.0.0-alpha-000007`, see nuget org https://www.nuget.org/packages/FSharp.NET.Sdk/1.0.0-alpha-000007 i am going to publish updates directly there)

if doesnt work after that, i'll clone this pr locally and fix it

**Comment by forki** [comment]
now it's completely strange message... urgs

**Comment by enricosada** [comment]
see https://ci.appveyor.com/project/SteffenForkmann/paket/build/0.0.1.7157#L195

```
MSBUILD : error MSB4025: The project file could not be loaded. The 'Version' start tag on line 27 position 8 does not match the end tag of 'PackageReference'. Line 29, position 7. [C:\projects\paket\src\Paket\Paket.preview3.fsproj]
```

@forki you replaced wrongly the xml

```xml
<Version>1.0.0-alpha-20161104-2/Version>
```

the `<` is missing from `</Version>`

**Comment by forki** [comment]
yep. sorry. now we're back to the beginning ;-)

**Comment by enricosada** [comment]
@forki remove the dev feeds

```
https://www.myget.org/F/nuget-volatile/api/v3/index.
https://www.myget.org/F/netcorecli-fsc-preview3/api/v3/index.json
```

`preview3` is released, we should use only nuget.org

**Comment by enricosada** [comment]
anyway i'll try to build this locally tonight, if doesnt work

**Comment by forki** [comment]
don't think that's it. Paket4 is providing it's own NuGet.Config

**Comment by enricosada** [comment]
@forki i think is a bug of my f# integration.

sry locally i cannot repro, but [this error](https://ci.appveyor.com/project/SteffenForkmann/paket/build/0.0.1.7164#L275)

```
dotnet exec --depsfile C:\Users\appveyor\.nuget\packages\.tools/dotnet-compile-fsc/1.0.0-preview2-020000/netcoreapp1.0/dotnet-compile-fsc.deps.json --additionalprobingpath C:\Users\appveyor\.nuget\packages C:\Users\appveyor\.nuget\packages\dotnet-compile-fsc/1.0.0-preview2-020000/lib/netcoreapp1.0/dotnet-compile-fsc.dll @C:\projects\paket\src\Paket.Core\obj\Release\netstandard1.6\dotnet-compile.rsp
         The specified deps.json [C:\Users\appveyor\.nuget\packages\.tools\dotnet-compile-fsc\1.0.0-preview2-020000\netcoreapp1.0\dotnet-compile-fsc.deps.json] does not exist
```

is the same as [the netcorecli-fsc ci server build](https://ci2.dot.net/job/dotnet_netcorecli-fsc/job/master/job/debug_windows_nt_x86_prtest/7/console)

I was thinking the missing `deps` was an xplat issue as reported in https://github.com/dotnet/netcorecli-fsc/issues/41 but is also on windows.
I'll fix that tonight anyway. is a bug

**Comment by forki** [comment]
Cool. Thanks buddy

Am 21.11.2016 18:56 schrieb "Enrico Sada" <notifications@github.com>:

**Comment by enricosada** [comment]
@forki rerun the build pls, i published another `FSharp.NET.Sdk` package

**Comment by forki** [comment]
still same issue

**Comment by enricosada** [comment]
ok, let's stop appveyor driven development so

time for `hub checkout https://github.com/fsprojects/Paket/pull/2032` 😄

**Comment by enricosada** [comment]
ok found the issue: it's because you have two fsproj in same directory.

```
dotnet compile-fsc
Specify which project file to use because this 'e:\github\Paket\src\Paket.Core' contains more than one project file.
```

it's because i use `dotnet compile-fsc` , but dotnet find two fsproj in same directory ( `Paket.Core.fsproj` and `Paket.Core.preview3.fsproj` ) and doesnt know which one to use for tool `dotnet-compile-fsc`

i'll try to fix it

**Comment by enricosada** [comment]
nope, added dotnet/netcorecli-fsc#47 as bug. Good catch @forki !

@forki i send a pr #2036 to fix the build with a workaround. that's my only idea to move forward now.
locally build ok.

**Comment by enricosada** [comment]
@forki i added some info about how to fix the build failure after my pr is merged, it's a problem with FAKE script, see https://github.com/fsprojects/Paket/pull/2036#issuecomment-262305530

i think is enough to `Environment.SetEnvironmentVariable` of current process.

**Comment by forki** [comment]
thanks. next step would be to make it work on travis. and the dotnet pack stuff

**Comment by enricosada** [comment]
@forki yes, i think the install of sdk if wrong on travis.
```
Installing 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-004056/dotnet-dev-win-x64.1.0.0-preview3-004056.zip' to '/home/travis/build/fsprojects/Paket/dotnetcore/dotnet-dev-win-x64.1.0.0-preview3-004056.zip
```

that's the url for windows. try `dotnet-dev-ubuntu.14.04-x64.#{dotnet_version}.tar.gz`

**Comment by enricosada** [comment]
@forki about pack just try it (appveyor driven dev 😄 ), if doesnt work i'll fix that but should work ok if project is netcore only.

**Comment by Alaiven** [comment]
@enricosada current code will not unpack tar.gz file:

`System.IO.Compression.ZipFile.ExtractToDirectory(localPath, dotnetCliPath.FullName)`

**Comment by enricosada** [comment]
good catch @Alaiven 

lets invoke `tar xf` meanwhile as workaround? like in suave https://github.com/SuaveIO/suave/blob/956af39393e7dfe2cf5288fb352098c802b09cf9/Rakefile#L119-L139

**Comment by forki** [comment]
@Alaiven can you please end a PR? thanks

**Comment by Alaiven** [comment]
@forki What do you mean? I'm new to github

**Comment by enricosada** [comment]
@Alaiven he is asking if you want to contribute making the fix yourself, and send as pull request so can be included in this project.
Basically fork this repository, create a branch with the changes to fix the issue and create a pull request. see https://guides.github.com/activities/forking/
if you need help just join the [paket chat on gitter](https://gitter.im/fsprojects/Paket) for helps

**Pull request merged**
