### PR TITLE
fix convert-from-nuget

### PR DESCRIPTION
**Pull request by pms1969**
found the reason the packages.configs weren't being changed to paket.references in the project files.

seems I inadvertently changed a line during one of my commits. :-s

### CODE REVIEW

**Comment by forki** [comment]
I'd love to see a mini integration test to nail this one down. Can you please give it a try?

**Comment by pms1969** [comment]
sure, might have to wait till later tonight

**Comment by pms1969** [comment]
done

**Comment by forki** [comment]
Ah so we already had test data but an assertion was missing? 

Thanks

**Comment by pms1969** [comment]
yes. 

no probs

**Comment by forki** [comment]
thx

**Pull request merged**
