### PR TITLE
Add props from root build folders

### PR DESCRIPTION
**Pull request by bengobeil**
#3816 

Props and target files were not added to project files if they were found in the root of build, buildTransitive or buildMultiTargeting folders.

### CODE REVIEW

**Comment by forki** [comment]
is that something that should go to paket 5? then please target `bugfix` branch

**Comment by bengobeil** [comment]
Yes I will add it to paket 5. ALl tests pass on my machine but some fail on AppVeyor. Not sure how to diagnose

**Comment by forki** [comment]
let's try to rerun

**Comment by bengobeil** [comment]
Actually I was not running the RunIntegrationTestDotnetCore target. Trying it on my machine

**Comment by bengobeil** [comment]
Yeah it also fails on my PC

**Comment by bengobeil** [comment]
Should be fixed now. So Ishould merge this in paket 6 and paket 5?

**Comment by forki** [comment]
thank you

**Pull request merged**
