### PR TITLE
Fixes #2390

### LINKED ISSUE #2390: Cleanup recent changes.
### Description

- Fixup https://github.com/fsprojects/Paket/pull/2388 and move this logic to the installmodel.
- At this time filter the xml stuff 
- ~~See if we can report part of https://github.com/fsprojects/Paket/pull/2379 without trace.~~

### PR DESCRIPTION
**Pull request by matthid**
https://github.com/fsprojects/Paket/issues/2390
https://github.com/fsprojects/Paket/issues/2360
https://github.com/fsprojects/Paket/pull/2388

### CODE REVIEW

**Comment by matthid** [comment]
This is harder than I thought... Problem is that the `xml` files actually improved the results. They were ignored by the compiler and allowed the installmodel to consider empty folders... We need to consider empty folders in the installmodel.

**Comment by matthid** [comment]
One more thing I noticed: When we add `System.Net.Http` and compile for net45 the framework reference is missing

**Comment by matthid** [comment]
I don't think it is related to this PR, but I can reproduce locally as well:

```
4) Error : Paket.IntegrationTests.UpdatePackageSpecs.#1432 update doesn't throw Stackoverflow
System.Exception : Paket failed with:
-> There was a version conflict during package resolution.
     Resolved packages:
      - Paket.Test.B 1.0.0
      - Paket.Test.C 1.0.0-prerelease
      - Paket.Test.D 1.0.0-prerelease
     Conflict detected:
      - Paket.Test.B 1.0.0 requested package Paket.Test.A: >= 0 (no prereleases)
      - Paket.Test.C 1.0.0-prerelease requested package Paket.Test.A: >= 0.0.0-prerelease
```

Probably related to the latest prerelease changes. I have no idea why it doesn't fail on AppVeyor.
@forki Do you see this failure when you run the integration test locally? With this PR or on master?

**Comment by 0x53A** [comment]
I'm not forki, but have also seen a weird behaviour wrt to the tests and prereleases.

master:
image

at commit f679d39:

image

-----------

Is there a random element to the resolving, e.g. could it affect the algorithm whether a package is already locally in the cache (so getting it's information is fast) or not?

**Comment by matthid** [comment]
@0x53A Thanks for testing this. Yes I think we prefer the cache. So if other tests depend on the same packages with different contents that might explain it. Will take a deep look tomorrow...

**Comment by matthid** [comment]
OK root cause seems to be
```
-> IOException: The process cannot access the file 'C:\Users\matth\AppData\Local\Temp\Paket.Test.A.nuspec' because it is being used by another process.
```

However I'm not sure where we miss to cleanup that handle. And it only happens occasionally, something like one out of 10 runs is failing. 

So maybe this is related to this PR after all because I introduced an additional place where the nuspec is read (the `GetContent` method).

**Pull request merged**
