### PR TITLE
removing transitive dependencies from dependencies list

### PR DESCRIPTION
**Pull request by pms1969**
brings the dependency list in line with exactly what nuget produces (as far as I can tell).

### CODE REVIEW

**Comment by forki** [comment]
Do we really want that? Is it needed?

**Comment by forki** [comment]
(I mean probably want that - but what are we breaking currrently?)

**Comment by pms1969** [comment]
I guess it's more of a completeness thing than anything else.  it declutters the output, and makes the dependency list that is generated by paket the same as nuget.

in a project of any size, (and I have a few at work), the depency list is relatively large.  a good chuck of these dependencies are transitive.  it leads to larger lock files I guess, and I need to justify the difference to the people I work under ;-)

**Comment by forki** [comment]
ok will look into it

**Comment by forki** [comment]
Could you please review b014e55 and 11a4308? Thanks

**Comment by pms1969** [comment]
all looks good.  just ran trunk against my solution here, and it worked as expected.

**Comment by forki** [comment]
Do we influence the packaged dlls with it? I mean for packages that don't use dependencies but bundle their stuff we still need to package all deps. Otherwise that would create a bug right?

**Comment by pms1969** [comment]
that code just has an impact on the dependencies list, not on the packaged dlls

**Pull request merged**
