### PR TITLE
updated to .net core sdk preview4

### PR DESCRIPTION
**Pull request by enricosada**
- use .net core sdk preview4
- fix `dotnet pack`
- fix merge package with `dotnet mergenupkg`

### CODE REVIEW

**Comment by enricosada** [comment]
@forki doing `dotnet pack` doesnt work right because doesnt consider the paket package references.

I can think some solutions, but depends on what you wanna do

1. ignore `dotnet pack`, use another paket command instead
2. hook inside `dotnet pack`, maybe just overriding `_GetPackageReferences` target 
3. pass a generated nuspec to `dotnet pack`

**Comment by forki** [comment]
But it should use all deps, right? Maybe we need to do the same trick as in restore.

**Comment by enricosada** [comment]
@forki let me fix travis meanwhile we discuss..

**Comment by enricosada** [comment]
Probably is easier.. the `dotnet pack` generate the Item `_PackageReferences` with `_GetPackageReferences`

```xml
  <!--
    ============================================================
    _GetPackageReferences
    Entry point for getting the package references for a project and it's references
    ============================================================
  -->
  <Target Name="_GetPackageReferences"
      Condition="$(TargetFramework) != ''"
      Returns="@(_PackageReferences)">

    <!-- Project to project entry -->
    <ItemGroup>
      <_PackageReferences Include="%(PackageReference.Identity)">
        <TargetFramework>$(TargetFramework)</TargetFramework>
        <IncludeAssets>%(PackageReference.IncludeAssets)</IncludeAssets>
        <ExcludeAssets>%(PackageReference.ExcludeAssets)</ExcludeAssets>
        <PrivateAssets>%(PackageReference.PrivateAssets)</PrivateAssets>
        <Version>%(PackageReference.Version)</Version>
      </_PackageReferences>
    </ItemGroup>
  </Target>
```

So i think the trick is JUST override that target maybe? if import order is correct should work, what do you think @theimowski ?

**Comment by enricosada** [comment]
depends on what you wanna do. replace completly the nuspec, or just fix the package references.. dunno..

**Comment by enricosada** [comment]
@forki @theimowski i have done your trick with dd35fb9
, but is not perfect.

Generated deps are ok minus `FSharp.NET.Sdk` who is added and shouldnt..

```xml
      <group targetFramework=".NETStandard1.6">
        <dependency id="FSharp.NET.Sdk" version="1.0.0-beta-" exclude="Build,Analyzers" />
        <dependency id="Newtonsoft.Json" version="9.0.1" exclude="Build,Analyzers" />
        <dependency id="FSharp.Core" version="4.0.1.7-alpha" exclude="Build,Analyzers" />
        <dependency id="Mono.Cecil" version="0.10.0-beta1-v2" exclude="Build,Analyzers" />
        <dependency id="Chessie" version="0.6.0" exclude="Build,Analyzers" />
       ....
````

**Comment by enricosada** [comment]
ok seems the ` <dependency id="FSharp.NET.Sdk" version="1.0.0-beta-" exclude="Build,Analyzers" />` (not the `beta-` without `*`) is added BEFORE this new target, so is added by normal nuget pack targets?

**Comment by cloudRoutine** [comment]
@enricosada isn't `dotnet pack` the only way to build for multiple framework targets with one command?

**Comment by enricosada** [comment]
@cloudRoutine you can `dotnet build` (and will build every target fw)

**Comment by cloudRoutine** [comment]
whenever i use `dotnet build` it builds `<TargetFramework>` not everything in `<TargetFrameworks>`

**Comment by enricosada** [comment]
@cloudRoutine probably is a bug in `FSharp.NET.Sdk`, i'll check later

**Comment by enricosada** [comment]
@forki i think build errors are unrelated to this PR

**Comment by enricosada** [comment]
@forki the PR is green:

- i cherry-picked a commit from `master` branch to disable a flacky test
- i disabled a test in ebe9da3, who was failing with a SO exception. But i dont think is related.

 There is an issue with `dotnet pack` who add `FSharp.NET.Sdk` and shouldnt. but the rest seems ok.
travis fixed with netcore too

**Comment by forki** [comment]
cool stuff. thanks buddy

**Pull request merged**
