### PR TITLE
Implement isMatchingOperatingSystem

### PR DESCRIPTION
**Pull request by kerams**
Thoughts on this? I decided to force the caller to provide the OS in order to make the function easily testable.
#1355

### CODE REVIEW

**Comment by forki** [comment]
This looks like a good start. Now we need the part that detects the OS. We already have a isMono function, but we need more...

**Comment by forki** [comment]
please take a look at https://github.com/fsprojects/Paket/pull/1366

**Comment by kerams** [comment]
I thought that `Environment.OSVersion.Platform` would be enough.

**Comment by forki** [comment]
yes that's what I used now.

**Comment by forki** [comment]
thanks a lot!

**Comment by kerams** [comment]
It might not be that simple after all :). http://stackoverflow.com/questions/10138040/how-to-detect-properly-windows-linux-mac-operating-systems

**Comment by forki** [comment]
Please take a look at the referenced pull request. We already have a couple
of platform helpers there. Maybe you can make use of these as well.

**Pull request merged**
