### PR TITLE
rework github strategy to use a more direct method in the common case…

### PR DESCRIPTION
**Pull request by baronfel**
… of just getting the latest version

### CODE REVIEW

**Comment by baronfel** [comment]
TODO:  pagination on the prerelease-case

**Comment by forki** [comment]
I think there should be no pagination on the prerelease case. If there is no prerelease on the first page then there is no active prerelease.

**Comment by baronfel** [comment]
ah, and the prerelease logic is really 'latest including prerelease', so we're really just grabbing the first of the 'all releases' page then?  that makes that logic simpler as well.

**Comment by forki** [comment]
Yes we only want the super latest and greatest (and broken) version.

**Comment by baronfel** [comment]
Alright, all better.

**Comment by forki** [comment]
thanks!

**Comment by forki** [comment]
sorry. I messed up.

The new bootstrapper doesn't work on prerelease case. It should always get the latest version, but github shows the last released version on top (even if that's older than the latest)

**Comment by baronfel** [comment]
sounds like we should always get the latest version via the new mechanism, then, and then use that version to compare against if the user requests a prerelease?

so /releases/latest => 1.99.0
then use 1.99.0 to compare against
/releases =>
   1.99.0
   2.0.0--alpha1million

?

**Pull request merged**
