### PR TITLE
do not export the MSBuild env-var to the outer shell

### PR DESCRIPTION
**Pull request by 0x53A**
fixes https://github.com/fsprojects/Paket/issues/2751

/cc @vbfox, sorry about that.

Please review by someone who knows more about batch than me.

### CODE REVIEW

**Comment by vbfox** [comment]
Nice.

Windows version looks 👍 to me, you don't need `endlocal` btw the end of the script does the same.

About the bash version, bash support setting env variables for only one command:

`VAR=value cmd args`

**Comment by 0x53A** [comment]
> you don't need endlocal btw the end of the script does the same.

but it doesn't hurt, right?

> bash support setting env variables for only one command:

done. but this is only in the windows branch of the bash script, so I doubt anyone even triggers this codepath.

(the bundled msbuild crashes hard on linux, so the mono msbuild is still used)

Thanks!

**Comment by vbfox** [comment]
> but it doesn't hurt, right?

No, it just restore the env explicitly instead of implicitly.

**Comment by matthid** [comment]
0x53A the windows code path is for me ;)
I'm using git bash ever since as I don't like cmd or powershell ;)

**Comment by 0x53A** [comment]
> I don't like cmd or powershell ;)

I can't understand that at all.

**Comment by 0x53A** [comment]
@matthid I think this is ready, unless you or @vbfox have any additional feedback.

**Pull request merged**
