### PR TITLE
Use AES encryption when not on windows

### PR DESCRIPTION
**Pull request by bengobeil**
When not on windows, instead of using Data Protection API, use AES encryption.

### CODE REVIEW

**Comment by bengobeil** [comment]
Fixes issue #3768

**Comment by forki** [comment]
Is this backwards compatible? I assume it is, but are windows users forced to reenter their passwords?

**Comment by bengobeil** [comment]
Its backwards compatible. If its on windows we will use DPApi. Else, use AES. That means if it worked before on windows, you will not have to re-enter

**Comment by forki** [comment]
do you think this should go to paket 5.x as well? then pleae feel free to send a similar PR that targets  `bugfix` branch.
Thanks!

**Comment by bengobeil** [comment]
OK will do

**Pull request merged**
