### PR TITLE
paket.lock beautification for HTTP specs 

### PR DESCRIPTION
**Pull request by sergey-tihon**
#553
`paket.references`:
```fsharp
http http://www.frijters.net/ikvmbin-8.0.5449.0.zip
http http://nlp.stanford.edu/software/stanford-corenlp-full-2014-10-31.zip
http http://nlp.stanford.edu/software/stanford-ner-2014-10-26.zip
http http://nlp.stanford.edu/software/stanford-parser-full-2014-10-31.zip
http http://nlp.stanford.edu/software/stanford-postagger-full-2014-10-26.zip
http http://nlp.stanford.edu/software/stanford-segmenter-2014-10-26.zip
```
Old `paket.lock`:
```fsharp
HTTP
  remote: http://www.frijters.net/ikvmbin-8.0.5449.0.zip
  specs:
    ikvmbin-8.0.5449.0.zip
  remote: http://nlp.stanford.edu/software/stanford-corenlp-full-2014-10-31.zip
  specs:
    stanford-corenlp-full-2014-10-31.zip
  remote: http://nlp.stanford.edu/software/stanford-ner-2014-10-26.zip
  specs:
    stanford-ner-2014-10-26.zip
  remote: http://nlp.stanford.edu/software/stanford-parser-full-2014-10-31.zip
  specs:
    stanford-parser-full-2014-10-31.zip
  remote: http://nlp.stanford.edu/software/stanford-postagger-full-2014-10-26.zip
  specs:
    stanford-postagger-full-2014-10-26.zip
  remote: http://nlp.stanford.edu/software/stanford-segmenter-2014-10-26.zip
  specs:
    stanford-segmenter-2014-10-26.zip
```
New `paket.lock`:
```fsharp
HTTP
  remote: http://www.frijters.net
  specs:
    ikvmbin-8.0.5449.0.zip (/ikvmbin-8.0.5449.0.zip)
  remote: http://nlp.stanford.edu
  specs:
    stanford-corenlp-full-2014-10-31.zip (/software/stanford-corenlp-full-2014-10-31.zip)
    stanford-ner-2014-10-26.zip (/software/stanford-ner-2014-10-26.zip)
    stanford-parser-full-2014-10-31.zip (/software/stanford-parser-full-2014-10-31.zip)
    stanford-postagger-full-2014-10-26.zip (/software/stanford-postagger-full-2014-10-26.zip)
    stanford-segmenter-2014-10-26.zip (/software/stanford-segmenter-2014-10-26.zip)
```

### CODE REVIEW

**Comment by sergey-tihon** [comment]
This PR is definitely need review

**Comment by forki** [comment]
thanks dude, I'll check it out

**Comment by forki** [comment]
please test 0.26 alpha versions

**Comment by sergey-tihon** [comment]
I works in all my cases

**Comment by JonCanning** [comment]
This isn't working for me, I'm referencing a raw gist. The bracket gets included in the folder structure, and the structure seems to be duplicated within that.

**Comment by forki** [comment]
can you please gieve mini repro so that we can fix it.

**Comment by JonCanning** [comment]
http https://gist.githubusercontent.com/JonCanning/37769e635aaece6dcef3/raw/adffa54dd02f94e5b06667700ef44e1a5feded73/paket.txt paket.txt

If I remove the file extension from the link it works

**Comment by forki** [comment]
@sergey-tihon can you try to fix this?

**Comment by forki** [comment]
I tried the following:

`paket.dependencies`:

    http https://gist.githubusercontent.com/JonCanning/37769e635aaece6dcef3/raw/adffa54dd02f94e5b06667700ef44e1a5feded73/paket.txt

`paket.references`:

    File:paket.txt .

running `paket update` gives `paket.lock`:

    HTTP
      remote: https://gist.githubusercontent.com
      specs:
        paket.txt (/JonCanning/37769e635aaece6dcef3/raw/adffa54dd02f94e5b06667700ef44e1a5feded73/paket.txt)

and fsproj-file got:

        <Content Include="..\..\paket-files\gist.githubusercontent.com\paket.txt">
          <Paket>True</Paket>
          <Link>paket.txt</Link>
        </Content>

LGTM

**Comment by JonCanning** [comment]
It's when you specify a filename after the url that it goes wrong

**Comment by forki** [comment]
but do we support that? http://fsprojects.github.io/Paket/http-dependencies.html

what should it do?

**Comment by JonCanning** [comment]
I was looking at the example here:

http://fsprojects.github.io/Paket/dependencies-file.html

I assumed that it would allow me to call the file something different locally

**Comment by forki** [comment]
1) Ouch. I have to test if this still works. Thanks for reporting.
2) I think this would be a new feature request. I think it makes sense.

**Comment by sergey-tihon** [comment]
As I know we support it for services that does not have file name in url, like `www.fssnip.net`
https://github.com/fsprojects/Paket/blob/master/tests/Paket.Tests/DependenciesFile/ParserSpecs.fs#L276-L277

I cannot reproduce it even with new file name. =(
`paket.dependencies`:
```
http https://gist.githubusercontent.com/JonCanning/37769e635aaece6dcef3/raw/adffa54dd02f94e5b06667700ef44e1a5feded73/paket.txt paket.txt
```
`paket.lock`:
```
HTTP
  remote: https://gist.githubusercontent.com
  specs:
    paket.txt (/JonCanning/37769e635aaece6dcef3/raw/adffa54dd02f94e5b06667700ef44e1a5feded73/paket.txt)
```

File structure:
image

**Comment by JonCanning** [comment]
Ah, it seems to be paket install that does it

**Comment by forki** [comment]
install doesn't work with http depenencies at the moment - https://github.com/fsprojects/Paket/issues/532

you have to run update. Subsequent installs will work.

**Comment by JonCanning** [comment]
It's the subsequent install that creates the mangled path

**Comment by forki** [comment]
woupsi. I can reproduce this.

@sergey-tihon: just try install after update and it will fail.

**Comment by forki** [comment]
HTTP
      remote: https://gist.githubusercontent.com
      specs:
        paket.txt (/JonCanning/37769e635aaece6dcef3/raw/adffa54dd02f94e5b06667700ef44e1a5feded73/paket.txt)

looks like the serialization to the lockfile is broken

**Comment by forki** [comment]
sorry about playing pingpong here. could you please test with 0.27.0-alpha006?

**Comment by JonCanning** [comment]
update writes:

<Content Include="paket-files\gist.githubusercontent.com\paket.txt">

subsequent install writes:

<Content Include="paket-files\gist.githubusercontent.com\gist.githubusercontent.com\paket.txt">

and a duplicate appears in paket-files along with a paket.dependencies which contains the html for the github gist page!?

**Comment by forki** [comment]
thanks I think this in 0.27.0-alpha007.

**Comment by JonCanning** [comment]
That's better, still got the dependencies file appearing on install, is that a problem?

**Comment by forki** [comment]
what do you mean?

**Comment by JonCanning** [comment]
The subsequent install creates a paket.dependencies file next to the paket.txt file

**Comment by forki** [comment]
that's actualy not bad, but I will check why this happens in this case

**Comment by forki** [comment]
oh I take that back. The dependencies file contains content (strange html). so it's probably created because the server doesn't throw 404 on the resource. funny

will investigate

**Comment by forki** [comment]
thanks for reporting this stuff. that's very valuable.
I pushed a new prerelease.

**Comment by JonCanning** [comment]
That's working for me, thanks

**Pull request merged**
