### PR TITLE
Chocolatey support for Paket.PowerShell

### PR DESCRIPTION
**Pull request by ctaggart**
Testing locally can be done like so:
```
choco install Paket.PowerShell -s C:\Projects\Paket\temp --pre -y --force
```
Installing from NuGet can be done like so:
```
choco install Paket.PowerShell -s http://www.nuget.org/api/v2 -y
```
Once it is uploaded to or mirrored on Chocolatey, then just this will work:
```
choco install Paket.PowerShell -y
```

### CODE REVIEW

**Comment by forki** [comment]
Should we push this to chocolatey during the build?

**Comment by ctaggart** [comment]
I think so. That is what I [do for SourceLink.exe](https://github.com/ctaggart/SourceLink/blob/master/build.fsx#L168-L190). You could also do that same for paket.

**Comment by forki** [comment]
cool. It's uploaded to https://chocolatey.org/packages/Paket.PowerShell/1.14.0, but await moderator approval.

**Comment by forki** [comment]
I'm pretty sure Paket's release cycle will annoy the hell out of the choco guys.

**Comment by alexeyzimarev** [comment]
After the installation, it cannot be used in the PS console, like path is not added.

**Comment by ctaggart** [comment]
@alexeyzimarev Are you trying to use it from the `Package Manager Console` in Visual Studio? Are you able to use it from normal PowerShell? It worked for me with this simple test:

image

Did the path get added correctly to the `PSModulePath`?
```
(Get-Item Env:\PSModulePath).Value -Split ';'
```
image

The `PSModulePath` allows the module to be imported on demand. If that is not working, are you ale to import it manually?
image

**Comment by ctaggart** [comment]
@alexeyzimarev It looks like some output doesn't show up. Is that what you mean? I logged this bug and will look into it.
https://github.com/fsprojects/Paket/issues/874

**Comment by alexeyzimarev** [comment]
No, for me it was just saying that "Paket" is not a valid command. I tried from the PS shell. Will check the path later.

**Comment by alexeyzimarev** [comment]
This is what I got after cinst

PS D:\GitHub\Paket.VisualStudio> (Get-Item Env:\PSModulePath).Value -Split ';'
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\

**Comment by alexeyzimarev** [comment]
Import gives this:

**Comment by ctaggart** [comment]
Hi @alexeyzimarev, I'm not sure why you get that error message. Can you provide the output of these commands?
```
$PSVersionTable
choco --version
choco list --localonly
Get-FileHash C:\ProgramData\chocolatey\lib\Paket.PowerShell\tools\Paket.PowerShell\Paket.PowerShell.dll -Algorithm SHA1 | fl
```

image

Unless I coded something wrong, `C:\ProgramData\chocolatey\lib\Paket.PowerShell\tools` should get added to your `$PSModulePath`. I've tested it on a couple of computers. Start a new PowerShell session after installing.
* https://github.com/fsprojects/Paket/blob/master/src/Paket.PowerShell/Install-PSModulePath.ps1
* https://github.com/chocolatey/choco/pull/327

**Comment by ferventcoder** [comment]
@alexeyzimarev did you close and reopen your shell?

**Comment by ferventcoder** [comment]
So forcing the import worked for me.

image

**Comment by ferventcoder** [comment]
I did notice that you are adding a bunch of unapproved verbs, which might be why it didn't automatically import?

**Comment by ferventcoder** [comment]
This might be helpful as well.

image

**Comment by ferventcoder** [comment]
Dumb question. Does a module automatically load without a psd1/psm1 file?

**Comment by ferventcoder** [comment]
Actually the dumbest possibility, did you need the trailing back slash at the end of your custom module path?

**Comment by ctaggart** [comment]
@ferventcoder There is not `Paket` command. If you open a new PowerShell instance and type `Paket-` or just `pak` **and hit tab**, do you see a list? PowerShell will import it as soon as your try running one of them. If so, the `$env:psmodulepath` is doing its job. I've now tried successfully on 3 computers.

**Comment by ferventcoder** [comment]
I didn't, but this may be helpful

WMF 5 by the way. I added the trailing back slash and 
image

**Comment by ferventcoder** [comment]
Seems to work without the trailing backslash as well. With `Paket- {tab}`

**Comment by ferventcoder** [comment]
so should be good to approve. :)

**Comment by ferventcoder** [comment]
Approved. 

With the project owners building the package, we move things to a trusted status after a few good approvals @forki.

**Comment by ctaggart** [comment]
Awesome! Thank you! Sometime this week, I hope to get a blog about how I used F# + Chocolatey + PowerShell. :-)

**Comment by ferventcoder** [comment]
:)

**Pull request merged**
