### PR TITLE
Fixes 3352 - copy local has no effect when opening project in vs2017

### PR DESCRIPTION
**Pull request by atlemann**
Fixes: #3352 

Setting `<ExcludeAssets>runtime</ExcludeAssets>` in the `.paket.props` file for packages with `copy_local: false` to avoid VS2017 changing the `props.assets.json` when loading the project.

Tweaked the result of combining copy_local flags from lock and references file:
- Setting only `copy_local: true` returns `Some true` which results in `PrivateAssets=All`
- Combinations of `copy_local: true` and `copy_local: false` results in either `Some false` or `None` which results in either `ExcludeAssets=runtime` or no flags at all.

Moved the `copy_local` setting to element 5 in the `.paket.resolved` file in the `obj` folder and updated `paket.Restore.targets` to read the 5th element instead.

### CODE REVIEW

**Comment by atlemann** [comment]
So, what's up with the Travis build? Does it break from time to time or did my changes break something?

**Comment by atlemann** [comment]
Why I'm asking about `PrivateAssets` is that I have a scenario where I have `copy_local: false` for some packages in the `paket.dependencies` file and `copy_local: true` in some `paket.references` files (for a unit-test projects). This combination of setting `copy_local` ends up setting `PrivateAssets=All` for those packages. Why is the `copy_local` flag used to set `PrivateAssets=All` when it is `ExcludeAssets=runtime` that enables the expected behavior?

**Comment by atlemann** [comment]
Other than the `PrivateAssets` thing, the changes committed fixes my issue. Should I remove the WIP and open another issue with the `PrivateAssets` thing instead?

**Comment by atlemann** [comment]
I guess this is why: #2951

**Comment by atlemann** [comment]
I'm done with this one as it fixes the problem I had with opening projects in VS2017 with `copy_local: false`.

**Comment by atlemann** [comment]
Unless I have to change the `PaketPropsVersion` in `RestoreProcess.fs` since I'm now editing the `.paket.props file`

**Comment by atlemann** [comment]
@forki @matthid Sorry for bothering you, but these changes fixes the issues I got when converting a C# solution with 180 projects (I know, I want to hang myself) to new SDK format. We're using the `copy_local` option quite extensively and would need this fix or something similar since VS2017 is changing the `runtime` entries in the `project.assets.json` when it loads the projects. This results in the .dlls with `copy_local: false` to be copied to the `bin` folders anyway.

Is there another way to fix this I should try instead?
Do you have some advice on how to add a test for this? 

Running `build.sh` is all green locally, so I'm not sure why the builds are failing here.

**Comment by matthid** [comment]
@atlemann Thanks for the PR.

Regarding the Code: I think there should be a built-in to get the "package settings" after considering the paket.references file. So I'm a bit hesitant about doing that manually.

Regarding the Test-Suite: Yes it is probably broken again. I assume at least appveyor should be green again after adding the netcoreapp2.2 changes to the integration test suite (/cc @forki )

**Comment by atlemann** [comment]
Um, not sure I follow what you mean by `built-in`?

**Comment by atlemann** [comment]
@matthid Is there anything I can change to make it mergable? I basically have to postpone switching to new SDK format due to this.

**Comment by forki** [comment]
please merge with master

**Comment by atlemann** [comment]
At least the Appveyor build succeeded again now

**Pull request merged**
