### PR TITLE
Add () to all calls of rest method "Packages" that have no argument (#3575)

### PR DESCRIPTION
**Pull request by keroiber**

### CODE REVIEW

**Comment by forki** [comment]
@matthid did we do this on purpose because some other feed needs it like this?

**Comment by matthid** [comment]
Yes I think other feeds don't like the braces

**Comment by forki** [comment]
so what now??

**Comment by matthid** [comment]
Our current workflow is we release and revert, forget and repeat ;)

**Comment by keroiber** [comment]
I have investigated some more. Our Artifactory server also supports Nuget V3 but the problem here is that it doesn't expose the resources with ".../api/nuget/v3/packages-nuget/index.json" but only ".../api/nuget/v3/packages-nuget", so paket does not recognise this api.
A solution here would be to remove the "index.json" from the regex in packagesources.fs:

```
                    if Regex("/v3(?:/[-\w]+)?$").IsMatch source then
                        NuGetV3 { Url = source; Authentication = auth }
                    else
                        NuGetV2 { Url = source; Authentication = auth }
```
instead of
```
                    if Regex("/v3(?:/[-\w]+)?/index.json$").IsMatch source then
                        NuGetV3 { Url = source; Authentication = auth }
                    else
                        NuGetV2 { Url = source; Authentication = auth }
```

**Comment by forki** [comment]
mmm that could work as well

**Comment by keroiber** [comment]
I've added a new pull request with this proposal

[https://github.com/fsprojects/Paket/pull/3588]

**Comment by matthid** [comment]
but this is not really fixed is it?

**Comment by keroiber** [comment]
You're right. A solution that doesn't break other feeds would be to try with braces only if the call without braces fails

**Comment by matthid** [comment]
Ok with all the PRs I missed that #3575 is actually still open

**Pull request closed without merging**
