### PR TITLE
Update the blacklist terminology to be more inclusive

### PR DESCRIPTION
**Pull request by ruhullahshah**
This commit is an attempt to remove the usage of the terminology "blacklist" within this project and rather use an inclusive terminology that is acceptable to a wider audience (devs/users) without running into the danger of hurting sentiments and thereby doing away with colonial-era terminology.

As an example, https://thenewstack.io/words-matter-finally-tech-looks-at-removing-exclusionary-language/

### CODE REVIEW

**Comment by forki** [comment]
thank you!

**Comment by ruhullahshah** [comment]
@forki You are welcome. I do not know the reason for the failing tests though. Running tests locally works.

**Comment by Greifenkralle** [comment]
A step into the right direction. 👍

**Comment by ruhullahshah** [comment]
@forki Is there something I can/have to do to make the failing checks pass?

**Pull request merged**
