### PR TITLE
[WIP] Add license expression and icon to template spec

### PR DESCRIPTION
**Pull request by cartermp**
My attempt at #3710, but minus the deprecation parts

### CODE REVIEW

**Comment by forki** [comment]
what's the status?

**Comment by cartermp** [comment]
I need to figure out how to actually pack files with paket.template. Can't seem to figure it out :/

**Comment by CaptnCodr** [comment]
Can we go on here? These nuget deprecation hints are annoying.

**Comment by baronfel** [comment]
@CaptnCodr you can also put the license expression in your project file and pack with `dotnet pack` these days, you don't need to use paket.template.

**Comment by CaptnCodr** [comment]
@baronfel How about the deprecated "iconUrl"?

**Comment by baronfel** [comment]
@CaptnCodr https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#packageicon this help doc describes what properties you'd use to set an image, along with a number of others. note that nuget now wants you to embed the icon instead of pointing to an external resource.

**Comment by cartermp** [comment]
This one should be easy enough, I just kind of gave up on some of the integration tests largely because...I couldn't write a proper paket.template file :/

**Comment by CaptnCodr** [comment]
Yes, I see. But we only use the paket.template to generate our nuget packages.
But why isn't it implemented like "license" which is the reaction on the deprecation of "licenseUrl" so how about to go on here and you have one PR from the list and an issue from the other? 😄

**Comment by cartermp** [comment]
I think we'd all be happy to take a PR that only does each one at a time.

**Comment by cartermp** [comment]
`license` is also added as per here: https://github.com/fsprojects/Paket/pull/3824

**Comment by CaptnCodr** [comment]
Ah yes.

**Pull request closed without merging**
