### PR TITLE
Use AES encryption when not on windows

### PR DESCRIPTION
**Pull request by bengobeil**
(cherry picked from commit b22361ce510ab530c8f8886f012d617893e61a8d)

### CODE REVIEW

**Comment by bengobeil** [comment]
If we can release this today, it will be very helpful for us. Thanks!

**Comment by forki** [comment]
image

**Comment by bengobeil** [comment]
What are the repro steps?

**Comment by bengobeil** [comment]
Oh its just doesn't build... one sec

**Comment by bengobeil** [comment]
Oh, probably a different lang version on 5.XXX ?

**Comment by forki** [comment]
yes it's old school ;-)

**Comment by bengobeil** [comment]
OK, it was a case of implicit yields

**Comment by forki** [comment]
Cool. Will release as soon as I'm back home

**Comment by bengobeil** [comment]
Great thanks!

**Pull request merged**
