### PR TITLE
WIP: Watcher

### PR DESCRIPTION
**Pull request by forki**
/cc @voiceofwisdom

### CODE REVIEW

**Comment by voiceofwisdom** [comment]
Looking at the file access times on the files that seem to be causing the `WatchChanges` to fire again, the DateModified is actually changing. Do you know anything that could be causing that?

**Comment by voiceofwisdom** [comment]
Running the `GenerateHelp` task all on its own causes those files to change on my box. Perhaps something to do with FSharp.Formatting is touching those files?

**Comment by forki** [comment]
@voiceofwisdom yes I can confirm. This happens even without your watcher. So I created https://github.com/tpetricek/FSharp.Formatting/issues/310

**Comment by matthid** [comment]
As explained in https://github.com/tpetricek/FSharp.Formatting/issues/310#issuecomment-98459889 the problem is probably [here](https://github.com/fsprojects/Paket/blob/master/docs/tools/generate.fsx#L6).

**Comment by forki** [comment]
thanks. I was able to work around this. All is well.

**Pull request merged**
