### PR TITLE
Option to force a binding redirects

### PR DESCRIPTION
**Pull request by mrinaldi**
This PR introduces the `redirects: force` to force a binding redirect to be written in the config as discussed in https://github.com/fsprojects/Paket/issues/1270#issuecomment-161368074.

It also introduces the redirects settings to references files.
I'm not sure if this was supposed to work before, but it wasn't and there were no doc regarding it.

Docs were updated accordingly.

### CODE REVIEW

**Comment by forki** [comment]
very cool. /cc @isaacabraham @dnauck

**Comment by forki** [comment]
awesome stuff

**Comment by forki** [comment]
works like a charme

works

**Comment by mrinaldi** [comment]
:smiley:

**Pull request merged**
