### PR TITLE
Prevent Simplifier removing item if it has settings or version requirements

### PR DESCRIPTION
**Pull request by BlythMeister**
I noticed that when i had any settings or version requirements in references/dependencies files and run a simplify it would remove these items and therefore remove the settings.

Now, as well as the item being implied as a transitive dependency, it also needs to have no settings or version requirements in order to be removed.

### CODE REVIEW

**Comment by BlythMeister** [comment]
@forki are these build failures mine, or pre-existing.  It is quite confusing 😕

**Comment by BlythMeister** [comment]
This one is ready

**Comment by forki** [comment]
can you please merge with master?

**Comment by BlythMeister** [comment]
@forki done :)

**Pull request merged**
